// Code generated by dagnabit; DO NOT EDIT.

package output_format

import internal "github.com/amarbel-llc/madder/go/internal/charlie/output_format"

type (
	Format = internal.Format
)

const (
	Default         = internal.Default
	FlagDescription = internal.FlagDescription
	FormatAuto      = internal.FormatAuto
	FormatJSON      = internal.FormatJSON
	FormatTAP       = internal.FormatTAP
)
