// Code generated by dagnabit (0.4.1+4bf4c5f); DO NOT EDIT.

package output_format

import internal "github.com/amarbel-llc/madder/go/internal/charlie/output_format"

// Format selects the encoding of a command's per-record result stream.
//
// auto (default): TAP on a TTY; otherwise the command's piped default (ndjson for most commands, ndjson-crap for sync).
// tap:            TAP format regardless of stdout.
// json:           single JSON document (command-specific shape).
//
//	For streaming commands this is an alias for ndjson.
//
// ndjson:         one JSON object per line.
// crap:           ndjson-crap records, one JSON record per line (go-crap v2).
type Format = internal.Format

// IsTTY reports whether stdout is an interactive terminal.
var IsTTY = internal.IsTTY

// Default is the value to initialize a flag field with.
const Default = internal.Default

// FlagDescription is a suggested description for use with flag.Var so all
// commands present the same help text.
const (
	FlagDescription = internal.FlagDescription
	FormatAuto      = internal.FormatAuto
	FormatCRAP      = internal.FormatCRAP
	FormatJSON      = internal.FormatJSON
	FormatNDJSON    = internal.FormatNDJSON
	FormatTAP       = internal.FormatTAP
)
