// Code generated by dagnabit (0.4.1+7e15e98); DO NOT EDIT.

package markl_registrations

import internal "github.com/amarbel-llc/madder/go/internal/charlie/markl_registrations"

// PurposeIdAlias names a purposeId-shaped string that
// markl.GetFormatOrError should resolve as if it were the named
// formatId. See markl.RegisterPurposeIdAlias for the registration call.
type PurposeIdAlias = internal.PurposeIdAlias

var (
	AliasDodderRepoPrivateKeyV1 = internal.AliasDodderRepoPrivateKeyV1
	AliasZitRepoPrivateKeyV1    = internal.AliasZitRepoPrivateKeyV1
)

// AllAliases is the canonical, ordered list of purpose-id → format-id
// aliases madder registers. Order is deterministic but consumers must
// not depend on it.
//
// TODO(#108) codegen this slice from the per-alias vars (same shape
// as AllPurposes).
var AllAliases = internal.AllAliases

// AllPurposes is the canonical, ordered list of purposes madder
// registers. Order is deterministic but consumers must not depend on
// it — registration is order-independent under markl's lazy Related
// validation (ADR 0006).
//
// TODO(#108) codegen this slice from the per-purpose vars so adding
// a new Purpose*Opts entry doesn't require a manual append.
var (
	AllPurposes                        = internal.AllPurposes
	PurposeBlobStoreConfigDigestV1Opts = internal.PurposeBlobStoreConfigDigestV1Opts
	PurposeMadderPrivateKeyV0Opts      = internal.PurposeMadderPrivateKeyV0Opts
	PurposeMadderPrivateKeyV1Opts      = internal.PurposeMadderPrivateKeyV1Opts
	PurposeMadderPubKeyV1Opts          = internal.PurposeMadderPubKeyV1Opts
)

// Papi document signature (jointly owned with amarbel-llc/papi;
// mirrored in the piggy-markl crate for the producer side). A slot-9A
// ecdsa-sha2-nistp256 SSH signature over a PAPI document's JCS bytes,
// carried as the 64-byte r‖s ecdsa_p256_sig payload after SSH-wire
// framing is stripped. Registered here transitionally — papi has no
// Go registration site yet and piggy's module registers only piggy-*
// purposes; it moves to its owner per madder#255's ownership model.
// Spans only ecdsa_p256_sig — PAPI's slot-9A YubiKey co-sign world is
// all P-256; widening to ed25519_sig later is backward-compatible
// (existing IDs still validate), so start narrow and amend if a
// software signer appears.
var PurposePapiDocSigV1Opts = internal.PurposePapiDocSigV1Opts
