// Code generated by dagnabit (0.6.2+09d2433); DO NOT EDIT.

package tap_diagnostics

import internal "code.linenisgreat.com/madder/go/internal/charlie/tap_diagnostics"

var FromError = internal.FromError
