// Code generated by dagnabit (0.4.0+42941ba); DO NOT EDIT.

package tap_diagnostics

import internal "github.com/amarbel-llc/madder/go/internal/charlie/tap_diagnostics"

var FromError = internal.FromError
