// Code generated by dagnabit (0.4.1+dirty); DO NOT EDIT.

package tap_diagnostics

import internal "code.linenisgreat.com/madder/go/internal/charlie/tap_diagnostics"

var FromError = internal.FromError
