// Code generated by dagnabit; DO NOT EDIT.

package scoped_id

import internal "github.com/amarbel-llc/madder/go/internal/alfa/scoped_id"

// ErrIdDigestVsLegacyConfig is returned when a blob-store-id carries
// a digest suffix but the resolved store's config is legacy (no `@`
// against an un-digestable config defeats the point of the suffix,
// so the error is hard and points the user at the migration command.
type ErrIdDigestVsLegacyConfig = internal.ErrIdDigestVsLegacyConfig

// Id is a scoped id: a location-prefixed, optionally-named handle to an
// addressable root — a madder blob store or a dodder repo. cwdDepth is a
// runtime CLI-rendering concern,
// only meaningful when location == Cwd: 0 = single-dot prefix (the
// deepest `.<utility>/` ancestor on the walk-up), 1 = `..`, etc. Wire-
// format serialization via MarshalText always emits the canonical
// single-dot form so on-disk refs stay stable across CWDs (#145).
//
// remoteFirst is the FDR-0019 system-scope spelling marker, only
// meaningful when location == XDGSystem: the `/name` spelling parses as
// remote-first (consult the consuming repo's remotes, fall back to the
// system-scoped `name`), while `//name` forces the system scope and
// never matches a remote. madder has no remote transport, so it ignores
// the marker and resolves both spellings to the system scope; dodder
// reads it to drive remote-first resolution. (See blob-store(7).)
type (
	Id                 = internal.Id
	LocationType       = internal.LocationType
	LocationTypeGetter = internal.LocationTypeGetter
)

var (
	LocationTypeCwd       = internal.LocationTypeCwd
	LocationTypeUnknown   = internal.LocationTypeUnknown
	LocationTypeXDGCache  = internal.LocationTypeXDGCache
	LocationTypeXDGSystem = internal.LocationTypeXDGSystem
	LocationTypeXDGUser   = internal.LocationTypeXDGUser
	Make                  = internal.Make
	MakeWithLocation      = internal.MakeWithLocation
)
