// Code generated by tommy; DO NOT EDIT.

package zettel_id_log

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V1Document struct {
	data     V1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV1(input []byte) (*V1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V1Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "side":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.Side.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("side: %w", err)
				}
				d.consumed["side"] = true
			}
		case "tai":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.Tai.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("tai: %w", err)
				}
				d.consumed["tai"] = true
			}
		case "markl-id":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.MarklId.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("markl-id: %w", err)
				}
				d.consumed["markl-id"] = true
			}
		case "word-count":
			if v, ok := cst.ExtractInt(_kv); ok {
				d.data.WordCount = v
				d.consumed["word-count"] = true
			}
		}
	}
	return d, nil
}
func (d *V1Document) Data() *V1 {
	return &d.data
}
func (d *V1Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Side.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("side: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "side", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Tai.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("tai: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "tai", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.MarklId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("markl-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "markl-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.WordCount != 0 || cst.HasValue(d.cstDoc.Root(), "word-count") {
		if err := cst.SetAny(d.cstDoc.Root(), "word-count", d.data.WordCount); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *V1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *V1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *V1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *V1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *V1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeV1Into(data *V1, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "side":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.Side.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("side: %w", err)
				}
				consumed[keyPrefix+"side"] = true
			}
		case "tai":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.Tai.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("tai: %w", err)
				}
				consumed[keyPrefix+"tai"] = true
			}
		case "markl-id":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.MarklId.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("markl-id: %w", err)
				}
				consumed[keyPrefix+"markl-id"] = true
			}
		case "word-count":
			if v, ok := cst.ExtractInt(_kv); ok {
				data.WordCount = v
				consumed[keyPrefix+"word-count"] = true
			}
		}
	}
	return nil
}
func EncodeV1From(data *V1, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.Side.MarshalText()
		if err != nil {
			return fmt.Errorf("side: %w", err)
		}
		if err := cst.SetAny(container, "side", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Tai.MarshalText()
		if err != nil {
			return fmt.Errorf("tai: %w", err)
		}
		if err := cst.SetAny(container, "tai", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.MarklId.MarshalText()
		if err != nil {
			return fmt.Errorf("markl-id: %w", err)
		}
		if err := cst.SetAny(container, "markl-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.WordCount != 0 || cst.HasValue(container, "word-count") {
		if err := cst.SetAny(container, "word-count", data.WordCount); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
