// Code generated by dagnabit (0.4.1+f3ad3d5); DO NOT EDIT.

package markl_io

import internal "github.com/amarbel-llc/madder/go/internal/alfa/markl_io"

var (
	MakeNopReadCloser    = internal.MakeNopReadCloser
	MakeReadCloser       = internal.MakeReadCloser
	MakeReadCloserTee    = internal.MakeReadCloserTee
	MakeWriter           = internal.MakeWriter
	MakeWriterWithRepool = internal.MakeWriterWithRepool
)
