// Code generated by dagnabit (0.5.0+3734c11); DO NOT EDIT.

package markl_io

import internal "code.linenisgreat.com/madder/go/internal/alfa/markl_io"

var (
	MakeNopReadCloser    = internal.MakeNopReadCloser
	MakeReadCloser       = internal.MakeReadCloser
	MakeReadCloserTee    = internal.MakeReadCloserTee
	MakeWriter           = internal.MakeWriter
	MakeWriterWithRepool = internal.MakeWriterWithRepool
)
