// Code generated by dagnabit; DO NOT EDIT.

package blech32

import internal "github.com/amarbel-llc/madder/go/internal/alfa/blech32"

type (
	Value = internal.Value
)

var (
	Decode                        = internal.Decode
	DecodeDataOnly                = internal.DecodeDataOnly
	DecodeString                  = internal.DecodeString
	DecodeWithHRPOverride         = internal.DecodeWithHRPOverride
	Encode                        = internal.Encode
	EncodeDataOnly                = internal.EncodeDataOnly
	EncodeHRPAsData               = internal.EncodeHRPAsData
	ErrEmptyHRP                   = internal.ErrEmptyHRP
	ErrInvalidChecksum            = internal.ErrInvalidChecksum
	ErrMixedCase                  = internal.ErrMixedCase
	ErrSeparatorMissing           = internal.ErrSeparatorMissing
	MakeValue                     = internal.MakeValue
	MakeValueWithExpectedHRP      = internal.MakeValueWithExpectedHRP
	VerifyChecksumWithHRPOverride = internal.VerifyChecksumWithHRPOverride
)
