// Code generated by dagnabit; DO NOT EDIT.

package xdg_location_type

import internal "github.com/amarbel-llc/madder/go/internal/0/xdg_location_type"

type (
	Type       = internal.Type
	TypeGetter = internal.TypeGetter
	Typee      = internal.Typee
)

const (
	Cwd       = internal.Cwd
	Unknown   = internal.Unknown
	XDGCache  = internal.XDGCache
	XDGSystem = internal.XDGSystem
	XDGUser   = internal.XDGUser
)
