// Code generated by dagnabit (0.5.0+3734c11); DO NOT EDIT.

package xdg_location_type

import internal "code.linenisgreat.com/madder/go/internal/0/xdg_location_type"

type (
	Type       = internal.Type
	TypeGetter = internal.TypeGetter
	Typee      = internal.Typee
)

const (
	Cwd       = internal.Cwd
	Unknown   = internal.Unknown
	XDGCache  = internal.XDGCache
	XDGSystem = internal.XDGSystem
	XDGUser   = internal.XDGUser
)
