// Code generated by dagnabit (0.4.1+4bf4c5f); DO NOT EDIT.

package env_local

import internal "github.com/amarbel-llc/madder/go/internal/foxtrot/env_local"

type Env = internal.Env

var Make = internal.Make
