// Code generated by dagnabit (0.6.2+4d808f7); DO NOT EDIT.

package env_local

import internal "code.linenisgreat.com/madder/go/internal/foxtrot/env_local"

type Env = internal.Env

var Make = internal.Make
