// Code generated by dagnabit; DO NOT EDIT.

package mmap_blob

import internal "github.com/amarbel-llc/madder/go/internal/foxtrot/mmap_blob"

type (
	MmapBlob = internal.MmapBlob
)

var (
	ErrDigestMismatch          = internal.ErrDigestMismatch
	ErrMmapUnsupported         = internal.ErrMmapUnsupported
	MakeMmapBlobFromBlobReader = internal.MakeMmapBlobFromBlobReader
)
