// Code generated by tommy 0.4.7 (d71e1b5); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlWebDAVV0Document struct {
	data   TomlWebDAVV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlWebDAVV0(input []byte) (*TomlWebDAVV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlWebDAVV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vUrl, _ok := model.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			d.data.URL = _x
			_vUrl.MarkConsumed()
		}
	}
	if _vUser, _ok := model.Get("user"); _ok && _vUser.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
			d.data.User = _x
			_vUser.MarkConsumed()
		}
	}
	if _vPassword, _ok := model.Get("password"); _ok && _vPassword.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPassword.Leaf); _xok {
			d.data.Password = _x
			_vPassword.MarkConsumed()
		}
	}
	if _vBearerToken, _ok := model.Get("bearer-token"); _ok && _vBearerToken.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBearerToken.Leaf); _xok {
			d.data.BearerToken = _x
			_vBearerToken.MarkConsumed()
		}
	}
	if _vTlsClientCertPath, _ok := model.Get("tls-client-cert-path"); _ok && _vTlsClientCertPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientCertPath.Leaf); _xok {
			d.data.TLSClientCertPath = _x
			_vTlsClientCertPath.MarkConsumed()
		}
	}
	if _vTlsClientKeyPath, _ok := model.Get("tls-client-key-path"); _ok && _vTlsClientKeyPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientKeyPath.Leaf); _xok {
			d.data.TLSClientKeyPath = _x
			_vTlsClientKeyPath.MarkConsumed()
		}
	}
	if _vTlsCaPath, _ok := model.Get("tls-ca-path"); _ok && _vTlsCaPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsCaPath.Leaf); _xok {
			d.data.TLSCAPath = _x
			_vTlsCaPath.MarkConsumed()
		}
	}
	if _vTlsServerName, _ok := model.Get("tls-server-name"); _ok && _vTlsServerName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsServerName.Leaf); _xok {
			d.data.TLSServerName = _x
			_vTlsServerName.MarkConsumed()
		}
	}
	if _vTlsInsecureSkipVerify, _ok := model.Get("tls-insecure-skip-verify"); _ok && _vTlsInsecureSkipVerify.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vTlsInsecureSkipVerify.Leaf); _xok {
			d.data.TLSInsecureSkipVerify = _x
			_vTlsInsecureSkipVerify.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlWebDAVV0Document) Data() *TomlWebDAVV0 {
	return &d.data
}

func (d *TomlWebDAVV0Document) Encode() ([]byte, error) {
	if d.data.URL != "" || cst.HasValue(d.cstDoc.Root(), "url") {
		if err := cst.SetAny(d.cstDoc.Root(), "url", d.data.URL); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.User != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "user", d.data.User); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "user")
	}
	if d.data.Password != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "password", d.data.Password); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "password")
	}
	if d.data.BearerToken != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "bearer-token", d.data.BearerToken); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "bearer-token")
	}
	if d.data.TLSClientCertPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-client-cert-path", d.data.TLSClientCertPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-client-cert-path")
	}
	if d.data.TLSClientKeyPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-client-key-path", d.data.TLSClientKeyPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-client-key-path")
	}
	if d.data.TLSCAPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-ca-path", d.data.TLSCAPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-ca-path")
	}
	if d.data.TLSServerName != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-server-name", d.data.TLSServerName); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-server-name")
	}
	if d.data.TLSInsecureSkipVerify != false {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-insecure-skip-verify", d.data.TLSInsecureSkipVerify); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-insecure-skip-verify")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlWebDAVV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlWebDAVV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlWebDAVV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlWebDAVV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlWebDAVV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlWebDAVV0Into(data *TomlWebDAVV0, sub *cst.Value) error {
	if _vUrl, _ok := sub.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			data.URL = _x
			_vUrl.MarkConsumed()
		}
	}
	if _vUser, _ok := sub.Get("user"); _ok && _vUser.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
			data.User = _x
			_vUser.MarkConsumed()
		}
	}
	if _vPassword, _ok := sub.Get("password"); _ok && _vPassword.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPassword.Leaf); _xok {
			data.Password = _x
			_vPassword.MarkConsumed()
		}
	}
	if _vBearerToken, _ok := sub.Get("bearer-token"); _ok && _vBearerToken.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBearerToken.Leaf); _xok {
			data.BearerToken = _x
			_vBearerToken.MarkConsumed()
		}
	}
	if _vTlsClientCertPath, _ok := sub.Get("tls-client-cert-path"); _ok && _vTlsClientCertPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientCertPath.Leaf); _xok {
			data.TLSClientCertPath = _x
			_vTlsClientCertPath.MarkConsumed()
		}
	}
	if _vTlsClientKeyPath, _ok := sub.Get("tls-client-key-path"); _ok && _vTlsClientKeyPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientKeyPath.Leaf); _xok {
			data.TLSClientKeyPath = _x
			_vTlsClientKeyPath.MarkConsumed()
		}
	}
	if _vTlsCaPath, _ok := sub.Get("tls-ca-path"); _ok && _vTlsCaPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsCaPath.Leaf); _xok {
			data.TLSCAPath = _x
			_vTlsCaPath.MarkConsumed()
		}
	}
	if _vTlsServerName, _ok := sub.Get("tls-server-name"); _ok && _vTlsServerName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsServerName.Leaf); _xok {
			data.TLSServerName = _x
			_vTlsServerName.MarkConsumed()
		}
	}
	if _vTlsInsecureSkipVerify, _ok := sub.Get("tls-insecure-skip-verify"); _ok && _vTlsInsecureSkipVerify.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vTlsInsecureSkipVerify.Leaf); _xok {
			data.TLSInsecureSkipVerify = _x
			_vTlsInsecureSkipVerify.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlWebDAVV0From(data *TomlWebDAVV0, doc *document.Document, container *cst.Node) error {
	if data.URL != "" || cst.HasValue(container, "url") {
		if err := cst.SetAny(container, "url", data.URL); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.User != "" {
		if err := cst.SetAny(container, "user", data.User); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "user")
	}
	if data.Password != "" {
		if err := cst.SetAny(container, "password", data.Password); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "password")
	}
	if data.BearerToken != "" {
		if err := cst.SetAny(container, "bearer-token", data.BearerToken); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "bearer-token")
	}
	if data.TLSClientCertPath != "" {
		if err := cst.SetAny(container, "tls-client-cert-path", data.TLSClientCertPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-client-cert-path")
	}
	if data.TLSClientKeyPath != "" {
		if err := cst.SetAny(container, "tls-client-key-path", data.TLSClientKeyPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-client-key-path")
	}
	if data.TLSCAPath != "" {
		if err := cst.SetAny(container, "tls-ca-path", data.TLSCAPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-ca-path")
	}
	if data.TLSServerName != "" {
		if err := cst.SetAny(container, "tls-server-name", data.TLSServerName); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-server-name")
	}
	if data.TLSInsecureSkipVerify != false {
		if err := cst.SetAny(container, "tls-insecure-skip-verify", data.TLSInsecureSkipVerify); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-insecure-skip-verify")
	}
	return nil
}
