// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/madder/go/internal/bravo/markl"
	"github.com/amarbel-llc/purse-first/libs/dewey/pkgs/values"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlV3Document struct {
	data     TomlV3
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV3(input []byte) (*TomlV3Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV3Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "hash_buckets":
			if v, ok := cst.ExtractIntSlice(_kv); ok {
				d.data.HashBuckets = values.IntSlice(v)
				d.consumed["hash_buckets"] = true
			}
		case "base_path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.BasePath = v
				d.consumed["base_path"] = true
			}
		case "hash_type-id":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("hash_type-id: %w", err)
				}
				d.consumed["hash_type-id"] = true
			}
		case "encryption":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.Encryption = make([]markl.Id, len(v))
				for _si, _s := range v {
					if err := d.data.Encryption[_si].UnmarshalText([]byte(_s)); err != nil {
						return nil, fmt.Errorf("encryption[%d]: %w", _si, err)
					}
				}
				d.consumed["encryption"] = true
			}
		case "compression-type":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.CompressionType = v
				d.consumed["compression-type"] = true
			}
		case "verify-on-collision":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.VerifyOnCollision = v
				d.consumed["verify-on-collision"] = true
			}
		case "single_hash":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.SingleHash = v
				d.consumed["single_hash"] = true
			}
		}
	}
	return d, nil
}

func (d *TomlV3Document) Data() *TomlV3 {
	return &d.data
}

func (d *TomlV3Document) Encode() ([]byte, error) {
	{
		if err := cst.SetAny(d.cstDoc.Root(), "hash_buckets", []int(d.data.HashBuckets)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.BasePath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "base_path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "base_path")
	}
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		vals := make([]string, len(d.data.Encryption))
		for i, item := range d.data.Encryption {
			v, err := item.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("encryption[%d]: %w", i, err)
			}
			vals[i] = string(v)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "encryption", vals); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.CompressionType != "" || cst.HasValue(d.cstDoc.Root(), "compression-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "compression-type", d.data.CompressionType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.VerifyOnCollision != false || cst.HasValue(d.cstDoc.Root(), "verify-on-collision") {
		if err := cst.SetAny(d.cstDoc.Root(), "verify-on-collision", d.data.VerifyOnCollision); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.SingleHash != false {
		if err := cst.SetAny(d.cstDoc.Root(), "single_hash", d.data.SingleHash); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "single_hash")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlV3Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlV3Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV3Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV3Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV3Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV3Into(data *TomlV3, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "hash_buckets":
			if v, ok := cst.ExtractIntSlice(_kv); ok {
				data.HashBuckets = values.IntSlice(v)
				consumed[keyPrefix+"hash_buckets"] = true
			}
		case "base_path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.BasePath = v
				consumed[keyPrefix+"base_path"] = true
			}
		case "hash_type-id":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("hash_type-id: %w", err)
				}
				consumed[keyPrefix+"hash_type-id"] = true
			}
		case "encryption":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.Encryption = make([]markl.Id, len(v))
				for _si, _s := range v {
					if err := data.Encryption[_si].UnmarshalText([]byte(_s)); err != nil {
						return fmt.Errorf("encryption[%d]: %w", _si, err)
					}
				}
				consumed[keyPrefix+"encryption"] = true
			}
		case "compression-type":
			if v, ok := cst.ExtractString(_kv); ok {
				data.CompressionType = v
				consumed[keyPrefix+"compression-type"] = true
			}
		case "verify-on-collision":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.VerifyOnCollision = v
				consumed[keyPrefix+"verify-on-collision"] = true
			}
		case "single_hash":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.SingleHash = v
				consumed[keyPrefix+"single_hash"] = true
			}
		}
	}
	return nil
}

func EncodeTomlV3From(data *TomlV3, doc *document.Document, container *cst.Node) error {
	{
		if err := cst.SetAny(container, "hash_buckets", []int(data.HashBuckets)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.BasePath != "" {
		if err := cst.SetAny(container, "base_path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "base_path")
	}
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(container, "hash_type-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		vals := make([]string, len(data.Encryption))
		for i, item := range data.Encryption {
			v, err := item.MarshalText()
			if err != nil {
				return fmt.Errorf("encryption[%d]: %w", i, err)
			}
			vals[i] = string(v)
		}
		if err := cst.SetAny(container, "encryption", vals); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.CompressionType != "" || cst.HasValue(container, "compression-type") {
		if err := cst.SetAny(container, "compression-type", data.CompressionType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.VerifyOnCollision != false || cst.HasValue(container, "verify-on-collision") {
		if err := cst.SetAny(container, "verify-on-collision", data.VerifyOnCollision); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.SingleHash != false {
		if err := cst.SetAny(container, "single_hash", data.SingleHash); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "single_hash")
	}
	return nil
}
