// Code generated by tommy 0.4.7 (d9d6558); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlSFTPV0Document struct {
	data   TomlSFTPV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlSFTPV0(input []byte) (*TomlSFTPV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlSFTPV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vHost, _ok := model.Get("host"); _ok && _vHost.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHost.Leaf); _xok {
			d.data.Host = _x
			_vHost.MarkConsumed()
		}
	}
	if _vPort, _ok := model.Get("port"); _ok && _vPort.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vPort.Leaf); _xok {
			d.data.Port = _x
			_vPort.MarkConsumed()
		}
	}
	if _vUser, _ok := model.Get("user"); _ok && _vUser.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
			d.data.User = _x
			_vUser.MarkConsumed()
		}
	}
	if _vPassword, _ok := model.Get("password"); _ok && _vPassword.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPassword.Leaf); _xok {
			d.data.Password = _x
			_vPassword.MarkConsumed()
		}
	}
	if _vPrivateKeyPath, _ok := model.Get("private-key-path"); _ok && _vPrivateKeyPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPrivateKeyPath.Leaf); _xok {
			d.data.PrivateKeyPath = _x
			_vPrivateKeyPath.MarkConsumed()
		}
	}
	if _vRemotePath, _ok := model.Get("remote-path"); _ok && _vRemotePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vRemotePath.Leaf); _xok {
			d.data.RemotePath = _x
			_vRemotePath.MarkConsumed()
		}
	}
	if _vKnownHostsFile, _ok := model.Get("known-hosts-file"); _ok && _vKnownHostsFile.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKnownHostsFile.Leaf); _xok {
			d.data.KnownHostsFile = _x
			_vKnownHostsFile.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlSFTPV0Document) Data() *TomlSFTPV0 {
	return &d.data
}

func (d *TomlSFTPV0Document) Encode() ([]byte, error) {
	if d.data.Host != "" || cst.HasValue(d.cstDoc.Root(), "host") {
		if err := cst.SetAny(d.cstDoc.Root(), "host", d.data.Host); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Port != 0 {
		if err := cst.SetAny(d.cstDoc.Root(), "port", d.data.Port); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "port")
	}
	if d.data.User != "" || cst.HasValue(d.cstDoc.Root(), "user") {
		if err := cst.SetAny(d.cstDoc.Root(), "user", d.data.User); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Password != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "password", d.data.Password); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "password")
	}
	if d.data.PrivateKeyPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "private-key-path", d.data.PrivateKeyPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "private-key-path")
	}
	if d.data.RemotePath != "" || cst.HasValue(d.cstDoc.Root(), "remote-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "remote-path", d.data.RemotePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.KnownHostsFile != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "known-hosts-file", d.data.KnownHostsFile); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "known-hosts-file")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlSFTPV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlSFTPV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlSFTPV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlSFTPV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlSFTPV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlSFTPV0Into(data *TomlSFTPV0, sub *cst.Value) error {
	if _vHost, _ok := sub.Get("host"); _ok && _vHost.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHost.Leaf); _xok {
			data.Host = _x
			_vHost.MarkConsumed()
		}
	}
	if _vPort, _ok := sub.Get("port"); _ok && _vPort.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vPort.Leaf); _xok {
			data.Port = _x
			_vPort.MarkConsumed()
		}
	}
	if _vUser, _ok := sub.Get("user"); _ok && _vUser.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
			data.User = _x
			_vUser.MarkConsumed()
		}
	}
	if _vPassword, _ok := sub.Get("password"); _ok && _vPassword.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPassword.Leaf); _xok {
			data.Password = _x
			_vPassword.MarkConsumed()
		}
	}
	if _vPrivateKeyPath, _ok := sub.Get("private-key-path"); _ok && _vPrivateKeyPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPrivateKeyPath.Leaf); _xok {
			data.PrivateKeyPath = _x
			_vPrivateKeyPath.MarkConsumed()
		}
	}
	if _vRemotePath, _ok := sub.Get("remote-path"); _ok && _vRemotePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vRemotePath.Leaf); _xok {
			data.RemotePath = _x
			_vRemotePath.MarkConsumed()
		}
	}
	if _vKnownHostsFile, _ok := sub.Get("known-hosts-file"); _ok && _vKnownHostsFile.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKnownHostsFile.Leaf); _xok {
			data.KnownHostsFile = _x
			_vKnownHostsFile.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlSFTPV0From(data *TomlSFTPV0, doc *document.Document, container *cst.Node) error {
	if data.Host != "" || cst.HasValue(container, "host") {
		if err := cst.SetAny(container, "host", data.Host); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Port != 0 {
		if err := cst.SetAny(container, "port", data.Port); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "port")
	}
	if data.User != "" || cst.HasValue(container, "user") {
		if err := cst.SetAny(container, "user", data.User); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Password != "" {
		if err := cst.SetAny(container, "password", data.Password); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "password")
	}
	if data.PrivateKeyPath != "" {
		if err := cst.SetAny(container, "private-key-path", data.PrivateKeyPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "private-key-path")
	}
	if data.RemotePath != "" || cst.HasValue(container, "remote-path") {
		if err := cst.SetAny(container, "remote-path", data.RemotePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.KnownHostsFile != "" {
		if err := cst.SetAny(container, "known-hosts-file", data.KnownHostsFile); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "known-hosts-file")
	}
	return nil
}
