// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlS3V0Document struct {
	data     TomlS3V0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlS3V0(input []byte) (*TomlS3V0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlS3V0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "endpoint":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Endpoint = v
				d.consumed["endpoint"] = true
			}
		case "region":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Region = v
				d.consumed["region"] = true
			}
		case "bucket":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Bucket = v
				d.consumed["bucket"] = true
			}
		case "prefix":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Prefix = v
				d.consumed["prefix"] = true
			}
		case "access-key-id":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.AccessKeyId = v
				d.consumed["access-key-id"] = true
			}
		case "secret-access-key":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.SecretAccessKey = v
				d.consumed["secret-access-key"] = true
			}
		case "session-token":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.SessionToken = v
				d.consumed["session-token"] = true
			}
		case "use-path-style":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.UsePathStyle = v
				d.consumed["use-path-style"] = true
			}
		case "insecure-skip-tls-verify":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.InsecureSkipVerify = v
				d.consumed["insecure-skip-tls-verify"] = true
			}
		}
	}
	return d, nil
}

func (d *TomlS3V0Document) Data() *TomlS3V0 {
	return &d.data
}

func (d *TomlS3V0Document) Encode() ([]byte, error) {
	if d.data.Endpoint != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "endpoint", d.data.Endpoint); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "endpoint")
	}
	if d.data.Region != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "region", d.data.Region); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "region")
	}
	if d.data.Bucket != "" || cst.HasValue(d.cstDoc.Root(), "bucket") {
		if err := cst.SetAny(d.cstDoc.Root(), "bucket", d.data.Bucket); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Prefix != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "prefix", d.data.Prefix); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "prefix")
	}
	if d.data.AccessKeyId != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "access-key-id", d.data.AccessKeyId); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "access-key-id")
	}
	if d.data.SecretAccessKey != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "secret-access-key", d.data.SecretAccessKey); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "secret-access-key")
	}
	if d.data.SessionToken != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "session-token", d.data.SessionToken); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "session-token")
	}
	if d.data.UsePathStyle != false {
		if err := cst.SetAny(d.cstDoc.Root(), "use-path-style", d.data.UsePathStyle); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "use-path-style")
	}
	if d.data.InsecureSkipVerify != false {
		if err := cst.SetAny(d.cstDoc.Root(), "insecure-skip-tls-verify", d.data.InsecureSkipVerify); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "insecure-skip-tls-verify")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlS3V0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlS3V0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlS3V0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlS3V0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlS3V0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlS3V0Into(data *TomlS3V0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "endpoint":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Endpoint = v
				consumed[keyPrefix+"endpoint"] = true
			}
		case "region":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Region = v
				consumed[keyPrefix+"region"] = true
			}
		case "bucket":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Bucket = v
				consumed[keyPrefix+"bucket"] = true
			}
		case "prefix":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Prefix = v
				consumed[keyPrefix+"prefix"] = true
			}
		case "access-key-id":
			if v, ok := cst.ExtractString(_kv); ok {
				data.AccessKeyId = v
				consumed[keyPrefix+"access-key-id"] = true
			}
		case "secret-access-key":
			if v, ok := cst.ExtractString(_kv); ok {
				data.SecretAccessKey = v
				consumed[keyPrefix+"secret-access-key"] = true
			}
		case "session-token":
			if v, ok := cst.ExtractString(_kv); ok {
				data.SessionToken = v
				consumed[keyPrefix+"session-token"] = true
			}
		case "use-path-style":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.UsePathStyle = v
				consumed[keyPrefix+"use-path-style"] = true
			}
		case "insecure-skip-tls-verify":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.InsecureSkipVerify = v
				consumed[keyPrefix+"insecure-skip-tls-verify"] = true
			}
		}
	}
	return nil
}

func EncodeTomlS3V0From(data *TomlS3V0, doc *document.Document, container *cst.Node) error {
	if data.Endpoint != "" {
		if err := cst.SetAny(container, "endpoint", data.Endpoint); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "endpoint")
	}
	if data.Region != "" {
		if err := cst.SetAny(container, "region", data.Region); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "region")
	}
	if data.Bucket != "" || cst.HasValue(container, "bucket") {
		if err := cst.SetAny(container, "bucket", data.Bucket); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Prefix != "" {
		if err := cst.SetAny(container, "prefix", data.Prefix); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "prefix")
	}
	if data.AccessKeyId != "" {
		if err := cst.SetAny(container, "access-key-id", data.AccessKeyId); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "access-key-id")
	}
	if data.SecretAccessKey != "" {
		if err := cst.SetAny(container, "secret-access-key", data.SecretAccessKey); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "secret-access-key")
	}
	if data.SessionToken != "" {
		if err := cst.SetAny(container, "session-token", data.SessionToken); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "session-token")
	}
	if data.UsePathStyle != false {
		if err := cst.SetAny(container, "use-path-style", data.UsePathStyle); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "use-path-style")
	}
	if data.InsecureSkipVerify != false {
		if err := cst.SetAny(container, "insecure-skip-tls-verify", data.InsecureSkipVerify); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "insecure-skip-tls-verify")
	}
	return nil
}
