// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlSFTPViaSSHConfigV0Document struct {
	data     TomlSFTPViaSSHConfigV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlSFTPViaSSHConfigV0(input []byte) (*TomlSFTPViaSSHConfigV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlSFTPViaSSHConfigV0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "uri":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.Uri.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("uri: %w", err)
				}
				d.consumed["uri"] = true
			}
		case "known-hosts-file":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.KnownHostsFile = v
				d.consumed["known-hosts-file"] = true
			}
		}
	}
	return d, nil
}
func (d *TomlSFTPViaSSHConfigV0Document) Data() *TomlSFTPViaSSHConfigV0 {
	return &d.data
}
func (d *TomlSFTPViaSSHConfigV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Uri.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("uri: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "uri", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.KnownHostsFile != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "known-hosts-file", d.data.KnownHostsFile); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "known-hosts-file")
	}
	return d.cstDoc.Bytes(), nil
}
func (d *TomlSFTPViaSSHConfigV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *TomlSFTPViaSSHConfigV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *TomlSFTPViaSSHConfigV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *TomlSFTPViaSSHConfigV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *TomlSFTPViaSSHConfigV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeTomlSFTPViaSSHConfigV0Into(data *TomlSFTPViaSSHConfigV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "uri":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.Uri.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("uri: %w", err)
				}
				consumed[keyPrefix+"uri"] = true
			}
		case "known-hosts-file":
			if v, ok := cst.ExtractString(_kv); ok {
				data.KnownHostsFile = v
				consumed[keyPrefix+"known-hosts-file"] = true
			}
		}
	}
	return nil
}
func EncodeTomlSFTPViaSSHConfigV0From(data *TomlSFTPViaSSHConfigV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.Uri.MarshalText()
		if err != nil {
			return fmt.Errorf("uri: %w", err)
		}
		if err := cst.SetAny(container, "uri", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.KnownHostsFile != "" {
		if err := cst.SetAny(container, "known-hosts-file", data.KnownHostsFile); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "known-hosts-file")
	}
	return nil
}
