// Code generated by tommy 0.4.7 (b504d1e); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlPointerV0Document struct {
	data   TomlPointerV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlPointerV0(input []byte) (*TomlPointerV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlPointerV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vId, _ok := model.Get("id"); _ok && _vId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
			if err := d.data.Id.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("id: %w", err)
			}
			_vId.MarkConsumed()
		}
	}
	if _vBasePath, _ok := model.Get("base-path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			d.data.BasePath = _x
			_vBasePath.MarkConsumed()
		}
	}
	if _vConfigPath, _ok := model.Get("config-path"); _ok && _vConfigPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfigPath.Leaf); _xok {
			d.data.ConfigPath = _x
			_vConfigPath.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlPointerV0Document) Data() *TomlPointerV0 {
	return &d.data
}

func (d *TomlPointerV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Id.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.BasePath != "" || cst.HasValue(d.cstDoc.Root(), "base-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "base-path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ConfigPath != "" || cst.HasValue(d.cstDoc.Root(), "config-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "config-path", d.data.ConfigPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlPointerV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlPointerV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlPointerV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlPointerV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlPointerV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlPointerV0Into(data *TomlPointerV0, sub *cst.Value) error {
	if _vId, _ok := sub.Get("id"); _ok && _vId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
			if err := data.Id.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("id: %w", err)
			}
			_vId.MarkConsumed()
		}
	}
	if _vBasePath, _ok := sub.Get("base-path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			data.BasePath = _x
			_vBasePath.MarkConsumed()
		}
	}
	if _vConfigPath, _ok := sub.Get("config-path"); _ok && _vConfigPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfigPath.Leaf); _xok {
			data.ConfigPath = _x
			_vConfigPath.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlPointerV0From(data *TomlPointerV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.Id.MarshalText()
		if err != nil {
			return fmt.Errorf("id: %w", err)
		}
		if err := cst.SetAny(container, "id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.BasePath != "" || cst.HasValue(container, "base-path") {
		if err := cst.SetAny(container, "base-path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ConfigPath != "" || cst.HasValue(container, "config-path") {
		if err := cst.SetAny(container, "config-path", data.ConfigPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
