// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type StoreKeyRecipientsV2Document struct {
	data   StoreKeyRecipientsV2
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeStoreKeyRecipientsV2(input []byte) (*StoreKeyRecipientsV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeStoreKeyRecipientsV2Parsed(doc)
}

// DecodeStoreKeyRecipientsV2Strict is DecodeStoreKeyRecipientsV2 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeStoreKeyRecipientsV2 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeStoreKeyRecipientsV2Strict(input []byte) (*StoreKeyRecipientsV2Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeStoreKeyRecipientsV2Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeStoreKeyRecipientsV2Parsed(doc *document.Document) (*StoreKeyRecipientsV2Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &StoreKeyRecipientsV2Document{
		cstDoc: doc,
		model:  model,
	}

	if _vSourceKind, _ok := model.Field("source_kind"); _ok && _vSourceKind.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSourceKind.Leaf); _xok {
			d.data.SourceKind = _x
			_vSourceKind.MarkConsumedString()
		}
	}
	if _vSource, _ok := model.Field("source"); _ok && _vSource.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
			d.data.Source = _x
			_vSource.MarkConsumedString()
		}
	}
	if _vPigpen, _ok := model.Field("pigpen"); _ok && _vPigpen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPigpen.Leaf); _xok {
			d.data.Pigpen = _x
			_vPigpen.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *StoreKeyRecipientsV2Document) Data() *StoreKeyRecipientsV2 {
	return &d.data
}

func (d *StoreKeyRecipientsV2Document) Encode() ([]byte, error) {
	if d.data.SourceKind != "" || cst.HasValue(d.cstDoc.Root(), "source_kind") {
		if err := cst.SetAny(d.cstDoc.Root(), "source_kind", d.data.SourceKind); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Source != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "source", d.data.Source); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "source")
	}
	if d.data.Pigpen != "" {
		if err := cst.SetMultilineString(d.cstDoc.Root(), "pigpen", d.data.Pigpen); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "pigpen")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *StoreKeyRecipientsV2Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *StoreKeyRecipientsV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *StoreKeyRecipientsV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *StoreKeyRecipientsV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *StoreKeyRecipientsV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeStoreKeyRecipientsV2Into(data *StoreKeyRecipientsV2, sub *cst.Value) error {
	if _vSourceKind, _ok := sub.Field("source_kind"); _ok && _vSourceKind.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSourceKind.Leaf); _xok {
			data.SourceKind = _x
			_vSourceKind.MarkConsumedString()
		}
	}
	if _vSource, _ok := sub.Field("source"); _ok && _vSource.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
			data.Source = _x
			_vSource.MarkConsumedString()
		}
	}
	if _vPigpen, _ok := sub.Field("pigpen"); _ok && _vPigpen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPigpen.Leaf); _xok {
			data.Pigpen = _x
			_vPigpen.MarkConsumedString()
		}
	}
	return nil
}

func EncodeStoreKeyRecipientsV2From(data *StoreKeyRecipientsV2, doc *document.Document, container *cst.Node) error {
	if data.SourceKind != "" || cst.HasValue(container, "source_kind") {
		if err := cst.SetAny(container, "source_kind", data.SourceKind); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Source != "" {
		if err := cst.SetAny(container, "source", data.Source); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "source")
	}
	if data.Pigpen != "" {
		if err := cst.SetMultilineString(container, "pigpen", data.Pigpen); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "pigpen")
	}
	return nil
}

type StoreKeySealedV2Document struct {
	data   StoreKeySealedV2
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeStoreKeySealedV2(input []byte) (*StoreKeySealedV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeStoreKeySealedV2Parsed(doc)
}

// DecodeStoreKeySealedV2Strict is DecodeStoreKeySealedV2 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeStoreKeySealedV2 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeStoreKeySealedV2Strict(input []byte) (*StoreKeySealedV2Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeStoreKeySealedV2Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeStoreKeySealedV2Parsed(doc *document.Document) (*StoreKeySealedV2Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &StoreKeySealedV2Document{
		cstDoc: doc,
		model:  model,
	}

	if _vDocument, _ok := model.Field("document"); _ok && _vDocument.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
			d.data.Document = _x
			_vDocument.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *StoreKeySealedV2Document) Data() *StoreKeySealedV2 {
	return &d.data
}

func (d *StoreKeySealedV2Document) Encode() ([]byte, error) {
	if d.data.Document != "" || cst.HasValue(d.cstDoc.Root(), "document") {
		if err := cst.SetMultilineString(d.cstDoc.Root(), "document", d.data.Document); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *StoreKeySealedV2Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *StoreKeySealedV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *StoreKeySealedV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *StoreKeySealedV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *StoreKeySealedV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeStoreKeySealedV2Into(data *StoreKeySealedV2, sub *cst.Value) error {
	if _vDocument, _ok := sub.Field("document"); _ok && _vDocument.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
			data.Document = _x
			_vDocument.MarkConsumedString()
		}
	}
	return nil
}

func EncodeStoreKeySealedV2From(data *StoreKeySealedV2, doc *document.Document, container *cst.Node) error {
	if data.Document != "" || cst.HasValue(container, "document") {
		if err := cst.SetMultilineString(container, "document", data.Document); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type TomlStoreKeyV2Document struct {
	data   TomlStoreKeyV2
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlStoreKeyV2(input []byte) (*TomlStoreKeyV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlStoreKeyV2Parsed(doc)
}

// DecodeTomlStoreKeyV2Strict is DecodeTomlStoreKeyV2 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlStoreKeyV2 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlStoreKeyV2Strict(input []byte) (*TomlStoreKeyV2Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlStoreKeyV2Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlStoreKeyV2Parsed(doc *document.Document) (*TomlStoreKeyV2Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlStoreKeyV2Document{
		cstDoc: doc,
		model:  model,
	}

	if _vRecipients, _ok := model.Field("recipients"); _ok && _vRecipients.Kind == cst.VTable {
		_vRecipients.MarkSeen()
		if _vRecipientsSourceKind, _ok := _vRecipients.Field("source_kind"); _ok && _vRecipientsSourceKind.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsSourceKind.Leaf); _xok {
				d.data.Recipients.SourceKind = _x
				_vRecipientsSourceKind.MarkConsumedString()
			}
		}
		if _vRecipientsSource, _ok := _vRecipients.Field("source"); _ok && _vRecipientsSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsSource.Leaf); _xok {
				d.data.Recipients.Source = _x
				_vRecipientsSource.MarkConsumedString()
			}
		}
		if _vRecipientsPigpen, _ok := _vRecipients.Field("pigpen"); _ok && _vRecipientsPigpen.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsPigpen.Leaf); _xok {
				d.data.Recipients.Pigpen = _x
				_vRecipientsPigpen.MarkConsumedString()
			}
		}
	} else {
		if _vSourceKind, _ok := model.Field("source_kind"); _ok && _vSourceKind.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSourceKind.Leaf); _xok {
				d.data.Recipients.SourceKind = _x
				_vSourceKind.MarkConsumedString()
			}
		}
		if _vSource, _ok := model.Field("source"); _ok && _vSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
				d.data.Recipients.Source = _x
				_vSource.MarkConsumedString()
			}
		}
		if _vPigpen, _ok := model.Field("pigpen"); _ok && _vPigpen.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vPigpen.Leaf); _xok {
				d.data.Recipients.Pigpen = _x
				_vPigpen.MarkConsumedString()
			}
		}
	}
	if _vSealed, _ok := model.Field("sealed"); _ok && _vSealed.Kind == cst.VTable {
		_vSealed.MarkSeen()
		if _vSealedDocument, _ok := _vSealed.Field("document"); _ok && _vSealedDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSealedDocument.Leaf); _xok {
				d.data.Sealed.Document = _x
				_vSealedDocument.MarkConsumedString()
			}
		}
	} else {
		if _vDocument, _ok := model.Field("document"); _ok && _vDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
				d.data.Sealed.Document = _x
				_vDocument.MarkConsumedString()
			}
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *TomlStoreKeyV2Document) Data() *TomlStoreKeyV2 {
	return &d.data
}

func (d *TomlStoreKeyV2Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "recipients")
		if d.data.Recipients.SourceKind != "" || cst.HasValue(tableNode, "source_kind") {
			if err := cst.SetAny(tableNode, "source_kind", d.data.Recipients.SourceKind); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Recipients.Source != "" {
			if err := cst.SetAny(tableNode, "source", d.data.Recipients.Source); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "source")
		}
		if d.data.Recipients.Pigpen != "" {
			if err := cst.SetMultilineString(tableNode, "pigpen", d.data.Recipients.Pigpen); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "pigpen")
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "sealed")
		if d.data.Sealed.Document != "" || cst.HasValue(tableNode, "document") {
			if err := cst.SetMultilineString(tableNode, "document", d.data.Sealed.Document); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlStoreKeyV2Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlStoreKeyV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlStoreKeyV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlStoreKeyV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlStoreKeyV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlStoreKeyV2Into(data *TomlStoreKeyV2, sub *cst.Value) error {
	if _vRecipients, _ok := sub.Field("recipients"); _ok && _vRecipients.Kind == cst.VTable {
		_vRecipients.MarkSeen()
		if _vRecipientsSourceKind, _ok := _vRecipients.Field("source_kind"); _ok && _vRecipientsSourceKind.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsSourceKind.Leaf); _xok {
				data.Recipients.SourceKind = _x
				_vRecipientsSourceKind.MarkConsumedString()
			}
		}
		if _vRecipientsSource, _ok := _vRecipients.Field("source"); _ok && _vRecipientsSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsSource.Leaf); _xok {
				data.Recipients.Source = _x
				_vRecipientsSource.MarkConsumedString()
			}
		}
		if _vRecipientsPigpen, _ok := _vRecipients.Field("pigpen"); _ok && _vRecipientsPigpen.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsPigpen.Leaf); _xok {
				data.Recipients.Pigpen = _x
				_vRecipientsPigpen.MarkConsumedString()
			}
		}
	} else {
		if _vSourceKind, _ok := sub.Field("source_kind"); _ok && _vSourceKind.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSourceKind.Leaf); _xok {
				data.Recipients.SourceKind = _x
				_vSourceKind.MarkConsumedString()
			}
		}
		if _vSource, _ok := sub.Field("source"); _ok && _vSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
				data.Recipients.Source = _x
				_vSource.MarkConsumedString()
			}
		}
		if _vPigpen, _ok := sub.Field("pigpen"); _ok && _vPigpen.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vPigpen.Leaf); _xok {
				data.Recipients.Pigpen = _x
				_vPigpen.MarkConsumedString()
			}
		}
	}
	if _vSealed, _ok := sub.Field("sealed"); _ok && _vSealed.Kind == cst.VTable {
		_vSealed.MarkSeen()
		if _vSealedDocument, _ok := _vSealed.Field("document"); _ok && _vSealedDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSealedDocument.Leaf); _xok {
				data.Sealed.Document = _x
				_vSealedDocument.MarkConsumedString()
			}
		}
	} else {
		if _vDocument, _ok := sub.Field("document"); _ok && _vDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
				data.Sealed.Document = _x
				_vDocument.MarkConsumedString()
			}
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeTomlStoreKeyV2From(data *TomlStoreKeyV2, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "recipients")
		if data.Recipients.SourceKind != "" || cst.HasValue(tableNode, "source_kind") {
			if err := cst.SetAny(tableNode, "source_kind", data.Recipients.SourceKind); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Recipients.Source != "" {
			if err := cst.SetAny(tableNode, "source", data.Recipients.Source); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "source")
		}
		if data.Recipients.Pigpen != "" {
			if err := cst.SetMultilineString(tableNode, "pigpen", data.Recipients.Pigpen); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(tableNode, "pigpen")
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "sealed")
		if data.Sealed.Document != "" || cst.HasValue(tableNode, "document") {
			if err := cst.SetMultilineString(tableNode, "document", data.Sealed.Document); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	return nil
}
