// Code generated by tommy 0.5.0 (c7e1574); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlPointerV2Document struct {
	data   TomlPointerV2
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlPointerV2(input []byte) (*TomlPointerV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlPointerV2Document{
		cstDoc: doc,
		model:  model,
	}

	if _vBasePath, _ok := model.Get("base-path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			d.data.BasePath = _x
			_vBasePath.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := model.Get("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := d.data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlPointerV2Document) Data() *TomlPointerV2 {
	return &d.data
}

func (d *TomlPointerV2Document) Encode() ([]byte, error) {
	if d.data.BasePath != "" || cst.HasValue(d.cstDoc.Root(), "base-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "base-path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.InstanceId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "instance-id", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "instance-id")
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlPointerV2Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlPointerV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlPointerV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlPointerV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlPointerV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlPointerV2Into(data *TomlPointerV2, sub *cst.Value) error {
	if _vBasePath, _ok := sub.Get("base-path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			data.BasePath = _x
			_vBasePath.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := sub.Get("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlPointerV2From(data *TomlPointerV2, doc *document.Document, container *cst.Node) error {
	if data.BasePath != "" || cst.HasValue(container, "base-path") {
		if err := cst.SetAny(container, "base-path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.InstanceId.MarshalText()
		if err != nil {
			return fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "instance-id", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "instance-id")
		}
	}
	return nil
}
