// Code generated by tommy 0.4.7 (92ffdff); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/purse-first/libs/dewey/pkgs/values"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlLocalHashBucketedV2Document struct {
	data   TomlLocalHashBucketedV2
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlLocalHashBucketedV2(input []byte) (*TomlLocalHashBucketedV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlLocalHashBucketedV2Document{
		cstDoc: doc,
		model:  model,
	}

	if _vHashBuckets, _ok := model.Get("hash_buckets"); _ok && _vHashBuckets.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractIntSlice(_vHashBuckets.Leaf); _xok {
			d.data.HashBuckets = values.IntSlice(_x)
			if d.data.HashBuckets == nil {
				d.data.HashBuckets = values.IntSlice{}
			}
			_vHashBuckets.MarkConsumed()
		}
	}
	if _vBasePath, _ok := model.Get("base_path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			d.data.BasePath = _x
			_vBasePath.MarkConsumed()
		}
	}
	if _vHashTypeId, _ok := model.Get("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := d.data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumed()
		}
	}
	if _vEncryption, _ok := model.Get("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEncryption.Leaf); _xok {
			if err := d.data.Encryption.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("encryption: %w", err)
			}
			_vEncryption.MarkConsumed()
		}
	}
	if _vCompressionType, _ok := model.Get("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			d.data.CompressionType = _x
			_vCompressionType.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlLocalHashBucketedV2Document) Data() *TomlLocalHashBucketedV2 {
	return &d.data
}

func (d *TomlLocalHashBucketedV2Document) Encode() ([]byte, error) {
	{
		if d.data.HashBuckets != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "hash_buckets", []int(d.data.HashBuckets)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.BasePath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "base_path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "base_path")
	}
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Encryption.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "encryption", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.CompressionType != "" || cst.HasValue(d.cstDoc.Root(), "compression-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "compression-type", d.data.CompressionType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlLocalHashBucketedV2Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlLocalHashBucketedV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlLocalHashBucketedV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlLocalHashBucketedV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlLocalHashBucketedV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlLocalHashBucketedV2Into(data *TomlLocalHashBucketedV2, sub *cst.Value) error {
	if _vHashBuckets, _ok := sub.Get("hash_buckets"); _ok && _vHashBuckets.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractIntSlice(_vHashBuckets.Leaf); _xok {
			data.HashBuckets = values.IntSlice(_x)
			if data.HashBuckets == nil {
				data.HashBuckets = values.IntSlice{}
			}
			_vHashBuckets.MarkConsumed()
		}
	}
	if _vBasePath, _ok := sub.Get("base_path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			data.BasePath = _x
			_vBasePath.MarkConsumed()
		}
	}
	if _vHashTypeId, _ok := sub.Get("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumed()
		}
	}
	if _vEncryption, _ok := sub.Get("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEncryption.Leaf); _xok {
			if err := data.Encryption.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("encryption: %w", err)
			}
			_vEncryption.MarkConsumed()
		}
	}
	if _vCompressionType, _ok := sub.Get("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			data.CompressionType = _x
			_vCompressionType.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlLocalHashBucketedV2From(data *TomlLocalHashBucketedV2, doc *document.Document, container *cst.Node) error {
	{
		if data.HashBuckets != nil {
			if err := cst.SetAny(container, "hash_buckets", []int(data.HashBuckets)); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.BasePath != "" {
		if err := cst.SetAny(container, "base_path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "base_path")
	}
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(container, "hash_type-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Encryption.MarshalText()
		if err != nil {
			return fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(container, "encryption", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.CompressionType != "" || cst.HasValue(container, "compression-type") {
		if err := cst.SetAny(container, "compression-type", data.CompressionType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
