// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlWebDAVV1Document struct {
	data   TomlWebDAVV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlWebDAVV1(input []byte) (*TomlWebDAVV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlWebDAVV1Parsed(doc)
}

// DecodeTomlWebDAVV1Strict is DecodeTomlWebDAVV1 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlWebDAVV1 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlWebDAVV1Strict(input []byte) (*TomlWebDAVV1Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlWebDAVV1Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlWebDAVV1Parsed(doc *document.Document) (*TomlWebDAVV1Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlWebDAVV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vUrl, _ok := model.Field("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			d.data.URL = _x
			_vUrl.MarkConsumedString()
		}
	}
	if _vUser, _ok := model.Field("user"); _ok && _vUser.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
			d.data.User = _x
			_vUser.MarkConsumedString()
		}
	}
	if _vPassword, _ok := model.Field("password"); _ok && _vPassword.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPassword.Leaf); _xok {
			d.data.Password = _x
			_vPassword.MarkConsumedString()
		}
	}
	if _vBearerToken, _ok := model.Field("bearer-token"); _ok && _vBearerToken.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBearerToken.Leaf); _xok {
			d.data.BearerToken = _x
			_vBearerToken.MarkConsumedString()
		}
	}
	if _vTlsClientCertPath, _ok := model.Field("tls-client-cert-path"); _ok && _vTlsClientCertPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientCertPath.Leaf); _xok {
			d.data.TLSClientCertPath = _x
			_vTlsClientCertPath.MarkConsumedString()
		}
	}
	if _vTlsClientKeyPath, _ok := model.Field("tls-client-key-path"); _ok && _vTlsClientKeyPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientKeyPath.Leaf); _xok {
			d.data.TLSClientKeyPath = _x
			_vTlsClientKeyPath.MarkConsumedString()
		}
	}
	if _vTlsCaPath, _ok := model.Field("tls-ca-path"); _ok && _vTlsCaPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsCaPath.Leaf); _xok {
			d.data.TLSCAPath = _x
			_vTlsCaPath.MarkConsumedString()
		}
	}
	if _vTlsServerName, _ok := model.Field("tls-server-name"); _ok && _vTlsServerName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsServerName.Leaf); _xok {
			d.data.TLSServerName = _x
			_vTlsServerName.MarkConsumedString()
		}
	}
	if _vTlsInsecureSkipVerify, _ok := model.Field("tls-insecure-skip-verify"); _ok && _vTlsInsecureSkipVerify.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vTlsInsecureSkipVerify.Leaf); _xok {
			d.data.TLSInsecureSkipVerify = _x
			_vTlsInsecureSkipVerify.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := model.Field("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := d.data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumedText()
		}
	}
	return d, nil
}

func (d *TomlWebDAVV1Document) Data() *TomlWebDAVV1 {
	return &d.data
}

func (d *TomlWebDAVV1Document) Encode() ([]byte, error) {
	if d.data.URL != "" || cst.HasValue(d.cstDoc.Root(), "url") {
		if err := cst.SetAny(d.cstDoc.Root(), "url", d.data.URL); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.User != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "user", d.data.User); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "user")
	}
	if d.data.Password != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "password", d.data.Password); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "password")
	}
	if d.data.BearerToken != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "bearer-token", d.data.BearerToken); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "bearer-token")
	}
	if d.data.TLSClientCertPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-client-cert-path", d.data.TLSClientCertPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-client-cert-path")
	}
	if d.data.TLSClientKeyPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-client-key-path", d.data.TLSClientKeyPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-client-key-path")
	}
	if d.data.TLSCAPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-ca-path", d.data.TLSCAPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-ca-path")
	}
	if d.data.TLSServerName != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-server-name", d.data.TLSServerName); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-server-name")
	}
	if d.data.TLSInsecureSkipVerify != false {
		if err := cst.SetAny(d.cstDoc.Root(), "tls-insecure-skip-verify", d.data.TLSInsecureSkipVerify); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "tls-insecure-skip-verify")
	}
	{
		v, err := d.data.InstanceId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "instance-id", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "instance-id")
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlWebDAVV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlWebDAVV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlWebDAVV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlWebDAVV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlWebDAVV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlWebDAVV1Into(data *TomlWebDAVV1, sub *cst.Value) error {
	if _vUrl, _ok := sub.Field("url"); _ok && _vUrl.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
			data.URL = _x
			_vUrl.MarkConsumedString()
		}
	}
	if _vUser, _ok := sub.Field("user"); _ok && _vUser.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
			data.User = _x
			_vUser.MarkConsumedString()
		}
	}
	if _vPassword, _ok := sub.Field("password"); _ok && _vPassword.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPassword.Leaf); _xok {
			data.Password = _x
			_vPassword.MarkConsumedString()
		}
	}
	if _vBearerToken, _ok := sub.Field("bearer-token"); _ok && _vBearerToken.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBearerToken.Leaf); _xok {
			data.BearerToken = _x
			_vBearerToken.MarkConsumedString()
		}
	}
	if _vTlsClientCertPath, _ok := sub.Field("tls-client-cert-path"); _ok && _vTlsClientCertPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientCertPath.Leaf); _xok {
			data.TLSClientCertPath = _x
			_vTlsClientCertPath.MarkConsumedString()
		}
	}
	if _vTlsClientKeyPath, _ok := sub.Field("tls-client-key-path"); _ok && _vTlsClientKeyPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsClientKeyPath.Leaf); _xok {
			data.TLSClientKeyPath = _x
			_vTlsClientKeyPath.MarkConsumedString()
		}
	}
	if _vTlsCaPath, _ok := sub.Field("tls-ca-path"); _ok && _vTlsCaPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsCaPath.Leaf); _xok {
			data.TLSCAPath = _x
			_vTlsCaPath.MarkConsumedString()
		}
	}
	if _vTlsServerName, _ok := sub.Field("tls-server-name"); _ok && _vTlsServerName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTlsServerName.Leaf); _xok {
			data.TLSServerName = _x
			_vTlsServerName.MarkConsumedString()
		}
	}
	if _vTlsInsecureSkipVerify, _ok := sub.Field("tls-insecure-skip-verify"); _ok && _vTlsInsecureSkipVerify.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vTlsInsecureSkipVerify.Leaf); _xok {
			data.TLSInsecureSkipVerify = _x
			_vTlsInsecureSkipVerify.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := sub.Field("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumedText()
		}
	}
	return nil
}

func EncodeTomlWebDAVV1From(data *TomlWebDAVV1, doc *document.Document, container *cst.Node) error {
	if data.URL != "" || cst.HasValue(container, "url") {
		if err := cst.SetAny(container, "url", data.URL); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.User != "" {
		if err := cst.SetAny(container, "user", data.User); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "user")
	}
	if data.Password != "" {
		if err := cst.SetAny(container, "password", data.Password); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "password")
	}
	if data.BearerToken != "" {
		if err := cst.SetAny(container, "bearer-token", data.BearerToken); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "bearer-token")
	}
	if data.TLSClientCertPath != "" {
		if err := cst.SetAny(container, "tls-client-cert-path", data.TLSClientCertPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-client-cert-path")
	}
	if data.TLSClientKeyPath != "" {
		if err := cst.SetAny(container, "tls-client-key-path", data.TLSClientKeyPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-client-key-path")
	}
	if data.TLSCAPath != "" {
		if err := cst.SetAny(container, "tls-ca-path", data.TLSCAPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-ca-path")
	}
	if data.TLSServerName != "" {
		if err := cst.SetAny(container, "tls-server-name", data.TLSServerName); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-server-name")
	}
	if data.TLSInsecureSkipVerify != false {
		if err := cst.SetAny(container, "tls-insecure-skip-verify", data.TLSInsecureSkipVerify); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "tls-insecure-skip-verify")
	}
	{
		v, err := data.InstanceId.MarshalText()
		if err != nil {
			return fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "instance-id", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "instance-id")
		}
	}
	return nil
}
