// Code generated by tommy 0.4.7 (dec0a3d); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/madder/go/internal/alfa/scoped_id"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlMultiV0Document struct {
	data   TomlMultiV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlMultiV0(input []byte) (*TomlMultiV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlMultiV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vMode, _ok := model.Get("mode"); _ok && _vMode.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vMode.Leaf); _xok {
			d.data.Mode = _x
			_vMode.MarkConsumed()
		}
	}
	if _vWriteStore, _ok := model.Get("write-store"); _ok && _vWriteStore.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vWriteStore.Leaf); _xok {
			if err := d.data.WriteStore.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("write-store: %w", err)
			}
			_vWriteStore.MarkConsumed()
		}
	}
	if _vReadStores, _ok := model.Get("read-stores"); _ok && _vReadStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vReadStores.Leaf); _xok {
			d.data.ReadStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := d.data.ReadStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return nil, fmt.Errorf("read-stores[%d]: %w", _si, err)
				}
			}
			_vReadStores.MarkConsumed()
		}
	}
	if _vMirrorStores, _ok := model.Get("mirror-stores"); _ok && _vMirrorStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vMirrorStores.Leaf); _xok {
			d.data.MirrorStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := d.data.MirrorStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return nil, fmt.Errorf("mirror-stores[%d]: %w", _si, err)
				}
			}
			_vMirrorStores.MarkConsumed()
		}
	}
	if _vReadFill, _ok := model.Get("read-fill"); _ok && _vReadFill.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vReadFill.Leaf); _xok {
			d.data.ReadFill = &_x
			_vReadFill.MarkConsumed()
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *TomlMultiV0Document) Data() *TomlMultiV0 {
	return &d.data
}

func (d *TomlMultiV0Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if d.data.Mode != "" || cst.HasValue(d.cstDoc.Root(), "mode") {
		if err := cst.SetAny(d.cstDoc.Root(), "mode", d.data.Mode); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.WriteStore.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("write-store: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "write-store", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "write-store")
		}
	}
	{
		if len(d.data.ReadStores) > 0 || cst.HasValue(d.cstDoc.Root(), "read-stores") {
			vals := make([]string, len(d.data.ReadStores))
			for i, item := range d.data.ReadStores {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("read-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "read-stores", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(d.data.MirrorStores) > 0 || cst.HasValue(d.cstDoc.Root(), "mirror-stores") {
			vals := make([]string, len(d.data.MirrorStores))
			for i, item := range d.data.MirrorStores {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("mirror-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "mirror-stores", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.ReadFill != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "read-fill", *d.data.ReadFill); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlMultiV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlMultiV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlMultiV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlMultiV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlMultiV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlMultiV0Into(data *TomlMultiV0, sub *cst.Value) error {
	if _vMode, _ok := sub.Get("mode"); _ok && _vMode.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vMode.Leaf); _xok {
			data.Mode = _x
			_vMode.MarkConsumed()
		}
	}
	if _vWriteStore, _ok := sub.Get("write-store"); _ok && _vWriteStore.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vWriteStore.Leaf); _xok {
			if err := data.WriteStore.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("write-store: %w", err)
			}
			_vWriteStore.MarkConsumed()
		}
	}
	if _vReadStores, _ok := sub.Get("read-stores"); _ok && _vReadStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vReadStores.Leaf); _xok {
			data.ReadStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := data.ReadStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return fmt.Errorf("read-stores[%d]: %w", _si, err)
				}
			}
			_vReadStores.MarkConsumed()
		}
	}
	if _vMirrorStores, _ok := sub.Get("mirror-stores"); _ok && _vMirrorStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vMirrorStores.Leaf); _xok {
			data.MirrorStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := data.MirrorStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return fmt.Errorf("mirror-stores[%d]: %w", _si, err)
				}
			}
			_vMirrorStores.MarkConsumed()
		}
	}
	if _vReadFill, _ok := sub.Get("read-fill"); _ok && _vReadFill.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vReadFill.Leaf); _xok {
			data.ReadFill = &_x
			_vReadFill.MarkConsumed()
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeTomlMultiV0From(data *TomlMultiV0, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	if data.Mode != "" || cst.HasValue(container, "mode") {
		if err := cst.SetAny(container, "mode", data.Mode); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.WriteStore.MarshalText()
		if err != nil {
			return fmt.Errorf("write-store: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "write-store", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "write-store")
		}
	}
	{
		if len(data.ReadStores) > 0 || cst.HasValue(container, "read-stores") {
			vals := make([]string, len(data.ReadStores))
			for i, item := range data.ReadStores {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("read-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "read-stores", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(data.MirrorStores) > 0 || cst.HasValue(container, "mirror-stores") {
			vals := make([]string, len(data.MirrorStores))
			for i, item := range data.MirrorStores {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("mirror-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "mirror-stores", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.ReadFill != nil {
		if err := cst.SetAny(container, "read-fill", *data.ReadFill); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
