// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/piggy/go/pkgs/markl"
	"code.linenisgreat.com/purse-first/libs/dewey/pkgs/values"
	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlV4Document struct {
	data   TomlV4
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlV4(input []byte) (*TomlV4Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlV4Parsed(doc)
}

// DecodeTomlV4Strict is DecodeTomlV4 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlV4 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlV4Strict(input []byte) (*TomlV4Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlV4Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlV4Parsed(doc *document.Document) (*TomlV4Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlV4Document{
		cstDoc: doc,
		model:  model,
	}

	if _vHashBuckets, _ok := model.Field("hash_buckets"); _ok && _vHashBuckets.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractIntSlice(_vHashBuckets.Leaf); _xok {
			d.data.HashBuckets = values.IntSlice(_x)
			if d.data.HashBuckets == nil {
				d.data.HashBuckets = values.IntSlice{}
			}
			_vHashBuckets.MarkConsumed()
		}
	}
	if _vBasePath, _ok := model.Field("base_path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			d.data.BasePath = _x
			_vBasePath.MarkConsumedString()
		}
	}
	if _vHashTypeId, _ok := model.Field("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := d.data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumedText()
		}
	}
	if _vEncryption, _ok := model.Field("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vEncryption.Leaf); _xok {
			d.data.Encryption = make([]markl.Id, len(_x))
			for _si, _s := range _x {
				if err := d.data.Encryption[_si].UnmarshalText([]byte(_s)); err != nil {
					return nil, fmt.Errorf("encryption[%d]: %w", _si, err)
				}
			}
			_vEncryption.MarkConsumed()
		}
	}
	if _vCompressionType, _ok := model.Field("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			d.data.CompressionType = _x
			_vCompressionType.MarkConsumedString()
		}
	}
	if _vVerifyOnCollision, _ok := model.Field("verify-on-collision"); _ok && _vVerifyOnCollision.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vVerifyOnCollision.Leaf); _xok {
			d.data.VerifyOnCollision = _x
			_vVerifyOnCollision.MarkConsumed()
		}
	}
	if _vSingleHash, _ok := model.Field("single_hash"); _ok && _vSingleHash.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vSingleHash.Leaf); _xok {
			d.data.SingleHash = _x
			_vSingleHash.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := model.Field("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := d.data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumedText()
		}
	}
	return d, nil
}

func (d *TomlV4Document) Data() *TomlV4 {
	return &d.data
}

func (d *TomlV4Document) Encode() ([]byte, error) {
	{
		if d.data.HashBuckets != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "hash_buckets", []int(d.data.HashBuckets)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.BasePath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "base_path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "base_path")
	}
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if d.data.Encryption != nil {
			vals := make([]string, len(d.data.Encryption))
			for i, item := range d.data.Encryption {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("encryption[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "encryption", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.CompressionType != "" || cst.HasValue(d.cstDoc.Root(), "compression-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "compression-type", d.data.CompressionType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.VerifyOnCollision != false || cst.HasValue(d.cstDoc.Root(), "verify-on-collision") {
		if err := cst.SetAny(d.cstDoc.Root(), "verify-on-collision", d.data.VerifyOnCollision); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.SingleHash != false {
		if err := cst.SetAny(d.cstDoc.Root(), "single_hash", d.data.SingleHash); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "single_hash")
	}
	{
		v, err := d.data.InstanceId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "instance-id", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "instance-id")
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlV4Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlV4Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV4Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV4Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV4Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV4Into(data *TomlV4, sub *cst.Value) error {
	if _vHashBuckets, _ok := sub.Field("hash_buckets"); _ok && _vHashBuckets.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractIntSlice(_vHashBuckets.Leaf); _xok {
			data.HashBuckets = values.IntSlice(_x)
			if data.HashBuckets == nil {
				data.HashBuckets = values.IntSlice{}
			}
			_vHashBuckets.MarkConsumed()
		}
	}
	if _vBasePath, _ok := sub.Field("base_path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			data.BasePath = _x
			_vBasePath.MarkConsumedString()
		}
	}
	if _vHashTypeId, _ok := sub.Field("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumedText()
		}
	}
	if _vEncryption, _ok := sub.Field("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vEncryption.Leaf); _xok {
			data.Encryption = make([]markl.Id, len(_x))
			for _si, _s := range _x {
				if err := data.Encryption[_si].UnmarshalText([]byte(_s)); err != nil {
					return fmt.Errorf("encryption[%d]: %w", _si, err)
				}
			}
			_vEncryption.MarkConsumed()
		}
	}
	if _vCompressionType, _ok := sub.Field("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			data.CompressionType = _x
			_vCompressionType.MarkConsumedString()
		}
	}
	if _vVerifyOnCollision, _ok := sub.Field("verify-on-collision"); _ok && _vVerifyOnCollision.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vVerifyOnCollision.Leaf); _xok {
			data.VerifyOnCollision = _x
			_vVerifyOnCollision.MarkConsumed()
		}
	}
	if _vSingleHash, _ok := sub.Field("single_hash"); _ok && _vSingleHash.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vSingleHash.Leaf); _xok {
			data.SingleHash = _x
			_vSingleHash.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := sub.Field("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumedText()
		}
	}
	return nil
}

func EncodeTomlV4From(data *TomlV4, doc *document.Document, container *cst.Node) error {
	{
		if data.HashBuckets != nil {
			if err := cst.SetAny(container, "hash_buckets", []int(data.HashBuckets)); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.BasePath != "" {
		if err := cst.SetAny(container, "base_path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "base_path")
	}
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(container, "hash_type-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if data.Encryption != nil {
			vals := make([]string, len(data.Encryption))
			for i, item := range data.Encryption {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("encryption[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "encryption", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.CompressionType != "" || cst.HasValue(container, "compression-type") {
		if err := cst.SetAny(container, "compression-type", data.CompressionType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.VerifyOnCollision != false || cst.HasValue(container, "verify-on-collision") {
		if err := cst.SetAny(container, "verify-on-collision", data.VerifyOnCollision); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.SingleHash != false {
		if err := cst.SetAny(container, "single_hash", data.SingleHash); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "single_hash")
	}
	{
		v, err := data.InstanceId.MarshalText()
		if err != nil {
			return fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "instance-id", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "instance-id")
		}
	}
	return nil
}
