// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/madder/go/internal/alfa/blob_store_id"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlMultiV0Document struct {
	data     TomlMultiV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlMultiV0(input []byte) (*TomlMultiV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlMultiV0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "mode":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Mode = v
				d.consumed["mode"] = true
			}
		case "write-store":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.WriteStore.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("write-store: %w", err)
				}
				d.consumed["write-store"] = true
			}
		case "read-stores":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.ReadStores = make([]blob_store_id.Id, len(v))
				for _si, _s := range v {
					if err := d.data.ReadStores[_si].UnmarshalText([]byte(_s)); err != nil {
						return nil, fmt.Errorf("read-stores[%d]: %w", _si, err)
					}
				}
				d.consumed["read-stores"] = true
			}
		case "mirror-stores":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				d.data.MirrorStores = make([]blob_store_id.Id, len(v))
				for _si, _s := range v {
					if err := d.data.MirrorStores[_si].UnmarshalText([]byte(_s)); err != nil {
						return nil, fmt.Errorf("mirror-stores[%d]: %w", _si, err)
					}
				}
				d.consumed["mirror-stores"] = true
			}
		case "read-fill":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.ReadFill = &v
				d.consumed["read-fill"] = true
			}
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *TomlMultiV0Document) Data() *TomlMultiV0 {
	return &d.data
}

func (d *TomlMultiV0Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if d.data.Mode != "" || cst.HasValue(d.cstDoc.Root(), "mode") {
		if err := cst.SetAny(d.cstDoc.Root(), "mode", d.data.Mode); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.WriteStore.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("write-store: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "write-store", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "write-store")
		}
	}
	{
		if len(d.data.ReadStores) > 0 || cst.HasValue(d.cstDoc.Root(), "read-stores") {
			vals := make([]string, len(d.data.ReadStores))
			for i, item := range d.data.ReadStores {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("read-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "read-stores", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(d.data.MirrorStores) > 0 || cst.HasValue(d.cstDoc.Root(), "mirror-stores") {
			vals := make([]string, len(d.data.MirrorStores))
			for i, item := range d.data.MirrorStores {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("mirror-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "mirror-stores", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.ReadFill != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "read-fill", *d.data.ReadFill); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlMultiV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlMultiV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlMultiV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlMultiV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlMultiV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlMultiV0Into(data *TomlMultiV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "mode":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Mode = v
				consumed[keyPrefix+"mode"] = true
			}
		case "write-store":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.WriteStore.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("write-store: %w", err)
				}
				consumed[keyPrefix+"write-store"] = true
			}
		case "read-stores":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.ReadStores = make([]blob_store_id.Id, len(v))
				for _si, _s := range v {
					if err := data.ReadStores[_si].UnmarshalText([]byte(_s)); err != nil {
						return fmt.Errorf("read-stores[%d]: %w", _si, err)
					}
				}
				consumed[keyPrefix+"read-stores"] = true
			}
		case "mirror-stores":
			if v, ok := cst.ExtractStringSlice(_kv); ok {
				data.MirrorStores = make([]blob_store_id.Id, len(v))
				for _si, _s := range v {
					if err := data.MirrorStores[_si].UnmarshalText([]byte(_s)); err != nil {
						return fmt.Errorf("mirror-stores[%d]: %w", _si, err)
					}
				}
				consumed[keyPrefix+"mirror-stores"] = true
			}
		case "read-fill":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.ReadFill = &v
				consumed[keyPrefix+"read-fill"] = true
			}
		}
	}
	return nil
}

func EncodeTomlMultiV0From(data *TomlMultiV0, doc *document.Document, container *cst.Node) error {
	if data.Mode != "" || cst.HasValue(container, "mode") {
		if err := cst.SetAny(container, "mode", data.Mode); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.WriteStore.MarshalText()
		if err != nil {
			return fmt.Errorf("write-store: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "write-store", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "write-store")
		}
	}
	{
		if len(data.ReadStores) > 0 || cst.HasValue(container, "read-stores") {
			vals := make([]string, len(data.ReadStores))
			for i, item := range data.ReadStores {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("read-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "read-stores", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(data.MirrorStores) > 0 || cst.HasValue(container, "mirror-stores") {
			vals := make([]string, len(data.MirrorStores))
			for i, item := range data.MirrorStores {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("mirror-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "mirror-stores", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.ReadFill != nil {
		if err := cst.SetAny(container, "read-fill", *data.ReadFill); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
