// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/purse-first/libs/dewey/charlie/values"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlLocalHashBucketedV2Document struct {
	data     TomlLocalHashBucketedV2
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlLocalHashBucketedV2(input []byte) (*TomlLocalHashBucketedV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlLocalHashBucketedV2Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "hash_buckets":
			if v, ok := cst.ExtractIntSlice(_kv); ok {
				d.data.HashBuckets = values.IntSlice(v)
				d.consumed["hash_buckets"] = true
			}
		case "base_path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.BasePath = v
				d.consumed["base_path"] = true
			}
		case "hash_type-id":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("hash_type-id: %w", err)
				}
				d.consumed["hash_type-id"] = true
			}
		case "encryption":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.Encryption.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("encryption: %w", err)
				}
				d.consumed["encryption"] = true
			}
		case "compression-type":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.CompressionType.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("compression-type: %w", err)
				}
				d.consumed["compression-type"] = true
			}
		}
	}
	return d, nil
}
func (d *TomlLocalHashBucketedV2Document) Data() *TomlLocalHashBucketedV2 {
	return &d.data
}
func (d *TomlLocalHashBucketedV2Document) Encode() ([]byte, error) {
	{
		if err := cst.SetAny(d.cstDoc.Root(), "hash_buckets", []int(d.data.HashBuckets)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.BasePath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "base_path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "base_path")
	}
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Encryption.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "encryption", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.CompressionType.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("compression-type: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "compression-type", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *TomlLocalHashBucketedV2Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *TomlLocalHashBucketedV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *TomlLocalHashBucketedV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *TomlLocalHashBucketedV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *TomlLocalHashBucketedV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeTomlLocalHashBucketedV2Into(data *TomlLocalHashBucketedV2, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "hash_buckets":
			if v, ok := cst.ExtractIntSlice(_kv); ok {
				data.HashBuckets = values.IntSlice(v)
				consumed[keyPrefix+"hash_buckets"] = true
			}
		case "base_path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.BasePath = v
				consumed[keyPrefix+"base_path"] = true
			}
		case "hash_type-id":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("hash_type-id: %w", err)
				}
				consumed[keyPrefix+"hash_type-id"] = true
			}
		case "encryption":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.Encryption.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("encryption: %w", err)
				}
				consumed[keyPrefix+"encryption"] = true
			}
		case "compression-type":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.CompressionType.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("compression-type: %w", err)
				}
				consumed[keyPrefix+"compression-type"] = true
			}
		}
	}
	return nil
}
func EncodeTomlLocalHashBucketedV2From(data *TomlLocalHashBucketedV2, doc *document.Document, container *cst.Node) error {
	{
		if err := cst.SetAny(container, "hash_buckets", []int(data.HashBuckets)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.BasePath != "" {
		if err := cst.SetAny(container, "base_path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "base_path")
	}
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(container, "hash_type-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Encryption.MarshalText()
		if err != nil {
			return fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(container, "encryption", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.CompressionType.MarshalText()
		if err != nil {
			return fmt.Errorf("compression-type: %w", err)
		}
		if err := cst.SetAny(container, "compression-type", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
