// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlSFTPViaSSHConfigV0Document struct {
	data   TomlSFTPViaSSHConfigV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlSFTPViaSSHConfigV0(input []byte) (*TomlSFTPViaSSHConfigV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlSFTPViaSSHConfigV0Parsed(doc)
}

// DecodeTomlSFTPViaSSHConfigV0Strict is DecodeTomlSFTPViaSSHConfigV0 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlSFTPViaSSHConfigV0 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlSFTPViaSSHConfigV0Strict(input []byte) (*TomlSFTPViaSSHConfigV0Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlSFTPViaSSHConfigV0Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlSFTPViaSSHConfigV0Parsed(doc *document.Document) (*TomlSFTPViaSSHConfigV0Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlSFTPViaSSHConfigV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vUri, _ok := model.Field("uri"); _ok && _vUri.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUri.Leaf); _xok {
			if err := d.data.Uri.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("uri: %w", err)
			}
			_vUri.MarkConsumedText()
		}
	}
	if _vKnownHostsFile, _ok := model.Field("known-hosts-file"); _ok && _vKnownHostsFile.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKnownHostsFile.Leaf); _xok {
			d.data.KnownHostsFile = _x
			_vKnownHostsFile.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *TomlSFTPViaSSHConfigV0Document) Data() *TomlSFTPViaSSHConfigV0 {
	return &d.data
}

func (d *TomlSFTPViaSSHConfigV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Uri.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("uri: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "uri", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.KnownHostsFile != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "known-hosts-file", d.data.KnownHostsFile); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "known-hosts-file")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlSFTPViaSSHConfigV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlSFTPViaSSHConfigV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlSFTPViaSSHConfigV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlSFTPViaSSHConfigV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlSFTPViaSSHConfigV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlSFTPViaSSHConfigV0Into(data *TomlSFTPViaSSHConfigV0, sub *cst.Value) error {
	if _vUri, _ok := sub.Field("uri"); _ok && _vUri.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUri.Leaf); _xok {
			if err := data.Uri.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("uri: %w", err)
			}
			_vUri.MarkConsumedText()
		}
	}
	if _vKnownHostsFile, _ok := sub.Field("known-hosts-file"); _ok && _vKnownHostsFile.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKnownHostsFile.Leaf); _xok {
			data.KnownHostsFile = _x
			_vKnownHostsFile.MarkConsumedString()
		}
	}
	return nil
}

func EncodeTomlSFTPViaSSHConfigV0From(data *TomlSFTPViaSSHConfigV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.Uri.MarshalText()
		if err != nil {
			return fmt.Errorf("uri: %w", err)
		}
		if err := cst.SetAny(container, "uri", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.KnownHostsFile != "" {
		if err := cst.SetAny(container, "known-hosts-file", data.KnownHostsFile); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "known-hosts-file")
	}
	return nil
}
