// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlPointerV1Document struct {
	data   TomlPointerV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlPointerV1(input []byte) (*TomlPointerV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlPointerV1Parsed(doc)
}

// DecodeTomlPointerV1Strict is DecodeTomlPointerV1 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlPointerV1 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlPointerV1Strict(input []byte) (*TomlPointerV1Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlPointerV1Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlPointerV1Parsed(doc *document.Document) (*TomlPointerV1Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlPointerV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vBasePath, _ok := model.Field("base-path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			d.data.BasePath = _x
			_vBasePath.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *TomlPointerV1Document) Data() *TomlPointerV1 {
	return &d.data
}

func (d *TomlPointerV1Document) Encode() ([]byte, error) {
	if d.data.BasePath != "" || cst.HasValue(d.cstDoc.Root(), "base-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "base-path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlPointerV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlPointerV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlPointerV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlPointerV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlPointerV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlPointerV1Into(data *TomlPointerV1, sub *cst.Value) error {
	if _vBasePath, _ok := sub.Field("base-path"); _ok && _vBasePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vBasePath.Leaf); _xok {
			data.BasePath = _x
			_vBasePath.MarkConsumedString()
		}
	}
	return nil
}

func EncodeTomlPointerV1From(data *TomlPointerV1, doc *document.Document, container *cst.Node) error {
	if data.BasePath != "" || cst.HasValue(container, "base-path") {
		if err := cst.SetAny(container, "base-path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
