// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlSFTPV0Document struct {
	data     TomlSFTPV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlSFTPV0(input []byte) (*TomlSFTPV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlSFTPV0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "host":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Host = v
				d.consumed["host"] = true
			}
		case "port":
			if v, ok := cst.ExtractInt(_kv); ok {
				d.data.Port = v
				d.consumed["port"] = true
			}
		case "user":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.User = v
				d.consumed["user"] = true
			}
		case "password":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Password = v
				d.consumed["password"] = true
			}
		case "private-key-path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.PrivateKeyPath = v
				d.consumed["private-key-path"] = true
			}
		case "remote-path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.RemotePath = v
				d.consumed["remote-path"] = true
			}
		case "known-hosts-file":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.KnownHostsFile = v
				d.consumed["known-hosts-file"] = true
			}
		}
	}
	return d, nil
}
func (d *TomlSFTPV0Document) Data() *TomlSFTPV0 {
	return &d.data
}
func (d *TomlSFTPV0Document) Encode() ([]byte, error) {
	if d.data.Host != "" || cst.HasValue(d.cstDoc.Root(), "host") {
		if err := cst.SetAny(d.cstDoc.Root(), "host", d.data.Host); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Port != 0 {
		if err := cst.SetAny(d.cstDoc.Root(), "port", d.data.Port); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "port")
	}
	if d.data.User != "" || cst.HasValue(d.cstDoc.Root(), "user") {
		if err := cst.SetAny(d.cstDoc.Root(), "user", d.data.User); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Password != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "password", d.data.Password); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "password")
	}
	if d.data.PrivateKeyPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "private-key-path", d.data.PrivateKeyPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "private-key-path")
	}
	if d.data.RemotePath != "" || cst.HasValue(d.cstDoc.Root(), "remote-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "remote-path", d.data.RemotePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.KnownHostsFile != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "known-hosts-file", d.data.KnownHostsFile); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "known-hosts-file")
	}
	return d.cstDoc.Bytes(), nil
}
func (d *TomlSFTPV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *TomlSFTPV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *TomlSFTPV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *TomlSFTPV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *TomlSFTPV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeTomlSFTPV0Into(data *TomlSFTPV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "host":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Host = v
				consumed[keyPrefix+"host"] = true
			}
		case "port":
			if v, ok := cst.ExtractInt(_kv); ok {
				data.Port = v
				consumed[keyPrefix+"port"] = true
			}
		case "user":
			if v, ok := cst.ExtractString(_kv); ok {
				data.User = v
				consumed[keyPrefix+"user"] = true
			}
		case "password":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Password = v
				consumed[keyPrefix+"password"] = true
			}
		case "private-key-path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.PrivateKeyPath = v
				consumed[keyPrefix+"private-key-path"] = true
			}
		case "remote-path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.RemotePath = v
				consumed[keyPrefix+"remote-path"] = true
			}
		case "known-hosts-file":
			if v, ok := cst.ExtractString(_kv); ok {
				data.KnownHostsFile = v
				consumed[keyPrefix+"known-hosts-file"] = true
			}
		}
	}
	return nil
}
func EncodeTomlSFTPV0From(data *TomlSFTPV0, doc *document.Document, container *cst.Node) error {
	if data.Host != "" || cst.HasValue(container, "host") {
		if err := cst.SetAny(container, "host", data.Host); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Port != 0 {
		if err := cst.SetAny(container, "port", data.Port); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "port")
	}
	if data.User != "" || cst.HasValue(container, "user") {
		if err := cst.SetAny(container, "user", data.User); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Password != "" {
		if err := cst.SetAny(container, "password", data.Password); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "password")
	}
	if data.PrivateKeyPath != "" {
		if err := cst.SetAny(container, "private-key-path", data.PrivateKeyPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "private-key-path")
	}
	if data.RemotePath != "" || cst.HasValue(container, "remote-path") {
		if err := cst.SetAny(container, "remote-path", data.RemotePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.KnownHostsFile != "" {
		if err := cst.SetAny(container, "known-hosts-file", data.KnownHostsFile); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "known-hosts-file")
	}
	return nil
}
