// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlInventoryArchiveV0Document struct {
	data   TomlInventoryArchiveV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlInventoryArchiveV0(input []byte) (*TomlInventoryArchiveV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlInventoryArchiveV0Parsed(doc)
}

// DecodeTomlInventoryArchiveV0Strict is DecodeTomlInventoryArchiveV0 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlInventoryArchiveV0 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlInventoryArchiveV0Strict(input []byte) (*TomlInventoryArchiveV0Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlInventoryArchiveV0Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlInventoryArchiveV0Parsed(doc *document.Document) (*TomlInventoryArchiveV0Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlInventoryArchiveV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vHashTypeId, _ok := model.Field("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := d.data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumedText()
		}
	}
	if _vCompressionType, _ok := model.Field("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			d.data.CompressionType = _x
			_vCompressionType.MarkConsumedString()
		}
	}
	if _vLooseBlobStoreId, _ok := model.Field("loose-blob-store-id"); _ok && _vLooseBlobStoreId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vLooseBlobStoreId.Leaf); _xok {
			if err := d.data.LooseBlobStoreId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("loose-blob-store-id: %w", err)
			}
			_vLooseBlobStoreId.MarkConsumedText()
		}
	}
	if _vEncryption, _ok := model.Field("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEncryption.Leaf); _xok {
			if err := d.data.Encryption.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("encryption: %w", err)
			}
			_vEncryption.MarkConsumedText()
		}
	}
	return d, nil
}

func (d *TomlInventoryArchiveV0Document) Data() *TomlInventoryArchiveV0 {
	return &d.data
}

func (d *TomlInventoryArchiveV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.CompressionType != "" || cst.HasValue(d.cstDoc.Root(), "compression-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "compression-type", d.data.CompressionType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.LooseBlobStoreId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("loose-blob-store-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "loose-blob-store-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Encryption.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "encryption", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlInventoryArchiveV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlInventoryArchiveV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlInventoryArchiveV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlInventoryArchiveV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlInventoryArchiveV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlInventoryArchiveV0Into(data *TomlInventoryArchiveV0, sub *cst.Value) error {
	if _vHashTypeId, _ok := sub.Field("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumedText()
		}
	}
	if _vCompressionType, _ok := sub.Field("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			data.CompressionType = _x
			_vCompressionType.MarkConsumedString()
		}
	}
	if _vLooseBlobStoreId, _ok := sub.Field("loose-blob-store-id"); _ok && _vLooseBlobStoreId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vLooseBlobStoreId.Leaf); _xok {
			if err := data.LooseBlobStoreId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("loose-blob-store-id: %w", err)
			}
			_vLooseBlobStoreId.MarkConsumedText()
		}
	}
	if _vEncryption, _ok := sub.Field("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEncryption.Leaf); _xok {
			if err := data.Encryption.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("encryption: %w", err)
			}
			_vEncryption.MarkConsumedText()
		}
	}
	return nil
}

func EncodeTomlInventoryArchiveV0From(data *TomlInventoryArchiveV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(container, "hash_type-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.CompressionType != "" || cst.HasValue(container, "compression-type") {
		if err := cst.SetAny(container, "compression-type", data.CompressionType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.LooseBlobStoreId.MarshalText()
		if err != nil {
			return fmt.Errorf("loose-blob-store-id: %w", err)
		}
		if err := cst.SetAny(container, "loose-blob-store-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Encryption.MarshalText()
		if err != nil {
			return fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(container, "encryption", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
