// Code generated by tommy 0.5.0 (1b6b24b); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type StoreKeyRecipientsDocument struct {
	data   StoreKeyRecipients
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeStoreKeyRecipients(input []byte) (*StoreKeyRecipientsDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &StoreKeyRecipientsDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vSource, _ok := model.Get("source"); _ok && _vSource.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
			d.data.Source = _x
			_vSource.MarkConsumed()
		}
	}
	if _vDigest, _ok := model.Get("digest"); _ok && _vDigest.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDigest.Leaf); _xok {
			if err := d.data.Digest.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("digest: %w", err)
			}
			_vDigest.MarkConsumed()
		}
	}
	return d, nil
}

func (d *StoreKeyRecipientsDocument) Data() *StoreKeyRecipients {
	return &d.data
}

func (d *StoreKeyRecipientsDocument) Encode() ([]byte, error) {
	if d.data.Source != "" || cst.HasValue(d.cstDoc.Root(), "source") {
		if err := cst.SetAny(d.cstDoc.Root(), "source", d.data.Source); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Digest.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("digest: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "digest", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *StoreKeyRecipientsDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *StoreKeyRecipientsDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *StoreKeyRecipientsDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *StoreKeyRecipientsDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *StoreKeyRecipientsDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeStoreKeyRecipientsInto(data *StoreKeyRecipients, sub *cst.Value) error {
	if _vSource, _ok := sub.Get("source"); _ok && _vSource.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
			data.Source = _x
			_vSource.MarkConsumed()
		}
	}
	if _vDigest, _ok := sub.Get("digest"); _ok && _vDigest.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDigest.Leaf); _xok {
			if err := data.Digest.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("digest: %w", err)
			}
			_vDigest.MarkConsumed()
		}
	}
	return nil
}

func EncodeStoreKeyRecipientsFrom(data *StoreKeyRecipients, doc *document.Document, container *cst.Node) error {
	if data.Source != "" || cst.HasValue(container, "source") {
		if err := cst.SetAny(container, "source", data.Source); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Digest.MarshalText()
		if err != nil {
			return fmt.Errorf("digest: %w", err)
		}
		if err := cst.SetAny(container, "digest", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type StoreKeySealedDocument struct {
	data   StoreKeySealed
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeStoreKeySealed(input []byte) (*StoreKeySealedDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &StoreKeySealedDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vDocument, _ok := model.Get("document"); _ok && _vDocument.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
			d.data.Document = _x
			_vDocument.MarkConsumed()
		}
	}
	return d, nil
}

func (d *StoreKeySealedDocument) Data() *StoreKeySealed {
	return &d.data
}

func (d *StoreKeySealedDocument) Encode() ([]byte, error) {
	if d.data.Document != "" || cst.HasValue(d.cstDoc.Root(), "document") {
		if err := cst.SetAny(d.cstDoc.Root(), "document", d.data.Document); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *StoreKeySealedDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *StoreKeySealedDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *StoreKeySealedDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *StoreKeySealedDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *StoreKeySealedDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeStoreKeySealedInto(data *StoreKeySealed, sub *cst.Value) error {
	if _vDocument, _ok := sub.Get("document"); _ok && _vDocument.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
			data.Document = _x
			_vDocument.MarkConsumed()
		}
	}
	return nil
}

func EncodeStoreKeySealedFrom(data *StoreKeySealed, doc *document.Document, container *cst.Node) error {
	if data.Document != "" || cst.HasValue(container, "document") {
		if err := cst.SetAny(container, "document", data.Document); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type TomlStoreKeyV1Document struct {
	data   TomlStoreKeyV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlStoreKeyV1(input []byte) (*TomlStoreKeyV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlStoreKeyV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vRecipients, _ok := model.Get("recipients"); _ok && _vRecipients.Kind == cst.VTable {
		_vRecipients.MarkSeen()
		if _vRecipientsSource, _ok := _vRecipients.Get("source"); _ok && _vRecipientsSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsSource.Leaf); _xok {
				d.data.Recipients.Source = _x
				_vRecipientsSource.MarkConsumed()
			}
		}
		if _vRecipientsDigest, _ok := _vRecipients.Get("digest"); _ok && _vRecipientsDigest.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsDigest.Leaf); _xok {
				if err := d.data.Recipients.Digest.UnmarshalText([]byte(_x)); err != nil {
					return nil, fmt.Errorf("digest: %w", err)
				}
				_vRecipientsDigest.MarkConsumed()
			}
		}
	} else {
		if _vSource, _ok := model.Get("source"); _ok && _vSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
				d.data.Recipients.Source = _x
				_vSource.MarkConsumed()
			}
		}
		if _vDigest, _ok := model.Get("digest"); _ok && _vDigest.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDigest.Leaf); _xok {
				if err := d.data.Recipients.Digest.UnmarshalText([]byte(_x)); err != nil {
					return nil, fmt.Errorf("digest: %w", err)
				}
				_vDigest.MarkConsumed()
			}
		}
	}
	if _vSealed, _ok := model.Get("sealed"); _ok && _vSealed.Kind == cst.VTable {
		_vSealed.MarkSeen()
		if _vSealedDocument, _ok := _vSealed.Get("document"); _ok && _vSealedDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSealedDocument.Leaf); _xok {
				d.data.Sealed.Document = _x
				_vSealedDocument.MarkConsumed()
			}
		}
	} else {
		if _vDocument, _ok := model.Get("document"); _ok && _vDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
				d.data.Sealed.Document = _x
				_vDocument.MarkConsumed()
			}
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *TomlStoreKeyV1Document) Data() *TomlStoreKeyV1 {
	return &d.data
}

func (d *TomlStoreKeyV1Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "recipients")
		if d.data.Recipients.Source != "" || cst.HasValue(tableNode, "source") {
			if err := cst.SetAny(tableNode, "source", d.data.Recipients.Source); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		{
			v, err := d.data.Recipients.Digest.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("digest: %w", err)
			}
			if err := cst.SetAny(tableNode, "digest", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "sealed")
		if d.data.Sealed.Document != "" || cst.HasValue(tableNode, "document") {
			if err := cst.SetAny(tableNode, "document", d.data.Sealed.Document); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlStoreKeyV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlStoreKeyV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlStoreKeyV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlStoreKeyV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlStoreKeyV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlStoreKeyV1Into(data *TomlStoreKeyV1, sub *cst.Value) error {
	if _vRecipients, _ok := sub.Get("recipients"); _ok && _vRecipients.Kind == cst.VTable {
		_vRecipients.MarkSeen()
		if _vRecipientsSource, _ok := _vRecipients.Get("source"); _ok && _vRecipientsSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsSource.Leaf); _xok {
				data.Recipients.Source = _x
				_vRecipientsSource.MarkConsumed()
			}
		}
		if _vRecipientsDigest, _ok := _vRecipients.Get("digest"); _ok && _vRecipientsDigest.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vRecipientsDigest.Leaf); _xok {
				if err := data.Recipients.Digest.UnmarshalText([]byte(_x)); err != nil {
					return fmt.Errorf("digest: %w", err)
				}
				_vRecipientsDigest.MarkConsumed()
			}
		}
	} else {
		if _vSource, _ok := sub.Get("source"); _ok && _vSource.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSource.Leaf); _xok {
				data.Recipients.Source = _x
				_vSource.MarkConsumed()
			}
		}
		if _vDigest, _ok := sub.Get("digest"); _ok && _vDigest.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDigest.Leaf); _xok {
				if err := data.Recipients.Digest.UnmarshalText([]byte(_x)); err != nil {
					return fmt.Errorf("digest: %w", err)
				}
				_vDigest.MarkConsumed()
			}
		}
	}
	if _vSealed, _ok := sub.Get("sealed"); _ok && _vSealed.Kind == cst.VTable {
		_vSealed.MarkSeen()
		if _vSealedDocument, _ok := _vSealed.Get("document"); _ok && _vSealedDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vSealedDocument.Leaf); _xok {
				data.Sealed.Document = _x
				_vSealedDocument.MarkConsumed()
			}
		}
	} else {
		if _vDocument, _ok := sub.Get("document"); _ok && _vDocument.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDocument.Leaf); _xok {
				data.Sealed.Document = _x
				_vDocument.MarkConsumed()
			}
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeTomlStoreKeyV1From(data *TomlStoreKeyV1, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "recipients")
		if data.Recipients.Source != "" || cst.HasValue(tableNode, "source") {
			if err := cst.SetAny(tableNode, "source", data.Recipients.Source); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		{
			v, err := data.Recipients.Digest.MarshalText()
			if err != nil {
				return fmt.Errorf("digest: %w", err)
			}
			if err := cst.SetAny(tableNode, "digest", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "sealed")
		if data.Sealed.Document != "" || cst.HasValue(tableNode, "document") {
			if err := cst.SetAny(tableNode, "document", data.Sealed.Document); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	return nil
}
