// Code generated by tommy 0.5.0 (fcabbbf); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/madder/go/internal/alfa/scoped_id"
	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlMultiV1Document struct {
	data   TomlMultiV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlMultiV1(input []byte) (*TomlMultiV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlMultiV1Parsed(doc)
}

// DecodeTomlMultiV1Strict is DecodeTomlMultiV1 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlMultiV1 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlMultiV1Strict(input []byte) (*TomlMultiV1Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlMultiV1Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlMultiV1Parsed(doc *document.Document) (*TomlMultiV1Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlMultiV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vMode, _ok := model.Field("mode"); _ok && _vMode.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vMode.Leaf); _xok {
			d.data.Mode = _x
			_vMode.MarkConsumedString()
		}
	}
	if _vWriteStore, _ok := model.Field("write-store"); _ok && _vWriteStore.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vWriteStore.Leaf); _xok {
			if err := d.data.WriteStore.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("write-store: %w", err)
			}
			_vWriteStore.MarkConsumedText()
		}
	}
	if _vReadStores, _ok := model.Field("read-stores"); _ok && _vReadStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vReadStores.Leaf); _xok {
			d.data.ReadStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := d.data.ReadStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return nil, fmt.Errorf("read-stores[%d]: %w", _si, err)
				}
			}
			_vReadStores.MarkConsumed()
		}
	}
	if _vMirrorStores, _ok := model.Field("mirror-stores"); _ok && _vMirrorStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vMirrorStores.Leaf); _xok {
			d.data.MirrorStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := d.data.MirrorStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return nil, fmt.Errorf("mirror-stores[%d]: %w", _si, err)
				}
			}
			_vMirrorStores.MarkConsumed()
		}
	}
	if _vReadFill, _ok := model.Field("read-fill"); _ok && _vReadFill.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vReadFill.Leaf); _xok {
			d.data.ReadFill = &_x
			_vReadFill.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := model.Field("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := d.data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumedText()
		}
	}
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	return d, nil
}

func (d *TomlMultiV1Document) Data() *TomlMultiV1 {
	return &d.data
}

func (d *TomlMultiV1Document) Encode() ([]byte, error) {
	if err := d.data.Validate(); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}
	if d.data.Mode != "" || cst.HasValue(d.cstDoc.Root(), "mode") {
		if err := cst.SetAny(d.cstDoc.Root(), "mode", d.data.Mode); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.WriteStore.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("write-store: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "write-store", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "write-store")
		}
	}
	{
		if len(d.data.ReadStores) > 0 || cst.HasValue(d.cstDoc.Root(), "read-stores") {
			vals := make([]string, len(d.data.ReadStores))
			for i, item := range d.data.ReadStores {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("read-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "read-stores", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(d.data.MirrorStores) > 0 || cst.HasValue(d.cstDoc.Root(), "mirror-stores") {
			vals := make([]string, len(d.data.MirrorStores))
			for i, item := range d.data.MirrorStores {
				v, err := item.MarshalText()
				if err != nil {
					return nil, fmt.Errorf("mirror-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(d.cstDoc.Root(), "mirror-stores", vals); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.ReadFill != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "read-fill", *d.data.ReadFill); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.InstanceId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(d.cstDoc.Root(), "instance-id", string(v)); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(d.cstDoc.Root(), "instance-id")
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlMultiV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlMultiV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlMultiV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlMultiV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlMultiV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlMultiV1Into(data *TomlMultiV1, sub *cst.Value) error {
	if _vMode, _ok := sub.Field("mode"); _ok && _vMode.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vMode.Leaf); _xok {
			data.Mode = _x
			_vMode.MarkConsumedString()
		}
	}
	if _vWriteStore, _ok := sub.Field("write-store"); _ok && _vWriteStore.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vWriteStore.Leaf); _xok {
			if err := data.WriteStore.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("write-store: %w", err)
			}
			_vWriteStore.MarkConsumedText()
		}
	}
	if _vReadStores, _ok := sub.Field("read-stores"); _ok && _vReadStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vReadStores.Leaf); _xok {
			data.ReadStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := data.ReadStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return fmt.Errorf("read-stores[%d]: %w", _si, err)
				}
			}
			_vReadStores.MarkConsumed()
		}
	}
	if _vMirrorStores, _ok := sub.Field("mirror-stores"); _ok && _vMirrorStores.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vMirrorStores.Leaf); _xok {
			data.MirrorStores = make([]scoped_id.Id, len(_x))
			for _si, _s := range _x {
				if err := data.MirrorStores[_si].UnmarshalText([]byte(_s)); err != nil {
					return fmt.Errorf("mirror-stores[%d]: %w", _si, err)
				}
			}
			_vMirrorStores.MarkConsumed()
		}
	}
	if _vReadFill, _ok := sub.Field("read-fill"); _ok && _vReadFill.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vReadFill.Leaf); _xok {
			data.ReadFill = &_x
			_vReadFill.MarkConsumed()
		}
	}
	if _vInstanceId, _ok := sub.Field("instance-id"); _ok && _vInstanceId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInstanceId.Leaf); _xok {
			if err := data.InstanceId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("instance-id: %w", err)
			}
			_vInstanceId.MarkConsumedText()
		}
	}
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	return nil
}

func EncodeTomlMultiV1From(data *TomlMultiV1, doc *document.Document, container *cst.Node) error {
	if err := data.Validate(); err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}
	if data.Mode != "" || cst.HasValue(container, "mode") {
		if err := cst.SetAny(container, "mode", data.Mode); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.WriteStore.MarshalText()
		if err != nil {
			return fmt.Errorf("write-store: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "write-store", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "write-store")
		}
	}
	{
		if len(data.ReadStores) > 0 || cst.HasValue(container, "read-stores") {
			vals := make([]string, len(data.ReadStores))
			for i, item := range data.ReadStores {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("read-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "read-stores", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	{
		if len(data.MirrorStores) > 0 || cst.HasValue(container, "mirror-stores") {
			vals := make([]string, len(data.MirrorStores))
			for i, item := range data.MirrorStores {
				v, err := item.MarshalText()
				if err != nil {
					return fmt.Errorf("mirror-stores[%d]: %w", i, err)
				}
				vals[i] = string(v)
			}
			if err := cst.SetAny(container, "mirror-stores", vals); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.ReadFill != nil {
		if err := cst.SetAny(container, "read-fill", *data.ReadFill); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.InstanceId.MarshalText()
		if err != nil {
			return fmt.Errorf("instance-id: %w", err)
		}
		if len(v) > 0 {
			if err := cst.SetAny(container, "instance-id", string(v)); err != nil {
				return fmt.Errorf("%w", err)
			}
		} else {
			cst.DeleteValue(container, "instance-id")
		}
	}
	return nil
}
