// Code generated by tommy 0.4.7 (d9d6558); DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlInventoryArchiveV2Document struct {
	data   TomlInventoryArchiveV2
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlInventoryArchiveV2(input []byte) (*TomlInventoryArchiveV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlInventoryArchiveV2Document{
		cstDoc: doc,
		model:  model,
	}

	if _vHashTypeId, _ok := model.Get("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := d.data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumed()
		}
	}
	if _vCompressionType, _ok := model.Get("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			d.data.CompressionType = _x
			_vCompressionType.MarkConsumed()
		}
	}
	if _vEncryption, _ok := model.Get("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEncryption.Leaf); _xok {
			if err := d.data.Encryption.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("encryption: %w", err)
			}
			_vEncryption.MarkConsumed()
		}
	}
	if _vDelta, _ok := model.Get("delta"); _ok && _vDelta.Kind == cst.VTable {
		_vDelta.MarkSeen()
		if _vDeltaEnabled, _ok := _vDelta.Get("enabled"); _ok && _vDeltaEnabled.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vDeltaEnabled.Leaf); _xok {
				d.data.Delta.Enabled = _x
				_vDeltaEnabled.MarkConsumed()
			}
		}
		if _vDeltaAlgorithm, _ok := _vDelta.Get("algorithm"); _ok && _vDeltaAlgorithm.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDeltaAlgorithm.Leaf); _xok {
				d.data.Delta.Algorithm = _x
				_vDeltaAlgorithm.MarkConsumed()
			}
		}
		if _vDeltaMinBlobSize, _ok := _vDelta.Get("min-blob-size"); _ok && _vDeltaMinBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vDeltaMinBlobSize.Leaf); _xok {
				d.data.Delta.MinBlobSize = _x
				_vDeltaMinBlobSize.MarkConsumed()
			}
		}
		if _vDeltaMaxBlobSize, _ok := _vDelta.Get("max-blob-size"); _ok && _vDeltaMaxBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vDeltaMaxBlobSize.Leaf); _xok {
				d.data.Delta.MaxBlobSize = _x
				_vDeltaMaxBlobSize.MarkConsumed()
			}
		}
		if _vDeltaSizeRatio, _ok := _vDelta.Get("size-ratio"); _ok && _vDeltaSizeRatio.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractFloat64(_vDeltaSizeRatio.Leaf); _xok {
				d.data.Delta.SizeRatio = _x
				_vDeltaSizeRatio.MarkConsumed()
			}
		}
		if _vDeltaSignature, _ok := _vDelta.Get("signature"); _ok && _vDeltaSignature.Kind == cst.VTable {
			_vDeltaSignature.MarkSeen()
			if _vDeltaSignatureType, _ok := _vDeltaSignature.Get("type"); _ok && _vDeltaSignatureType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vDeltaSignatureType.Leaf); _xok {
					d.data.Delta.Signature.Type = _x
					_vDeltaSignatureType.MarkConsumed()
				}
			}
			if _vDeltaSignatureSignatureLen, _ok := _vDeltaSignature.Get("signature-len"); _ok && _vDeltaSignatureSignatureLen.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureSignatureLen.Leaf); _xok {
					d.data.Delta.Signature.SignatureLen = _x
					_vDeltaSignatureSignatureLen.MarkConsumed()
				}
			}
			if _vDeltaSignatureAvgChunkSize, _ok := _vDeltaSignature.Get("avg-chunk-size"); _ok && _vDeltaSignatureAvgChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureAvgChunkSize.Leaf); _xok {
					d.data.Delta.Signature.AvgChunkSize = _x
					_vDeltaSignatureAvgChunkSize.MarkConsumed()
				}
			}
			if _vDeltaSignatureMinChunkSize, _ok := _vDeltaSignature.Get("min-chunk-size"); _ok && _vDeltaSignatureMinChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureMinChunkSize.Leaf); _xok {
					d.data.Delta.Signature.MinChunkSize = _x
					_vDeltaSignatureMinChunkSize.MarkConsumed()
				}
			}
			if _vDeltaSignatureMaxChunkSize, _ok := _vDeltaSignature.Get("max-chunk-size"); _ok && _vDeltaSignatureMaxChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureMaxChunkSize.Leaf); _xok {
					d.data.Delta.Signature.MaxChunkSize = _x
					_vDeltaSignatureMaxChunkSize.MarkConsumed()
				}
			}
		} else {
			if _vType, _ok := _vDelta.Get("type"); _ok && _vType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
					d.data.Delta.Signature.Type = _x
					_vType.MarkConsumed()
				}
			}
			if _vSignatureLen, _ok := _vDelta.Get("signature-len"); _ok && _vSignatureLen.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vSignatureLen.Leaf); _xok {
					d.data.Delta.Signature.SignatureLen = _x
					_vSignatureLen.MarkConsumed()
				}
			}
			if _vAvgChunkSize, _ok := _vDelta.Get("avg-chunk-size"); _ok && _vAvgChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vAvgChunkSize.Leaf); _xok {
					d.data.Delta.Signature.AvgChunkSize = _x
					_vAvgChunkSize.MarkConsumed()
				}
			}
			if _vMinChunkSize, _ok := _vDelta.Get("min-chunk-size"); _ok && _vMinChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vMinChunkSize.Leaf); _xok {
					d.data.Delta.Signature.MinChunkSize = _x
					_vMinChunkSize.MarkConsumed()
				}
			}
			if _vMaxChunkSize, _ok := _vDelta.Get("max-chunk-size"); _ok && _vMaxChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vMaxChunkSize.Leaf); _xok {
					d.data.Delta.Signature.MaxChunkSize = _x
					_vMaxChunkSize.MarkConsumed()
				}
			}
		}
		if _vDeltaSelector, _ok := _vDelta.Get("selector"); _ok && _vDeltaSelector.Kind == cst.VTable {
			_vDeltaSelector.MarkSeen()
			if _vDeltaSelectorType, _ok := _vDeltaSelector.Get("type"); _ok && _vDeltaSelectorType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vDeltaSelectorType.Leaf); _xok {
					d.data.Delta.Selector.Type = _x
					_vDeltaSelectorType.MarkConsumed()
				}
			}
			if _vDeltaSelectorBands, _ok := _vDeltaSelector.Get("bands"); _ok && _vDeltaSelectorBands.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSelectorBands.Leaf); _xok {
					d.data.Delta.Selector.Bands = _x
					_vDeltaSelectorBands.MarkConsumed()
				}
			}
			if _vDeltaSelectorRowsPerBand, _ok := _vDeltaSelector.Get("rows-per-band"); _ok && _vDeltaSelectorRowsPerBand.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSelectorRowsPerBand.Leaf); _xok {
					d.data.Delta.Selector.RowsPerBand = _x
					_vDeltaSelectorRowsPerBand.MarkConsumed()
				}
			}
			if _vDeltaSelectorMinBlobSize, _ok := _vDeltaSelector.Get("min-blob-size"); _ok && _vDeltaSelectorMinBlobSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractUint64(_vDeltaSelectorMinBlobSize.Leaf); _xok {
					d.data.Delta.Selector.MinBlobSize = _x
					_vDeltaSelectorMinBlobSize.MarkConsumed()
				}
			}
			if _vDeltaSelectorMaxBlobSize, _ok := _vDeltaSelector.Get("max-blob-size"); _ok && _vDeltaSelectorMaxBlobSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractUint64(_vDeltaSelectorMaxBlobSize.Leaf); _xok {
					d.data.Delta.Selector.MaxBlobSize = _x
					_vDeltaSelectorMaxBlobSize.MarkConsumed()
				}
			}
		} else {
			if _vType, _ok := _vDelta.Get("type"); _ok && _vType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
					d.data.Delta.Selector.Type = _x
					_vType.MarkConsumed()
				}
			}
			if _vBands, _ok := _vDelta.Get("bands"); _ok && _vBands.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vBands.Leaf); _xok {
					d.data.Delta.Selector.Bands = _x
					_vBands.MarkConsumed()
				}
			}
			if _vRowsPerBand, _ok := _vDelta.Get("rows-per-band"); _ok && _vRowsPerBand.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vRowsPerBand.Leaf); _xok {
					d.data.Delta.Selector.RowsPerBand = _x
					_vRowsPerBand.MarkConsumed()
				}
			}
		}
	} else {
		if _vEnabled, _ok := model.Get("enabled"); _ok && _vEnabled.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vEnabled.Leaf); _xok {
				d.data.Delta.Enabled = _x
				_vEnabled.MarkConsumed()
			}
		}
		if _vAlgorithm, _ok := model.Get("algorithm"); _ok && _vAlgorithm.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vAlgorithm.Leaf); _xok {
				d.data.Delta.Algorithm = _x
				_vAlgorithm.MarkConsumed()
			}
		}
		if _vMinBlobSize, _ok := model.Get("min-blob-size"); _ok && _vMinBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vMinBlobSize.Leaf); _xok {
				d.data.Delta.MinBlobSize = _x
				_vMinBlobSize.MarkConsumed()
			}
		}
		if _vMaxBlobSize, _ok := model.Get("max-blob-size"); _ok && _vMaxBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vMaxBlobSize.Leaf); _xok {
				d.data.Delta.MaxBlobSize = _x
				_vMaxBlobSize.MarkConsumed()
			}
		}
		if _vSizeRatio, _ok := model.Get("size-ratio"); _ok && _vSizeRatio.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractFloat64(_vSizeRatio.Leaf); _xok {
				d.data.Delta.SizeRatio = _x
				_vSizeRatio.MarkConsumed()
			}
		}
	}
	if _vMaxPackSize, _ok := model.Get("max-pack-size"); _ok && _vMaxPackSize.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractUint64(_vMaxPackSize.Leaf); _xok {
			d.data.MaxPackSize = _x
			_vMaxPackSize.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlInventoryArchiveV2Document) Data() *TomlInventoryArchiveV2 {
	return &d.data
}

func (d *TomlInventoryArchiveV2Document) Encode() ([]byte, error) {
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.CompressionType != "" || cst.HasValue(d.cstDoc.Root(), "compression-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "compression-type", d.data.CompressionType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Encryption.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "encryption", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "delta")
		if d.data.Delta.Enabled != false || cst.HasValue(tableNode, "enabled") {
			if err := cst.SetAny(tableNode, "enabled", d.data.Delta.Enabled); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Delta.Algorithm != "" || cst.HasValue(tableNode, "algorithm") {
			if err := cst.SetAny(tableNode, "algorithm", d.data.Delta.Algorithm); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Delta.MinBlobSize != 0 || cst.HasValue(tableNode, "min-blob-size") {
			if err := cst.SetAny(tableNode, "min-blob-size", d.data.Delta.MinBlobSize); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Delta.MaxBlobSize != 0 || cst.HasValue(tableNode, "max-blob-size") {
			if err := cst.SetAny(tableNode, "max-blob-size", d.data.Delta.MaxBlobSize); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Delta.SizeRatio != 0.0 || cst.HasValue(tableNode, "size-ratio") {
			if err := cst.SetAny(tableNode, "size-ratio", d.data.Delta.SizeRatio); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		{
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "signature")
			if d.data.Delta.Signature.Type != "" || cst.HasValue(tableNode, "type") {
				if err := cst.SetAny(tableNode, "type", d.data.Delta.Signature.Type); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Signature.SignatureLen != 0 || cst.HasValue(tableNode, "signature-len") {
				if err := cst.SetAny(tableNode, "signature-len", d.data.Delta.Signature.SignatureLen); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Signature.AvgChunkSize != 0 || cst.HasValue(tableNode, "avg-chunk-size") {
				if err := cst.SetAny(tableNode, "avg-chunk-size", d.data.Delta.Signature.AvgChunkSize); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Signature.MinChunkSize != 0 || cst.HasValue(tableNode, "min-chunk-size") {
				if err := cst.SetAny(tableNode, "min-chunk-size", d.data.Delta.Signature.MinChunkSize); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Signature.MaxChunkSize != 0 || cst.HasValue(tableNode, "max-chunk-size") {
				if err := cst.SetAny(tableNode, "max-chunk-size", d.data.Delta.Signature.MaxChunkSize); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		{
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "selector")
			if d.data.Delta.Selector.Type != "" || cst.HasValue(tableNode, "type") {
				if err := cst.SetAny(tableNode, "type", d.data.Delta.Selector.Type); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Selector.Bands != 0 || cst.HasValue(tableNode, "bands") {
				if err := cst.SetAny(tableNode, "bands", d.data.Delta.Selector.Bands); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Selector.RowsPerBand != 0 || cst.HasValue(tableNode, "rows-per-band") {
				if err := cst.SetAny(tableNode, "rows-per-band", d.data.Delta.Selector.RowsPerBand); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Selector.MinBlobSize != 0 || cst.HasValue(tableNode, "min-blob-size") {
				if err := cst.SetAny(tableNode, "min-blob-size", d.data.Delta.Selector.MinBlobSize); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Delta.Selector.MaxBlobSize != 0 || cst.HasValue(tableNode, "max-blob-size") {
				if err := cst.SetAny(tableNode, "max-blob-size", d.data.Delta.Selector.MaxBlobSize); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if d.data.MaxPackSize != 0 || cst.HasValue(d.cstDoc.Root(), "max-pack-size") {
		if err := cst.SetAny(d.cstDoc.Root(), "max-pack-size", d.data.MaxPackSize); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlInventoryArchiveV2Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlInventoryArchiveV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlInventoryArchiveV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlInventoryArchiveV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlInventoryArchiveV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlInventoryArchiveV2Into(data *TomlInventoryArchiveV2, sub *cst.Value) error {
	if _vHashTypeId, _ok := sub.Get("hash_type-id"); _ok && _vHashTypeId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vHashTypeId.Leaf); _xok {
			if err := data.HashTypeId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("hash_type-id: %w", err)
			}
			_vHashTypeId.MarkConsumed()
		}
	}
	if _vCompressionType, _ok := sub.Get("compression-type"); _ok && _vCompressionType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCompressionType.Leaf); _xok {
			data.CompressionType = _x
			_vCompressionType.MarkConsumed()
		}
	}
	if _vEncryption, _ok := sub.Get("encryption"); _ok && _vEncryption.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEncryption.Leaf); _xok {
			if err := data.Encryption.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("encryption: %w", err)
			}
			_vEncryption.MarkConsumed()
		}
	}
	if _vDelta, _ok := sub.Get("delta"); _ok && _vDelta.Kind == cst.VTable {
		_vDelta.MarkSeen()
		if _vDeltaEnabled, _ok := _vDelta.Get("enabled"); _ok && _vDeltaEnabled.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vDeltaEnabled.Leaf); _xok {
				data.Delta.Enabled = _x
				_vDeltaEnabled.MarkConsumed()
			}
		}
		if _vDeltaAlgorithm, _ok := _vDelta.Get("algorithm"); _ok && _vDeltaAlgorithm.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vDeltaAlgorithm.Leaf); _xok {
				data.Delta.Algorithm = _x
				_vDeltaAlgorithm.MarkConsumed()
			}
		}
		if _vDeltaMinBlobSize, _ok := _vDelta.Get("min-blob-size"); _ok && _vDeltaMinBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vDeltaMinBlobSize.Leaf); _xok {
				data.Delta.MinBlobSize = _x
				_vDeltaMinBlobSize.MarkConsumed()
			}
		}
		if _vDeltaMaxBlobSize, _ok := _vDelta.Get("max-blob-size"); _ok && _vDeltaMaxBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vDeltaMaxBlobSize.Leaf); _xok {
				data.Delta.MaxBlobSize = _x
				_vDeltaMaxBlobSize.MarkConsumed()
			}
		}
		if _vDeltaSizeRatio, _ok := _vDelta.Get("size-ratio"); _ok && _vDeltaSizeRatio.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractFloat64(_vDeltaSizeRatio.Leaf); _xok {
				data.Delta.SizeRatio = _x
				_vDeltaSizeRatio.MarkConsumed()
			}
		}
		if _vDeltaSignature, _ok := _vDelta.Get("signature"); _ok && _vDeltaSignature.Kind == cst.VTable {
			_vDeltaSignature.MarkSeen()
			if _vDeltaSignatureType, _ok := _vDeltaSignature.Get("type"); _ok && _vDeltaSignatureType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vDeltaSignatureType.Leaf); _xok {
					data.Delta.Signature.Type = _x
					_vDeltaSignatureType.MarkConsumed()
				}
			}
			if _vDeltaSignatureSignatureLen, _ok := _vDeltaSignature.Get("signature-len"); _ok && _vDeltaSignatureSignatureLen.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureSignatureLen.Leaf); _xok {
					data.Delta.Signature.SignatureLen = _x
					_vDeltaSignatureSignatureLen.MarkConsumed()
				}
			}
			if _vDeltaSignatureAvgChunkSize, _ok := _vDeltaSignature.Get("avg-chunk-size"); _ok && _vDeltaSignatureAvgChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureAvgChunkSize.Leaf); _xok {
					data.Delta.Signature.AvgChunkSize = _x
					_vDeltaSignatureAvgChunkSize.MarkConsumed()
				}
			}
			if _vDeltaSignatureMinChunkSize, _ok := _vDeltaSignature.Get("min-chunk-size"); _ok && _vDeltaSignatureMinChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureMinChunkSize.Leaf); _xok {
					data.Delta.Signature.MinChunkSize = _x
					_vDeltaSignatureMinChunkSize.MarkConsumed()
				}
			}
			if _vDeltaSignatureMaxChunkSize, _ok := _vDeltaSignature.Get("max-chunk-size"); _ok && _vDeltaSignatureMaxChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSignatureMaxChunkSize.Leaf); _xok {
					data.Delta.Signature.MaxChunkSize = _x
					_vDeltaSignatureMaxChunkSize.MarkConsumed()
				}
			}
		} else {
			if _vType, _ok := _vDelta.Get("type"); _ok && _vType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
					data.Delta.Signature.Type = _x
					_vType.MarkConsumed()
				}
			}
			if _vSignatureLen, _ok := _vDelta.Get("signature-len"); _ok && _vSignatureLen.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vSignatureLen.Leaf); _xok {
					data.Delta.Signature.SignatureLen = _x
					_vSignatureLen.MarkConsumed()
				}
			}
			if _vAvgChunkSize, _ok := _vDelta.Get("avg-chunk-size"); _ok && _vAvgChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vAvgChunkSize.Leaf); _xok {
					data.Delta.Signature.AvgChunkSize = _x
					_vAvgChunkSize.MarkConsumed()
				}
			}
			if _vMinChunkSize, _ok := _vDelta.Get("min-chunk-size"); _ok && _vMinChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vMinChunkSize.Leaf); _xok {
					data.Delta.Signature.MinChunkSize = _x
					_vMinChunkSize.MarkConsumed()
				}
			}
			if _vMaxChunkSize, _ok := _vDelta.Get("max-chunk-size"); _ok && _vMaxChunkSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vMaxChunkSize.Leaf); _xok {
					data.Delta.Signature.MaxChunkSize = _x
					_vMaxChunkSize.MarkConsumed()
				}
			}
		}
		if _vDeltaSelector, _ok := _vDelta.Get("selector"); _ok && _vDeltaSelector.Kind == cst.VTable {
			_vDeltaSelector.MarkSeen()
			if _vDeltaSelectorType, _ok := _vDeltaSelector.Get("type"); _ok && _vDeltaSelectorType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vDeltaSelectorType.Leaf); _xok {
					data.Delta.Selector.Type = _x
					_vDeltaSelectorType.MarkConsumed()
				}
			}
			if _vDeltaSelectorBands, _ok := _vDeltaSelector.Get("bands"); _ok && _vDeltaSelectorBands.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSelectorBands.Leaf); _xok {
					data.Delta.Selector.Bands = _x
					_vDeltaSelectorBands.MarkConsumed()
				}
			}
			if _vDeltaSelectorRowsPerBand, _ok := _vDeltaSelector.Get("rows-per-band"); _ok && _vDeltaSelectorRowsPerBand.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vDeltaSelectorRowsPerBand.Leaf); _xok {
					data.Delta.Selector.RowsPerBand = _x
					_vDeltaSelectorRowsPerBand.MarkConsumed()
				}
			}
			if _vDeltaSelectorMinBlobSize, _ok := _vDeltaSelector.Get("min-blob-size"); _ok && _vDeltaSelectorMinBlobSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractUint64(_vDeltaSelectorMinBlobSize.Leaf); _xok {
					data.Delta.Selector.MinBlobSize = _x
					_vDeltaSelectorMinBlobSize.MarkConsumed()
				}
			}
			if _vDeltaSelectorMaxBlobSize, _ok := _vDeltaSelector.Get("max-blob-size"); _ok && _vDeltaSelectorMaxBlobSize.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractUint64(_vDeltaSelectorMaxBlobSize.Leaf); _xok {
					data.Delta.Selector.MaxBlobSize = _x
					_vDeltaSelectorMaxBlobSize.MarkConsumed()
				}
			}
		} else {
			if _vType, _ok := _vDelta.Get("type"); _ok && _vType.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
					data.Delta.Selector.Type = _x
					_vType.MarkConsumed()
				}
			}
			if _vBands, _ok := _vDelta.Get("bands"); _ok && _vBands.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vBands.Leaf); _xok {
					data.Delta.Selector.Bands = _x
					_vBands.MarkConsumed()
				}
			}
			if _vRowsPerBand, _ok := _vDelta.Get("rows-per-band"); _ok && _vRowsPerBand.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractInt(_vRowsPerBand.Leaf); _xok {
					data.Delta.Selector.RowsPerBand = _x
					_vRowsPerBand.MarkConsumed()
				}
			}
		}
	} else {
		if _vEnabled, _ok := sub.Get("enabled"); _ok && _vEnabled.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vEnabled.Leaf); _xok {
				data.Delta.Enabled = _x
				_vEnabled.MarkConsumed()
			}
		}
		if _vAlgorithm, _ok := sub.Get("algorithm"); _ok && _vAlgorithm.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vAlgorithm.Leaf); _xok {
				data.Delta.Algorithm = _x
				_vAlgorithm.MarkConsumed()
			}
		}
		if _vMinBlobSize, _ok := sub.Get("min-blob-size"); _ok && _vMinBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vMinBlobSize.Leaf); _xok {
				data.Delta.MinBlobSize = _x
				_vMinBlobSize.MarkConsumed()
			}
		}
		if _vMaxBlobSize, _ok := sub.Get("max-blob-size"); _ok && _vMaxBlobSize.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractUint64(_vMaxBlobSize.Leaf); _xok {
				data.Delta.MaxBlobSize = _x
				_vMaxBlobSize.MarkConsumed()
			}
		}
		if _vSizeRatio, _ok := sub.Get("size-ratio"); _ok && _vSizeRatio.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractFloat64(_vSizeRatio.Leaf); _xok {
				data.Delta.SizeRatio = _x
				_vSizeRatio.MarkConsumed()
			}
		}
	}
	if _vMaxPackSize, _ok := sub.Get("max-pack-size"); _ok && _vMaxPackSize.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractUint64(_vMaxPackSize.Leaf); _xok {
			data.MaxPackSize = _x
			_vMaxPackSize.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlInventoryArchiveV2From(data *TomlInventoryArchiveV2, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := cst.SetAny(container, "hash_type-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.CompressionType != "" || cst.HasValue(container, "compression-type") {
		if err := cst.SetAny(container, "compression-type", data.CompressionType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Encryption.MarshalText()
		if err != nil {
			return fmt.Errorf("encryption: %w", err)
		}
		if err := cst.SetAny(container, "encryption", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "delta")
		if data.Delta.Enabled != false || cst.HasValue(tableNode, "enabled") {
			if err := cst.SetAny(tableNode, "enabled", data.Delta.Enabled); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Delta.Algorithm != "" || cst.HasValue(tableNode, "algorithm") {
			if err := cst.SetAny(tableNode, "algorithm", data.Delta.Algorithm); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Delta.MinBlobSize != 0 || cst.HasValue(tableNode, "min-blob-size") {
			if err := cst.SetAny(tableNode, "min-blob-size", data.Delta.MinBlobSize); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Delta.MaxBlobSize != 0 || cst.HasValue(tableNode, "max-blob-size") {
			if err := cst.SetAny(tableNode, "max-blob-size", data.Delta.MaxBlobSize); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Delta.SizeRatio != 0.0 || cst.HasValue(tableNode, "size-ratio") {
			if err := cst.SetAny(tableNode, "size-ratio", data.Delta.SizeRatio); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		{
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "signature")
			if data.Delta.Signature.Type != "" || cst.HasValue(tableNode, "type") {
				if err := cst.SetAny(tableNode, "type", data.Delta.Signature.Type); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Signature.SignatureLen != 0 || cst.HasValue(tableNode, "signature-len") {
				if err := cst.SetAny(tableNode, "signature-len", data.Delta.Signature.SignatureLen); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Signature.AvgChunkSize != 0 || cst.HasValue(tableNode, "avg-chunk-size") {
				if err := cst.SetAny(tableNode, "avg-chunk-size", data.Delta.Signature.AvgChunkSize); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Signature.MinChunkSize != 0 || cst.HasValue(tableNode, "min-chunk-size") {
				if err := cst.SetAny(tableNode, "min-chunk-size", data.Delta.Signature.MinChunkSize); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Signature.MaxChunkSize != 0 || cst.HasValue(tableNode, "max-chunk-size") {
				if err := cst.SetAny(tableNode, "max-chunk-size", data.Delta.Signature.MaxChunkSize); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		{
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "selector")
			if data.Delta.Selector.Type != "" || cst.HasValue(tableNode, "type") {
				if err := cst.SetAny(tableNode, "type", data.Delta.Selector.Type); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Selector.Bands != 0 || cst.HasValue(tableNode, "bands") {
				if err := cst.SetAny(tableNode, "bands", data.Delta.Selector.Bands); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Selector.RowsPerBand != 0 || cst.HasValue(tableNode, "rows-per-band") {
				if err := cst.SetAny(tableNode, "rows-per-band", data.Delta.Selector.RowsPerBand); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Selector.MinBlobSize != 0 || cst.HasValue(tableNode, "min-blob-size") {
				if err := cst.SetAny(tableNode, "min-blob-size", data.Delta.Selector.MinBlobSize); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Delta.Selector.MaxBlobSize != 0 || cst.HasValue(tableNode, "max-blob-size") {
				if err := cst.SetAny(tableNode, "max-blob-size", data.Delta.Selector.MaxBlobSize); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if data.MaxPackSize != 0 || cst.HasValue(container, "max-pack-size") {
		if err := cst.SetAny(container, "max-pack-size", data.MaxPackSize); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
