// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlPointerV1Document struct {
	data     TomlPointerV1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlPointerV1(input []byte) (*TomlPointerV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlPointerV1Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "base-path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.BasePath = v
				d.consumed["base-path"] = true
			}
		}
	}
	return d, nil
}
func (d *TomlPointerV1Document) Data() *TomlPointerV1 {
	return &d.data
}
func (d *TomlPointerV1Document) Encode() ([]byte, error) {
	if d.data.BasePath != "" || cst.HasValue(d.cstDoc.Root(), "base-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "base-path", d.data.BasePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *TomlPointerV1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *TomlPointerV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *TomlPointerV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *TomlPointerV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *TomlPointerV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeTomlPointerV1Into(data *TomlPointerV1, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "base-path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.BasePath = v
				consumed[keyPrefix+"base-path"] = true
			}
		}
	}
	return nil
}
func EncodeTomlPointerV1From(data *TomlPointerV1, doc *document.Document, container *cst.Node) error {
	if data.BasePath != "" || cst.HasValue(container, "base-path") {
		if err := cst.SetAny(container, "base-path", data.BasePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
