// Package blob_store_id is a deprecated compatibility alias for
// pkgs/scoped_id. The type was renamed under FDR-0019 to be agnostic to
// blob stores vs. dodder repos. This shim is kept for one release so
// downstream consumers (notably dodder, which imports this path at
// several sites) can migrate without a flag-day when they bump the
// madder flake input.
//
// This file is hand-written, NOT generated by dagnabit: the generating
// internal package is now internal/alfa/scoped_id, whose facade is
// pkgs/scoped_id. Do not regenerate this directory.
//
// Deprecated: use code.linenisgreat.com/madder/go/pkgs/scoped_id.
package blob_store_id

import scoped_id "code.linenisgreat.com/madder/go/pkgs/scoped_id"

// Deprecated: use scoped_id.ErrIdDigestVsLegacyConfig.
type ErrIdDigestVsLegacyConfig = scoped_id.ErrIdDigestVsLegacyConfig

// Deprecated: use scoped_id.Id and friends.
type (
	Id                 = scoped_id.Id
	LocationType       = scoped_id.LocationType
	LocationTypeGetter = scoped_id.LocationTypeGetter
)

// Deprecated: use the scoped_id equivalents.
var (
	LocationTypeCwd       = scoped_id.LocationTypeCwd
	LocationTypeUnknown   = scoped_id.LocationTypeUnknown
	LocationTypeXDGCache  = scoped_id.LocationTypeXDGCache
	LocationTypeXDGSystem = scoped_id.LocationTypeXDGSystem
	LocationTypeXDGUser   = scoped_id.LocationTypeXDGUser
	Make                  = scoped_id.Make
	MakeWithLocation      = scoped_id.MakeWithLocation
)
