// Code generated by dagnabit; DO NOT EDIT.

package inventory_archive

import internal "github.com/amarbel-llc/madder/go/internal/alfa/inventory_archive"

type (
	BaseSelector            = internal.BaseSelector
	BaseSelectorParams      = internal.BaseSelectorParams
	BlobMetadata            = internal.BlobMetadata
	BlobSet                 = internal.BlobSet
	Bsdiff                  = internal.Bsdiff
	CacheEntry              = internal.CacheEntry
	CacheEntryV1            = internal.CacheEntryV1
	CacheReader             = internal.CacheReader
	CacheReaderV1           = internal.CacheReaderV1
	DataEntry               = internal.DataEntry
	DataEntryV1             = internal.DataEntryV1
	DataReader              = internal.DataReader
	DataReaderV1            = internal.DataReaderV1
	DataWriter              = internal.DataWriter
	DataWriterV1            = internal.DataWriterV1
	DeltaAlgorithm          = internal.DeltaAlgorithm
	DeltaAssignments        = internal.DeltaAssignments
	GearCDCMinHashComputer  = internal.GearCDCMinHashComputer
	IndexEntry              = internal.IndexEntry
	IndexEntryV1            = internal.IndexEntryV1
	IndexReader             = internal.IndexReader
	IndexReaderV1           = internal.IndexReaderV1
	LSHBandingSelector      = internal.LSHBandingSelector
	SignatureComputer       = internal.SignatureComputer
	SignatureComputerParams = internal.SignatureComputerParams
	SizeBasedSelector       = internal.SizeBasedSelector
)

var (
	BaseSelectorForName       = internal.BaseSelectorForName
	ByteToCompression         = internal.ByteToCompression
	CompressionToByte         = internal.CompressionToByte
	DeltaAlgorithmByteForName = internal.DeltaAlgorithmByteForName
	DeltaAlgorithmForByte     = internal.DeltaAlgorithmForByte
	GearCDCChunks             = internal.GearCDCChunks
	MinHashJaccard            = internal.MinHashJaccard
	MinHashSignature          = internal.MinHashSignature
	NewCacheReader            = internal.NewCacheReader
	NewCacheReaderV1          = internal.NewCacheReaderV1
	NewDataReader             = internal.NewDataReader
	NewDataReaderV1           = internal.NewDataReaderV1
	NewDataWriter             = internal.NewDataWriter
	NewDataWriterV1           = internal.NewDataWriterV1
	NewIndexReader            = internal.NewIndexReader
	NewIndexReaderV1          = internal.NewIndexReaderV1
	RegisterBaseSelector      = internal.RegisterBaseSelector
	RegisterDeltaAlgorithm    = internal.RegisterDeltaAlgorithm
	RegisterSignatureComputer = internal.RegisterSignatureComputer
	SignatureComputerForName  = internal.SignatureComputerForName
	ToMap                     = internal.ToMap
	ToMapV1                   = internal.ToMapV1
	WriteCache                = internal.WriteCache
	WriteCacheV1              = internal.WriteCacheV1
	WriteIndex                = internal.WriteIndex
	WriteIndexV1              = internal.WriteIndexV1
)

const (
	CacheFileMagic           = internal.CacheFileMagic
	CacheFileName            = internal.CacheFileName
	CacheFileNameV1          = internal.CacheFileNameV1
	CacheFileVersion         = internal.CacheFileVersion
	CacheFileVersionV1       = internal.CacheFileVersionV1
	CompressionByteGzip      = internal.CompressionByteGzip
	CompressionByteNone      = internal.CompressionByteNone
	CompressionByteZlib      = internal.CompressionByteZlib
	CompressionByteZstd      = internal.CompressionByteZstd
	DataFileExtension        = internal.DataFileExtension
	DataFileExtensionV1      = internal.DataFileExtensionV1
	DataFileMagic            = internal.DataFileMagic
	DataFileVersion          = internal.DataFileVersion
	DataFileVersionV1        = internal.DataFileVersionV1
	DeltaAlgorithmByteBsdiff = internal.DeltaAlgorithmByteBsdiff
	EntryTypeDelta           = internal.EntryTypeDelta
	EntryTypeFull            = internal.EntryTypeFull
	FlagHasDeltas            = internal.FlagHasDeltas
	FlagHasEncryption        = internal.FlagHasEncryption
	FlagHasEncryptionV1      = internal.FlagHasEncryptionV1
	FlagReservedCrossArch    = internal.FlagReservedCrossArch
	IndexFileExtension       = internal.IndexFileExtension
	IndexFileExtensionV1     = internal.IndexFileExtensionV1
	IndexFileMagic           = internal.IndexFileMagic
	IndexFileVersion         = internal.IndexFileVersion
	IndexFileVersionV1       = internal.IndexFileVersionV1
)
