// Code generated by dagnabit; DO NOT EDIT.

package hyphence

import (
	internal "github.com/amarbel-llc/madder/go/internal/charlie/hyphence"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/0/interfaces"
)

type (
	Coder[BLOB any]                                           = internal.Coder[BLOB]
	CoderToTypedBlob[BLOB any]                                = internal.CoderToTypedBlob[BLOB]
	CoderTommy[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]]       = internal.CoderTommy[BLOB, BLOB_PTR]
	CoderTypeMap[BLOB any]                                    = internal.CoderTypeMap[BLOB]
	CoderTypeMapWithoutType[BLOB any]                         = internal.CoderTypeMapWithoutType[BLOB]
	Decoder[BLOB any]                                         = internal.Decoder[BLOB]
	DecoderTypeMapWithoutType[BLOB any]                       = internal.DecoderTypeMapWithoutType[BLOB]
	Document                                                  = internal.Document
	Encoder[BLOB any]                                         = internal.Encoder[BLOB]
	EncoderTypeMapWithoutType[BLOB any]                       = internal.EncoderTypeMapWithoutType[BLOB]
	MetadataBuilder                                           = internal.MetadataBuilder
	MetadataLine                                              = internal.MetadataLine
	MetadataStreamer                                          = internal.MetadataStreamer
	MetadataValidator                                         = internal.MetadataValidator
	MetadataWriterTo                                          = internal.MetadataWriterTo
	Peeker                                                    = internal.Peeker
	Reader                                                    = internal.Reader
	TommyBlobDecoder[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]] = internal.TommyBlobDecoder[BLOB, BLOB_PTR]
	TommyBlobEncoder[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]] = internal.TommyBlobEncoder[BLOB, BLOB_PTR]
	TypedBlob[BLOB any]                                       = internal.TypedBlob[BLOB]
	TypedBlobEmpty                                            = internal.TypedBlobEmpty
	TypedMetadataCoder[BLOB any]                              = internal.TypedMetadataCoder[BLOB]
	Writer                                                    = internal.Writer
)

var (
	BoundaryStringValue          = internal.BoundaryStringValue
	ErrInlineBodyWithAtReference = internal.ErrInlineBodyWithAtReference
	ErrInvalidPrefix             = internal.ErrInvalidPrefix
	ErrMalformedMetadataLine     = internal.ErrMalformedMetadataLine
	PeekBoundaryFromPeeker       = internal.PeekBoundaryFromPeeker
	ReadBoundaryFromPeeker       = internal.ReadBoundaryFromPeeker
	ReadBoundaryFromRingBuffer   = internal.ReadBoundaryFromRingBuffer
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func DecodeFromFile[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](coders internal.CoderToTypedBlob[BLOB], path string) (typedBlob internal.TypedBlob[BLOB], err error) {
	return internal.DecodeFromFile[BLOB, BLOB_PTR](coders, path)
}
func DecodeFromFileInto[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](typedBlob *internal.TypedBlob[BLOB], coders internal.CoderToTypedBlob[BLOB], path string) (err error) {
	return internal.DecodeFromFileInto[BLOB, BLOB_PTR](typedBlob, coders, path)
}
func DecodeFromFileOrEmptyBuffer[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](coders internal.CoderToTypedBlob[BLOB], path string, permitNotExist bool) (typedBlob internal.TypedBlob[BLOB], err error) {
	return internal.DecodeFromFileOrEmptyBuffer[BLOB, BLOB_PTR](coders, path, permitNotExist)
}
func EncodeToFile[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](coders internal.CoderToTypedBlob[BLOB], typedBlob *internal.TypedBlob[BLOB], path string) (err error) {
	return internal.EncodeToFile[BLOB, BLOB_PTR](coders, typedBlob, path)
}

const (
	Boundary = internal.Boundary
)
