// Code generated by dagnabit (0.3.3+8d3cce0); DO NOT EDIT.

package hyphence

import (
	internal "github.com/amarbel-llc/madder/go/internal/charlie/hyphence"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
)

// BodyStreamer is the Blob consumer for `hyphence body` and any
// caller that wants to stream the body section verbatim to a
// writer. Mirrors MetadataStreamer for the metadata side.
type (
	BodyStreamer                                        = internal.BodyStreamer
	Coder[BLOB any]                                     = internal.Coder[BLOB]
	CoderToTypedBlob[BLOB any]                          = internal.CoderToTypedBlob[BLOB]
	CoderTommy[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]] = internal.CoderTommy[BLOB, BLOB_PTR]
	CoderTypeMap[BLOB any]                              = internal.CoderTypeMap[BLOB]
	CoderTypeMapWithoutType[BLOB any]                   = internal.CoderTypeMapWithoutType[BLOB]
)

// CountingDiscardReaderFrom is the Blob consumer for validate, meta,
// and any subcommand that wants to drain the body section without
// preserving it. SawBody is true after ReadFrom if at least one byte
// followed the body separator.
type (
	CountingDiscardReaderFrom           = internal.CountingDiscardReaderFrom
	Decoder[BLOB any]                   = internal.Decoder[BLOB]
	DecoderTypeMapWithoutType[BLOB any] = internal.DecoderTypeMapWithoutType[BLOB]
)

// Document is the parsed metadata section of a hyphence document. The
// body is never buffered into Document — body bytes are streamed by
// the Blob consumer attached to a Reader. Document is the format-only
// model used by `hyphence meta`, `hyphence format`, and the
// `hyphence validate` subcommand; the type-aware Coder/Reader
// machinery in this package is independent.
type (
	Document                            = internal.Document
	Encoder[BLOB any]                   = internal.Encoder[BLOB]
	EncoderTypeMapWithoutType[BLOB any] = internal.EncoderTypeMapWithoutType[BLOB]
)

// FormatBodyEmitter is the Blob consumer for `hyphence format`. By
// the time ReadFrom fires, MetadataBuilder has populated Doc; this
// emits the canonicalized metadata section to Out, then streams the
// body bytes from r to Out.
type FormatBodyEmitter = internal.FormatBodyEmitter

// MetadataBuilder is the metadata consumer for `hyphence format`. It
// parses each metadata line into a structured MetadataLine and
// appends to Doc.Metadata in source order. Comment lines (`%`) are
// buffered as LeadingComments on the next non-comment line, or
// TrailingComments if none follows. Malformed lines abort with
// ErrMalformedMetadataLine or ErrInvalidPrefix.
type MetadataBuilder = internal.MetadataBuilder

// MetadataLine is a single metadata line keyed by its single-character
// prefix. Per RFC 0001 §Metadata Lines, prefixes are one of '!', '@',
// '#', '-', '<', '%'. LeadingComments captures '%' lines that
// preceded this line in source order — comments are entangled with
// the next non-comment line per RFC, so reordering carries them
// along.
type MetadataLine = internal.MetadataLine

// MetadataStreamer is the metadata consumer for `hyphence meta`. It
// copies metadata bytes verbatim from the piped reader supplied by
// hyphence.Reader's metadata pipeline to W. No per-line validation
// happens here — `hyphence meta` is intentionally lenient; users who
// want strict checks run `hyphence validate` first.
type MetadataStreamer = internal.MetadataStreamer

// MetadataValidator is the metadata consumer for `hyphence validate`.
// It parses each metadata line strictly per RFC 0001 §Metadata Lines.
// Tracks SawAtLine for the post-ReadFrom inline-body-AND-@ cross-
// check the validate subcommand performs.
type (
	MetadataValidator                                         = internal.MetadataValidator
	MetadataWriterTo                                          = internal.MetadataWriterTo
	Peeker                                                    = internal.Peeker
	Reader                                                    = internal.Reader
	TommyBlobDecoder[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]] = internal.TommyBlobDecoder[BLOB, BLOB_PTR]
	TommyBlobEncoder[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]] = internal.TommyBlobEncoder[BLOB, BLOB_PTR]
	TypedBlob[BLOB any]                                       = internal.TypedBlob[BLOB]
	TypedBlobEmpty                                            = internal.TypedBlobEmpty
	TypedMetadataCoder[BLOB any]                              = internal.TypedMetadataCoder[BLOB]
	Writer                                                    = internal.Writer
)

var BoundaryStringValue = internal.BoundaryStringValue

// Canonicalize sorts doc.Metadata in place per RFC 0001 §Canonical
// Line Order. Stable sort within each prefix bucket preserves
// insertion order. Each MetadataLine carries its LeadingComments
// across the sort. TrailingComments remain at the document tail.
var Canonicalize = internal.Canonicalize

// ErrInlineBodyWithAtReference is returned when a document has
// both an `@` blob-reference line in its metadata and a body
// section after the closing boundary. RFC 0001 §Metadata Lines
// says decoders SHOULD reject such documents.
var ErrInlineBodyWithAtReference = internal.ErrInlineBodyWithAtReference

// ErrInvalidPrefix is returned when a metadata line's prefix is
// not one of !@#-<%.
var ErrInvalidPrefix = internal.ErrInvalidPrefix

// ErrMalformedMetadataLine is returned when a line in the
// metadata section does not match `<prefix> <content>` shape.
var (
	ErrMalformedMetadataLine   = internal.ErrMalformedMetadataLine
	PeekBoundaryFromPeeker     = internal.PeekBoundaryFromPeeker
	ReadBoundaryFromPeeker     = internal.ReadBoundaryFromPeeker
	ReadBoundaryFromRingBuffer = internal.ReadBoundaryFromRingBuffer
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func DecodeFromFile[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](coders internal.CoderToTypedBlob[BLOB], path string) (typedBlob internal.TypedBlob[BLOB], err error) {
	return internal.DecodeFromFile[BLOB, BLOB_PTR](coders, path)
}

func DecodeFromFileInto[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](typedBlob *internal.TypedBlob[BLOB], coders internal.CoderToTypedBlob[BLOB], path string) (err error) {
	return internal.DecodeFromFileInto[BLOB, BLOB_PTR](typedBlob, coders, path)
}

// For decodes where typedBlob.Blob should be populated with an empty struct
// when the file is missing
func DecodeFromFileOrEmptyBuffer[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](coders internal.CoderToTypedBlob[BLOB], path string, permitNotExist bool) (typedBlob internal.TypedBlob[BLOB], err error) {
	return internal.DecodeFromFileOrEmptyBuffer[BLOB, BLOB_PTR](coders, path, permitNotExist)
}

// EncodeToFile writes typedBlob through coders.EncodeTo to path. A path
// of "-" routes to stdout, mirroring DecodeFromFileInto's stdin
// shortcut. For real paths, files.CreateExclusiveWriteOnly is used so a
// concurrent writer fails fast rather than producing a torn write.
func EncodeToFile[BLOB any, BLOB_PTR interfaces.Ptr[BLOB]](coders internal.CoderToTypedBlob[BLOB], typedBlob *internal.TypedBlob[BLOB], path string) (err error) {
	return internal.EncodeToFile[BLOB, BLOB_PTR](coders, typedBlob, path)
}

const Boundary = internal.Boundary
