// Code generated by dagnabit; DO NOT EDIT.

package markl

import (
	domaininterfaces "github.com/amarbel-llc/madder/go/internal/0/domain_interfaces"
	internal "github.com/amarbel-llc/madder/go/internal/bravo/markl"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/0/interfaces"
	constraints "golang.org/x/exp/constraints"
)

type (
	DiscoveredKey                                                = internal.DiscoveredKey
	ErrFormatOperationNotSupported                               = internal.ErrFormatOperationNotSupported
	ErrIsNull                                                    = internal.ErrIsNull
	ErrNotEqual                                                  = internal.ErrNotEqual
	ErrNotEqualBytes                                             = internal.ErrNotEqualBytes
	ErrUnsupportedIdFormat                                       = internal.ErrUnsupportedIdFormat
	Format                                                       = internal.Format
	FormatHash                                                   = internal.FormatHash
	FormatId                                                     = internal.FormatId
	FormatPub                                                    = internal.FormatPub
	FormatSec                                                    = internal.FormatSec
	FuncFormatPubVerify                                          = internal.FuncFormatPubVerify
	FuncFormatSecGenerate                                        = internal.FuncFormatSecGenerate
	FuncFormatSecGetIOWrapper                                    = internal.FuncFormatSecGetIOWrapper
	FuncFormatSecGetPublicKey                                    = internal.FuncFormatSecGetPublicKey
	FuncFormatSecSign                                            = internal.FuncFormatSecSign
	Hash                                                         = internal.Hash
	Id                                                           = internal.Id
	IdBinaryDecodingFormatTypeData                               = internal.IdBinaryDecodingFormatTypeData
	IdBinaryDecodingTypeData                                     = internal.IdBinaryDecodingTypeData
	IdBinaryEncodingFormatTypeData                               = internal.IdBinaryEncodingFormatTypeData
	IdBinaryEncodingTypeData                                     = internal.IdBinaryEncodingTypeData
	IdBroken                                                     = internal.IdBroken
	IdFormat                                                     = internal.IdFormat
	Lock[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]] = internal.Lock[KEY, KEY_PTR]
	Purpose                                                      = internal.Purpose
	PurposeType                                                  = internal.PurposeType
	Slice                                                        = internal.Slice
)

var (
	AgeX25519Generate                  = internal.AgeX25519Generate
	AgeX25519GetIOWrapper              = internal.AgeX25519GetIOWrapper
	AgeX25519GetPublicKey              = internal.AgeX25519GetPublicKey
	AssertEqual                        = internal.AssertEqual
	AssertIdIsNotNull                  = internal.AssertIdIsNotNull
	AssertIdIsNotNullWithPurpose       = internal.AssertIdIsNotNullWithPurpose
	AssertIdIsNull                     = internal.AssertIdIsNull
	Clone                              = internal.Clone
	CompareToReader                    = internal.CompareToReader
	CompareToReaderAt                  = internal.CompareToReaderAt
	ConnectEcdsaP256AgentSigner        = internal.ConnectEcdsaP256AgentSigner
	ConnectSSHAgentSigner              = internal.ConnectSSHAgentSigner
	DiscoverPivyAgentECDHKeys          = internal.DiscoverPivyAgentECDHKeys
	DiscoverPivyAgentECDHKeysVerbose   = internal.DiscoverPivyAgentECDHKeysVerbose
	DiscoverSSHAgentECDHKeys           = internal.DiscoverSSHAgentECDHKeys
	DiscoverSSHAgentECDHKeysVerbose    = internal.DiscoverSSHAgentECDHKeysVerbose
	DiscoverSSHAgentEd25519Keys        = internal.DiscoverSSHAgentEd25519Keys
	DiscoverSSHAgentEd25519KeysVerbose = internal.DiscoverSSHAgentEd25519KeysVerbose
	EcdsaP256Verify                    = internal.EcdsaP256Verify
	Ed25519GeneratePrivateKey          = internal.Ed25519GeneratePrivateKey
	Ed25519GetPublicKey                = internal.Ed25519GetPublicKey
	Ed25519Sign                        = internal.Ed25519Sign
	Ed25519Verify                      = internal.Ed25519Verify
	Equals                             = internal.Equals
	EqualsReader                       = internal.EqualsReader
	ErrEcdsaP256SSHAgentNotConnected   = internal.ErrEcdsaP256SSHAgentNotConnected
	ErrEd25519SSHAgentNotConnected     = internal.ErrEd25519SSHAgentNotConnected
	ErrEd25519SeedNotPrivateKey        = internal.ErrEd25519SeedNotPrivateKey
	ErrEmptyType                       = internal.ErrEmptyType
	ErrNilFormat                       = internal.ErrNilFormat
	FormatBytesAsHex                   = internal.FormatBytesAsHex
	FormatHashBlake2b256               = internal.FormatHashBlake2b256
	FormatHashSha256                   = internal.FormatHashSha256
	FormatOrEmptyOnNull                = internal.FormatOrEmptyOnNull
	GetDigestTypeForSigType            = internal.GetDigestTypeForSigType
	GetFormatHashOrError               = internal.GetFormatHashOrError
	GetFormatOrError                   = internal.GetFormatOrError
	GetFormatSecOrError                = internal.GetFormatSecOrError
	GetId                              = internal.GetId
	GetMotherSigTypeForSigType         = internal.GetMotherSigTypeForSigType
	GetPurpose                         = internal.GetPurpose
	IsErrEcdsaP256SSHAgentNotConnected = internal.IsErrEcdsaP256SSHAgentNotConnected
	IsErrEd25519SSHAgentNotConnected   = internal.IsErrEd25519SSHAgentNotConnected
	IsErrNull                          = internal.IsErrNull
	IsNull                             = internal.IsNull
	MakeErrEmptyType                   = internal.MakeErrEmptyType
	MakeErrNotEqualBytes               = internal.MakeErrNotEqualBytes
	MakeErrWrongHasher                 = internal.MakeErrWrongHasher
	MakeErrWrongType                   = internal.MakeErrWrongType
	NonceGenerate                      = internal.NonceGenerate
	NonceGenerate32                    = internal.NonceGenerate32
	PivyEcdhP256GetIOWrapper           = internal.PivyEcdhP256GetIOWrapper
	ReadFrom                           = internal.ReadFrom
	RegisterEcdsaP256SSHFormat         = internal.RegisterEcdsaP256SSHFormat
	RegisterSSHEd25519Format           = internal.RegisterSSHEd25519Format
	SetDigester                        = internal.SetDigester
	SetFromPath                        = internal.SetFromPath
	SetHexBytes                        = internal.SetHexBytes
	SetHexStringFromAbsolutePath       = internal.SetHexStringFromAbsolutePath
	SetHexStringFromRelPath            = internal.SetHexStringFromRelPath
	SetMarklIdWithFormatBlech32        = internal.SetMarklIdWithFormatBlech32
	SetMaybeSha256                     = internal.SetMaybeSha256
)

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func LockEquals[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](left domaininterfaces.Lock[KEY, KEY_PTR], right domaininterfaces.Lock[KEY, KEY_PTR]) bool {
	return internal.LockEquals[KEY, KEY_PTR](left, right)
}
func MakeErrLength[INTEGER constraints.Integer](expected INTEGER, actual INTEGER) error {
	return internal.MakeErrLength[INTEGER](expected, actual)
}
func MakeLock[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]]() internal.Lock[KEY, KEY_PTR] {
	return internal.MakeLock[KEY, KEY_PTR]()
}
func MakeLockWith[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](key KEY, value domaininterfaces.MarklId) internal.Lock[KEY, KEY_PTR] {
	return internal.MakeLockWith[KEY, KEY_PTR](key, value)
}

const (
	FormatIdAgeX25519Pub              = internal.FormatIdAgeX25519Pub
	FormatIdAgeX25519Sec              = internal.FormatIdAgeX25519Sec
	FormatIdEcdsaP256Pub              = internal.FormatIdEcdsaP256Pub
	FormatIdEcdsaP256SSH              = internal.FormatIdEcdsaP256SSH
	FormatIdEcdsaP256Sig              = internal.FormatIdEcdsaP256Sig
	FormatIdEd25519Pub                = internal.FormatIdEd25519Pub
	FormatIdEd25519SSH                = internal.FormatIdEd25519SSH
	FormatIdEd25519Sec                = internal.FormatIdEd25519Sec
	FormatIdEd25519Sig                = internal.FormatIdEd25519Sig
	FormatIdHashBlake2b256            = internal.FormatIdHashBlake2b256
	FormatIdHashSha256                = internal.FormatIdHashSha256
	FormatIdNonceSec                  = internal.FormatIdNonceSec
	FormatIdPivyEcdhP256Pub           = internal.FormatIdPivyEcdhP256Pub
	IdFormatBlech32                   = internal.IdFormatBlech32
	IdFormatDefault                   = internal.IdFormatDefault
	IdFormatHex                       = internal.IdFormatHex
	PurposeBlobDigestV1               = internal.PurposeBlobDigestV1
	PurposeMadderPrivateKeyV0         = internal.PurposeMadderPrivateKeyV0
	PurposeMadderPrivateKeyV1         = internal.PurposeMadderPrivateKeyV1
	PurposeMadderPubKeyV1             = internal.PurposeMadderPubKeyV1
	PurposeObjectDigestV1             = internal.PurposeObjectDigestV1
	PurposeObjectDigestV2             = internal.PurposeObjectDigestV2
	PurposeObjectMotherSigV1          = internal.PurposeObjectMotherSigV1
	PurposeObjectMotherSigV2          = internal.PurposeObjectMotherSigV2
	PurposeObjectSigV0                = internal.PurposeObjectSigV0
	PurposeObjectSigV1                = internal.PurposeObjectSigV1
	PurposeObjectSigV2                = internal.PurposeObjectSigV2
	PurposeRepoPrivateKeyV1           = internal.PurposeRepoPrivateKeyV1
	PurposeRepoPubKeyV1               = internal.PurposeRepoPubKeyV1
	PurposeRequestAuthChallengeV1     = internal.PurposeRequestAuthChallengeV1
	PurposeRequestAuthResponseV1      = internal.PurposeRequestAuthResponseV1
	PurposeRequestRepoSigV1           = internal.PurposeRequestRepoSigV1
	PurposeTypeBlobDigest             = internal.PurposeTypeBlobDigest
	PurposeTypeObjectDigest           = internal.PurposeTypeObjectDigest
	PurposeTypeObjectMotherSig        = internal.PurposeTypeObjectMotherSig
	PurposeTypeObjectSig              = internal.PurposeTypeObjectSig
	PurposeTypePrivateKey             = internal.PurposeTypePrivateKey
	PurposeTypePubKey                 = internal.PurposeTypePubKey
	PurposeTypeRepoPubKey             = internal.PurposeTypeRepoPubKey
	PurposeTypeRequestAuth            = internal.PurposeTypeRequestAuth
	PurposeTypeUnknown                = internal.PurposeTypeUnknown
	PurposeV5MetadataDigestWithoutTai = internal.PurposeV5MetadataDigestWithoutTai
)
