// Code generated by dagnabit (0.4.1+400e71c); DO NOT EDIT.

package markl

import (
	internal "github.com/amarbel-llc/madder/go/internal/bravo/markl"
	domaininterfaces "github.com/amarbel-llc/madder/go/pkgs/domain_interfaces"
	interfaces "github.com/amarbel-llc/purse-first/libs/dewey/pkgs/interfaces"
	constraints "golang.org/x/exp/constraints"
)

type (
	DiscoveredKey                  = internal.DiscoveredKey
	ErrFormatOperationNotSupported = internal.ErrFormatOperationNotSupported
	ErrIsNull                      = internal.ErrIsNull
)

// ErrLegacyCombinedHRPWireForm signals that a markl-id wire string
// failed checksum verification under the canonical split-HRP rule
// (RFC 0002 §3.3) but verifies under the legacy combined-HRP form
// (RFC 0002 §9.1) where the entire `<purpose>@<format>` string was
// used as the blech32 HRP.
//
// The combined-HRP form shipped briefly between commits `8dc78c7`
// and the #159 revert (`fd53684`); see madder#167 for the broader
// migration story. UnmarshalText returns this in place of the bare
// blech32 ErrInvalidChecksum so callers can distinguish a legacy
// pre-v0.3.16 file from genuine corruption.
//
// Recovery — two shapes, pick one:
//
//  1. Programmatic: build a fresh markl.Id and re-marshal —
//
//     var id markl.Id
//     _ = id.SetPurposeId(legacy.Purpose)
//     _ = id.SetMarklId(legacy.FormatId, legacy.Data)
//     canonical, _ := id.MarshalText()
//
//  2. Splice: the legacy and canonical bodies differ only in the
//     last 6 chars (the checksum). Replace them with
//     SplitHRPChecksum:
//
//     body := legacy.Raw // (or just the post-`@` section)
//     canonical := body[:len(body)-6] + legacy.SplitHRPChecksum
//
// Sensitivity (#169 coupling): for `*_sec` formats, Data is the
// secret. Error() MUST NOT render Data; Raw rendering will be
// redacted when #169 ships. SplitHRPChecksum is derived public
// material and is safe to render unredacted.
type (
	ErrLegacyCombinedHRPWireForm = internal.ErrLegacyCombinedHRPWireForm
	ErrNotEqual                  = internal.ErrNotEqual
	ErrNotEqualBytes             = internal.ErrNotEqualBytes
	ErrUnsupportedIdFormat       = internal.ErrUnsupportedIdFormat
	Format                       = internal.Format
	FormatHash                   = internal.FormatHash
	FormatId                     = internal.FormatId
	FormatPub                    = internal.FormatPub
	FormatSec                    = internal.FormatSec
	FuncFormatPubVerify          = internal.FuncFormatPubVerify
)

// TODO switch to accepting bytes?
type (
	FuncFormatSecGenerate                                                              = internal.FuncFormatSecGenerate
	FuncFormatSecGetIOWrapper                                                          = internal.FuncFormatSecGetIOWrapper
	FuncFormatSecGetPublicKey                                                          = internal.FuncFormatSecGetPublicKey
	FuncFormatSecSign                                                                  = internal.FuncFormatSecSign
	Hash                                                                               = internal.Hash
	Id                                                                                 = internal.Id
	IdBinaryDecodingFormatTypeData                                                     = internal.IdBinaryDecodingFormatTypeData
	IdBinaryDecodingTypeData                                                           = internal.IdBinaryDecodingTypeData
	IdBinaryEncodingFormatTypeData                                                     = internal.IdBinaryEncodingFormatTypeData
	IdBinaryEncodingTypeData                                                           = internal.IdBinaryEncodingTypeData
	IdBroken                                                                           = internal.IdBroken
	IdFormat                                                                           = internal.IdFormat
	Lock[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]]                       = internal.Lock[KEY, KEY_PTR]
	LockBinaryMarshaler[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]]        = internal.LockBinaryMarshaler[KEY, KEY_PTR]
	MutableLockBinaryMarshaler[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]] = internal.MutableLockBinaryMarshaler[KEY, KEY_PTR]
	Purpose                                                                            = internal.Purpose
	PurposeType                                                                        = internal.PurposeType
)

// RegisterPurposeOpts is the public registration shape for purposes.
//
// Related is a free-form role → purposeId map (see ADR 0006). Values are
// validated lazily: lookups via Purpose.GetRelated succeed for any registered
// role, and a downstream caller passing the result to GetPurpose is what
// surfaces typos.
type (
	RegisterPurposeOpts = internal.RegisterPurposeOpts
	Slice               = internal.Slice
)

var (
	AgeX25519Generate     = internal.AgeX25519Generate
	AgeX25519GetIOWrapper = internal.AgeX25519GetIOWrapper
)

// TODO verify if this is correct
var (
	AgeX25519GetPublicKey        = internal.AgeX25519GetPublicKey
	AssertEqual                  = internal.AssertEqual
	AssertIdIsNotNull            = internal.AssertIdIsNotNull
	AssertIdIsNotNullWithPurpose = internal.AssertIdIsNotNullWithPurpose
	AssertIdIsNull               = internal.AssertIdIsNull
	Clone                        = internal.Clone
	CompareToReader              = internal.CompareToReader
	CompareToReaderAt            = internal.CompareToReaderAt
	ConnectEcdsaP256AgentSigner  = internal.ConnectEcdsaP256AgentSigner
	ConnectSSHAgentSigner        = internal.ConnectSSHAgentSigner
)

// DiscoverAgentECDHKeysVerbose discovers ECDSA P-256 keys from the agent
// whose unix socket path is held in the named environment variable (e.g.
// PIGGY_AUTH_SOCK to target piggy-agent instead of the agent fronted by
// SSH_AUTH_SOCK).
var DiscoverAgentECDHKeysVerbose = internal.DiscoverAgentECDHKeysVerbose

// DiscoverAgentEd25519KeysVerbose discovers Ed25519 keys from the agent
// whose unix socket path is held in the named environment variable (e.g.
// PIGGY_AUTH_SOCK to target piggy-agent instead of the agent fronted by
// SSH_AUTH_SOCK).
var (
	DiscoverAgentEd25519KeysVerbose    = internal.DiscoverAgentEd25519KeysVerbose
	DiscoverPivyAgentECDHKeys          = internal.DiscoverPivyAgentECDHKeys
	DiscoverPivyAgentECDHKeysVerbose   = internal.DiscoverPivyAgentECDHKeysVerbose
	DiscoverSSHAgentECDHKeys           = internal.DiscoverSSHAgentECDHKeys
	DiscoverSSHAgentECDHKeysVerbose    = internal.DiscoverSSHAgentECDHKeysVerbose
	DiscoverSSHAgentEd25519Keys        = internal.DiscoverSSHAgentEd25519Keys
	DiscoverSSHAgentEd25519KeysVerbose = internal.DiscoverSSHAgentEd25519KeysVerbose
	EcdsaP256Verify                    = internal.EcdsaP256Verify
	Ed25519GeneratePrivateKey          = internal.Ed25519GeneratePrivateKey
	Ed25519GetPublicKey                = internal.Ed25519GetPublicKey
	Ed25519Sign                        = internal.Ed25519Sign
	Ed25519Verify                      = internal.Ed25519Verify
	Equals                             = internal.Equals
	EqualsReader                       = internal.EqualsReader
	ErrEcdsaP256SSHAgentNotConnected   = internal.ErrEcdsaP256SSHAgentNotConnected
	ErrEd25519SSHAgentNotConnected     = internal.ErrEd25519SSHAgentNotConnected
)

// ErrEd25519SeedNotPrivateKey signals that Ed25519GetPublicKey received a
// 32-byte value. RFC 8032 uses a 32-byte seed as the canonical private key,
// but Go's crypto/ed25519 uses a 64-byte representation (seed ‖ pubkey) —
// and so does madder (see FormatSec{Id: FormatIdEd25519Sec, Size:
// ed25519.PrivateKeySize}). Callers with a seed must explicitly expand it
// via ed25519.NewKeyFromSeed before presenting it as a private-key MarklId.
var (
	ErrEd25519SeedNotPrivateKey = internal.ErrEd25519SeedNotPrivateKey
	ErrEmptyType                = internal.ErrEmptyType
)

// ErrNilFormat signals that an Id mutation requires a non-nil MarklFormat
// but received nil. Raised via panic from resetDataForFormat — the sole
// mutation primitive — so any in-package bug that tries to populate an Id
// without first supplying a format surfaces at the point of mutation.
var ErrNilFormat = internal.ErrNilFormat

// Creates a human-readable string representation of a digest.
// TODO add type information
var (
	FormatBytesAsHex     = internal.FormatBytesAsHex
	FormatHashBlake2b256 = internal.FormatHashBlake2b256
)

// TODO remove unnecessary references
var (
	FormatHashSha256        = internal.FormatHashSha256
	FormatOrEmptyOnNull     = internal.FormatOrEmptyOnNull
	GetDigestTypeForSigType = internal.GetDigestTypeForSigType
	GetFormatHashOrError    = internal.GetFormatHashOrError
	GetFormatOrError        = internal.GetFormatOrError
)

// move to Id
var (
	GetFormatSecOrError                = internal.GetFormatSecOrError
	GetId                              = internal.GetId
	GetMotherSigTypeForSigType         = internal.GetMotherSigTypeForSigType
	GetPurpose                         = internal.GetPurpose
	IsErrEcdsaP256SSHAgentNotConnected = internal.IsErrEcdsaP256SSHAgentNotConnected
	IsErrEd25519SSHAgentNotConnected   = internal.IsErrEd25519SSHAgentNotConnected
	IsErrNull                          = internal.IsErrNull
	IsNull                             = internal.IsNull
	MakeErrEmptyType                   = internal.MakeErrEmptyType
	MakeErrNotEqualBytes               = internal.MakeErrNotEqualBytes
	MakeErrWrongHasher                 = internal.MakeErrWrongHasher
	MakeErrWrongType                   = internal.MakeErrWrongType
	NonceGenerate                      = internal.NonceGenerate
	NonceGenerate32                    = internal.NonceGenerate32
	PivyEcdhP256GetIOWrapper           = internal.PivyEcdhP256GetIOWrapper
	ReadFrom                           = internal.ReadFrom
	RegisterEcdsaP256SSHFormat         = internal.RegisterEcdsaP256SSHFormat
)

// RegisterFormat installs a MarklFormat in the package-global registry.
// Panics on nil format, empty format id, or duplicate registration. Returns
// the registered format value so callers may keep a typed handle.
var RegisterFormat = internal.RegisterFormat

// RegisterPurpose installs a Purpose in the package-global registry. Panics
// if Id is already registered, or if FormatIds contains a duplicate. Returns
// the constructed Purpose so callers may keep a typed handle.
var RegisterPurpose = internal.RegisterPurpose

// RegisterPurposeIdAlias installs an alias from a purposeId-shaped string
// to a formatId. Panics on duplicate alias to match the registry's
// stability convention. The aliased formatId is not validated at
// registration time — GetFormatOrError surfaces an unknown target via its
// usual "unknown format id" error.
var (
	RegisterPurposeIdAlias       = internal.RegisterPurposeIdAlias
	RegisterSSHEd25519Format     = internal.RegisterSSHEd25519Format
	SetDigester                  = internal.SetDigester
	SetFromPath                  = internal.SetFromPath
	SetHexBytes                  = internal.SetHexBytes
	SetHexStringFromAbsolutePath = internal.SetHexStringFromAbsolutePath
	SetHexStringFromRelPath      = internal.SetHexStringFromRelPath
	SetMarklIdWithFormatBlech32  = internal.SetMarklIdWithFormatBlech32
)

// TODO remove
var SetMaybeSha256 = internal.SetMaybeSha256

// Generic function wrappers — Go does not support assigning
// generic functions to variables without instantiation.
// See https://github.com/golang/go/issues/52654
func LockEquals[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](left domaininterfaces.Lock[KEY, KEY_PTR], right domaininterfaces.Lock[KEY, KEY_PTR]) bool {
	return internal.LockEquals[KEY, KEY_PTR](left, right)
}

func MakeErrLength[INTEGER constraints.Integer](expected INTEGER, actual INTEGER) error {
	return internal.MakeErrLength[INTEGER](expected, actual)
}

func MakeLock[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]]() internal.Lock[KEY, KEY_PTR] {
	return internal.MakeLock[KEY, KEY_PTR]()
}

func MakeLockCoder[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](lock domaininterfaces.Lock[KEY, KEY_PTR], requireValue bool) internal.LockBinaryMarshaler[KEY, KEY_PTR] {
	return internal.MakeLockCoder[KEY, KEY_PTR](lock, requireValue)
}

func MakeLockCoderValueNotRequired[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](lock domaininterfaces.Lock[KEY, KEY_PTR]) internal.LockBinaryMarshaler[KEY, KEY_PTR] {
	return internal.MakeLockCoderValueNotRequired[KEY, KEY_PTR](lock)
}

func MakeLockWith[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](key KEY, value domaininterfaces.MarklId) internal.Lock[KEY, KEY_PTR] {
	return internal.MakeLockWith[KEY, KEY_PTR](key, value)
}

func MakeMutableLockCoder[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](lock domaininterfaces.LockMutable[KEY, KEY_PTR], requireValue bool) internal.MutableLockBinaryMarshaler[KEY, KEY_PTR] {
	return internal.MakeMutableLockCoder[KEY, KEY_PTR](lock, requireValue)
}

func MakeMutableLockCoderValueNotRequired[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](lock domaininterfaces.LockMutable[KEY, KEY_PTR]) internal.MutableLockBinaryMarshaler[KEY, KEY_PTR] {
	return internal.MakeMutableLockCoderValueNotRequired[KEY, KEY_PTR](lock)
}

func MakeMutableLockCoderValueRequired[KEY interfaces.Value, KEY_PTR interfaces.ValuePtr[KEY]](lock domaininterfaces.LockMutable[KEY, KEY_PTR]) internal.MutableLockBinaryMarshaler[KEY, KEY_PTR] {
	return internal.MakeMutableLockCoderValueRequired[KEY, KEY_PTR](lock)
}

const (
	FormatIdAgeX25519Pub = internal.FormatIdAgeX25519Pub
	FormatIdAgeX25519Sec = internal.FormatIdAgeX25519Sec
	FormatIdEcdsaP256Pub = internal.FormatIdEcdsaP256Pub
	FormatIdEcdsaP256SSH = internal.FormatIdEcdsaP256SSH
	FormatIdEcdsaP256Sig = internal.FormatIdEcdsaP256Sig
)

// keep sorted
const (
	FormatIdEd25519Pub      = internal.FormatIdEd25519Pub
	FormatIdEd25519SSH      = internal.FormatIdEd25519SSH
	FormatIdEd25519Sec      = internal.FormatIdEd25519Sec
	FormatIdEd25519Sig      = internal.FormatIdEd25519Sig
	FormatIdHashBlake2b256  = internal.FormatIdHashBlake2b256
	FormatIdHashSha256      = internal.FormatIdHashSha256
	FormatIdNonceSec        = internal.FormatIdNonceSec
	FormatIdPivyEcdhP256Pub = internal.FormatIdPivyEcdhP256Pub
)

// SEC1-compressed P-256 public key (33 bytes), surfaced via the SSH
// agent from a PIV authentication/signature slot (9A/9C/9E). Byte
// shape is identical to ecdsa_p256_pub; the distinct format id lets a
// purpose distinguish piggy PIV SSH-auth keys from recipient pubkeys
// of the same shape. Owned jointly with amarbel-llc/piggy (mirrored
// in its piggy-markl crate). See RFC 0002 §5.
const (
	FormatIdSshEcdsaNistp256Pub = internal.FormatIdSshEcdsaNistp256Pub
	IdFormatBlech32             = internal.IdFormatBlech32
	IdFormatDefault             = internal.IdFormatDefault
	IdFormatHex                 = internal.IdFormatHex
)

// Blob Digests
const PurposeBlobDigestV1 = internal.PurposeBlobDigestV1

// Blob-Store-Config Digests
const (
	PurposeBlobStoreConfigDigestV1 = internal.PurposeBlobStoreConfigDigestV1
	PurposeMadderPrivateKeyV0      = internal.PurposeMadderPrivateKeyV0
	PurposeMadderPrivateKeyV1      = internal.PurposeMadderPrivateKeyV1
	PurposeMadderPubKeyV1          = internal.PurposeMadderPubKeyV1
)

// Object Digests
const (
	PurposeObjectDigestV1 = internal.PurposeObjectDigestV1
	PurposeObjectDigestV2 = internal.PurposeObjectDigestV2
)

// Object Mother Sigs
const (
	PurposeObjectMotherSigV1 = internal.PurposeObjectMotherSigV1
	PurposeObjectMotherSigV2 = internal.PurposeObjectMotherSigV2
)

// Object Sigs
const (
	PurposeObjectSigV0 = internal.PurposeObjectSigV0
	PurposeObjectSigV1 = internal.PurposeObjectSigV1
	PurposeObjectSigV2 = internal.PurposeObjectSigV2
)

// Papi document signature (jointly owned with amarbel-llc/papi; see
// RFC 0002 §6.1). A slot-9A ecdsa-sha2-nistp256 SSH signature over a
// PAPI document's canonicalized (JCS) bytes, carried as the 64-byte
// r‖s payload once SSH-wire framing is stripped. Mirrored in the
// piggy-markl crate for the producer side (`piggy papi sign`).
const PurposePapiDocSigV1 = internal.PurposePapiDocSigV1

// Piggy keys (jointly owned with amarbel-llc/piggy; see RFC 0002 §6.1
// and the piggy-markl crate). The piggy-piv_* purposes carry a PIV
// slot's SSH-suitable public key; piggy-recipient-v1 carries an
// encryption recipient pubkey (PIV slot 9D or an age recipient).
// keep sorted
const (
	PurposePiggyPivAuthV1     = internal.PurposePiggyPivAuthV1
	PurposePiggyPivCardAuthV1 = internal.PurposePiggyPivCardAuthV1
	PurposePiggyPivSigV1      = internal.PurposePiggyPivSigV1
	PurposePiggyRecipientV1   = internal.PurposePiggyRecipientV1
)

// PrivateKeys
const PurposeRepoPrivateKeyV1 = internal.PurposeRepoPrivateKeyV1

// PubKeys
const (
	PurposeRepoPubKeyV1           = internal.PurposeRepoPubKeyV1
	PurposeRequestAuthChallengeV1 = internal.PurposeRequestAuthChallengeV1
)

// Request Auth
const (
	PurposeRequestAuthResponseV1      = internal.PurposeRequestAuthResponseV1
	PurposeRequestRepoSigV1           = internal.PurposeRequestRepoSigV1
	PurposeTypeBlobDigest             = internal.PurposeTypeBlobDigest
	PurposeTypeObjectDigest           = internal.PurposeTypeObjectDigest
	PurposeTypeObjectMotherSig        = internal.PurposeTypeObjectMotherSig
	PurposeTypeObjectSig              = internal.PurposeTypeObjectSig
	PurposeTypePrivateKey             = internal.PurposeTypePrivateKey
	PurposeTypePubKey                 = internal.PurposeTypePubKey
	PurposeTypeRepoPubKey             = internal.PurposeTypeRepoPubKey
	PurposeTypeRequestAuth            = internal.PurposeTypeRequestAuth
	PurposeTypeUnknown                = internal.PurposeTypeUnknown
	PurposeV5MetadataDigestWithoutTai = internal.PurposeV5MetadataDigestWithoutTai
	RelatedRoleDigest                 = internal.RelatedRoleDigest
	RelatedRoleMotherSig              = internal.RelatedRoleMotherSig
	RelatedRolePublicKey              = internal.RelatedRolePublicKey
)
