// Code generated by dagnabit; DO NOT EDIT.

package directory_layout

import internal "github.com/amarbel-llc/madder/go/internal/bravo/directory_layout"

type (
	BlobStore     = internal.BlobStore
	BlobStorePath = internal.BlobStorePath
	Common        = internal.Common
	XDG           = internal.XDG
)

var (
	CloneBlobStoreWithXDG         = internal.CloneBlobStoreWithXDG
	DirBlobStore                  = internal.DirBlobStore
	GetBlobStoreConfigPaths       = internal.GetBlobStoreConfigPaths
	GetBlobStorePath              = internal.GetBlobStorePath
	GetBlobStorePathForCustomPath = internal.GetBlobStorePathForCustomPath
	GetDefaultBlobStore           = internal.GetDefaultBlobStore
	MakeBlobStore                 = internal.MakeBlobStore
	MakeBlobStoreCache            = internal.MakeBlobStoreCache
	MakeBlobStorePath             = internal.MakeBlobStorePath
	PathBlobStore                 = internal.PathBlobStore
)

const (
	FileNameBlobStoreConfig = internal.FileNameBlobStoreConfig
)
