// Code generated by dagnabit (0.4.1+dirty); DO NOT EDIT.

package directory_layout

import internal "code.linenisgreat.com/madder/go/internal/bravo/directory_layout"

type (
	BlobStore     = internal.BlobStore
	BlobStorePath = internal.BlobStorePath
	Common        = internal.Common
	XDG           = internal.XDG
)

var (
	CloneBlobStoreWithXDG = internal.CloneBlobStoreWithXDG
	DirBlobStore          = internal.DirBlobStore
)

// FindAllCwdOverridePaths walks up from cwd and returns every ancestor
// that contains `.<utilityName>/` (file or directory), deepest-first.
// Honors `<UTILITYNAME>_CEILING_DIRECTORIES` (parsed via dewey's
// xdg.ParseCeilingDirectories + xdg.IsAboveCeiling).
//
// Multi-match counterpart of dewey's xdg.getCwdXDGOverridePath, which
// returns only the deepest match. Loop shape mirrors the post-#75
// dewey: the ceiling dir is the LAST dir checked, not the first
// excluded — match git's GIT_CEILING_DIRECTORIES semantics. See #145
// and amarbel-llc/purse-first#75.
//
// xdg.IsAboveCeiling symlink-resolves both dir and each ceiling before
// comparison (amarbel-llc/purse-first#80), so this wrapper no longer
// needs to canonicalize either side.
var (
	FindAllCwdOverridePaths       = internal.FindAllCwdOverridePaths
	GetBlobStoreConfigPaths       = internal.GetBlobStoreConfigPaths
	GetBlobStorePath              = internal.GetBlobStorePath
	GetBlobStorePathForCustomPath = internal.GetBlobStorePathForCustomPath
	GetDefaultBlobStore           = internal.GetDefaultBlobStore
	GetLegacyBlobStoreConfigPaths = internal.GetLegacyBlobStoreConfigPaths
	MakeBlobStore                 = internal.MakeBlobStore
	MakeBlobStoreCache            = internal.MakeBlobStoreCache
	MakeBlobStorePath             = internal.MakeBlobStorePath
)

// MakeBlobStoreSystem builds the XDG-system (`//name`) layout (madder#230).
// The xdg must already be rooted at the system path (env_dir.rootAtSystem);
// the layout reports LocationTypeXDGSystem so init/discovery accept `//name`
// ids against it.
var (
	MakeBlobStoreSystem = internal.MakeBlobStoreSystem
	PathBlobStore       = internal.PathBlobStore
)

// ResolveNthAncestorMatch walks up from cwd via FindAllCwdOverridePaths
// (deepest-first, ceiling-respecting ancestors carrying `.<utilityName>/`)
// and returns the depth-th ancestor for which matches reports true: depth 0
// is the deepest match, depth 1 the next match up, etc. This is the
// store-aware, depth-ranked OPERATE-path resolver (dodder#281) — the
// counterpart to env_dir.MakeDefaultAndInitialize's literal Nth-parent
// walk-up (madder#153), which is the INIT-path resolver. Operate stays
// nearest-ancestor so a command can run from a child directory below the
// addressed root.
//
// It ERRORS (does not clamp) when fewer than depth+1 matching ancestors
// exist, mirroring scoped_id's strict posture and #153's overflow policy.
//
// matches is the caller's name/identity check for a candidate ancestor:
// madder would pass "this ancestor hosts a blob store named <name>"; dodder
// passes its own ".dodder repo named <name>" check. Injecting it keeps this
// single deepest-first walk utility-agnostic (it never needs to know either
// layout's store/repo model) while reusing the discovery walk rather than
// duplicating it. matches must be non-nil.
var ResolveNthAncestorMatch = internal.ResolveNthAncestorMatch

const FileNameBlobStoreConfig = internal.FileNameBlobStoreConfig
