// Code generated by tommy; DO NOT EDIT.

package options_print

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V0Document struct {
	data     V0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV0(input []byte) (*V0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "print-include-description":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintIncludeDescription = &v
				d.consumed["print-include-description"] = true
			}
		case "print-time":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintTime = &v
				d.consumed["print-time"] = true
			}
		case "print-etiketten-always":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintTagsAlways = &v
				d.consumed["print-etiketten-always"] = true
			}
		case "print-empty-shas":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintEmptyShas = &v
				d.consumed["print-empty-shas"] = true
			}
		case "print-include-typen":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintIncludeTypes = &v
				d.consumed["print-include-typen"] = true
			}
		case "print-matched-archiviert":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintMatchedDormant = &v
				d.consumed["print-matched-archiviert"] = true
			}
		case "print-shas":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintShas = &v
				d.consumed["print-shas"] = true
			}
		case "print-flush":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintFlush = &v
				d.consumed["print-flush"] = true
			}
		case "print-unchanged":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintUnchanged = &v
				d.consumed["print-unchanged"] = true
			}
		case "print-colors":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintColors = &v
				d.consumed["print-colors"] = true
			}
		case "print-bestandsaufnahme":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintInventoryLists = &v
				d.consumed["print-bestandsaufnahme"] = true
			}
		}
	}
	{
		var _ftAbbreviations *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "abbreviations" {
				_ftAbbreviations = _ch
				break
			}
		}
		if _ftAbbreviations != nil {
			d.consumed["abbreviations"] = true
			abbreviationsVal := &abbreviationsV0{}
			for _, _kv := range _ftAbbreviations.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "hinweisen":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						d.consumed["abbreviations.hinweisen"] = true
					}
				case "shas":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.Shas = &v
						d.consumed["abbreviations.shas"] = true
					}
				}
			}
			d.data.Abbreviations = abbreviationsVal
		} else {
			abbreviationsVal := &abbreviationsV0{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "hinweisen":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						_found = true
						d.consumed["hinweisen"] = true
					}
				case "shas":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.Shas = &v
						_found = true
						d.consumed["shas"] = true
					}
				}
			}
			if _found {
				d.data.Abbreviations = abbreviationsVal
			}
		}
	}
	return d, nil
}
func (d *V0Document) Data() *V0 {
	return &d.data
}
func (d *V0Document) Encode() ([]byte, error) {
	if d.data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "abbreviations")
		if d.data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "hinweisen", *d.data.Abbreviations.ZettelIds); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Abbreviations.Shas != nil {
			if err := cst.SetAny(tableNode, "shas", *d.data.Abbreviations.Shas); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.PrintIncludeDescription != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-description", *d.data.PrintIncludeDescription); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTime != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-time", *d.data.PrintTime); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTagsAlways != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-etiketten-always", *d.data.PrintTagsAlways); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintEmptyShas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-empty-shas", *d.data.PrintEmptyShas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintIncludeTypes != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-typen", *d.data.PrintIncludeTypes); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintMatchedDormant != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-matched-archiviert", *d.data.PrintMatchedDormant); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintShas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-shas", *d.data.PrintShas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintFlush != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-flush", *d.data.PrintFlush); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintUnchanged != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-unchanged", *d.data.PrintUnchanged); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintColors != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-colors", *d.data.PrintColors); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintInventoryLists != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-bestandsaufnahme", *d.data.PrintInventoryLists); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *V0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *V0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *V0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *V0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *V0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeV0Into(data *V0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "print-include-description":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintIncludeDescription = &v
				consumed[keyPrefix+"print-include-description"] = true
			}
		case "print-time":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintTime = &v
				consumed[keyPrefix+"print-time"] = true
			}
		case "print-etiketten-always":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintTagsAlways = &v
				consumed[keyPrefix+"print-etiketten-always"] = true
			}
		case "print-empty-shas":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintEmptyShas = &v
				consumed[keyPrefix+"print-empty-shas"] = true
			}
		case "print-include-typen":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintIncludeTypes = &v
				consumed[keyPrefix+"print-include-typen"] = true
			}
		case "print-matched-archiviert":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintMatchedDormant = &v
				consumed[keyPrefix+"print-matched-archiviert"] = true
			}
		case "print-shas":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintShas = &v
				consumed[keyPrefix+"print-shas"] = true
			}
		case "print-flush":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintFlush = &v
				consumed[keyPrefix+"print-flush"] = true
			}
		case "print-unchanged":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintUnchanged = &v
				consumed[keyPrefix+"print-unchanged"] = true
			}
		case "print-colors":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintColors = &v
				consumed[keyPrefix+"print-colors"] = true
			}
		case "print-bestandsaufnahme":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintInventoryLists = &v
				consumed[keyPrefix+"print-bestandsaufnahme"] = true
			}
		}
	}
	{
		var _ftAbbreviations *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"abbreviations" {
				_ftAbbreviations = _ch
				break
			}
		}
		if _ftAbbreviations != nil {
			consumed[keyPrefix+"abbreviations"] = true
			abbreviationsVal := &abbreviationsV0{}
			for _, _kv := range _ftAbbreviations.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "hinweisen":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						consumed[keyPrefix+"abbreviations.hinweisen"] = true
					}
				case "shas":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.Shas = &v
						consumed[keyPrefix+"abbreviations.shas"] = true
					}
				}
			}
			data.Abbreviations = abbreviationsVal
		} else {
			abbreviationsVal := &abbreviationsV0{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "hinweisen":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						_found = true
						consumed["hinweisen"] = true
					}
				case "shas":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.Shas = &v
						_found = true
						consumed["shas"] = true
					}
				}
			}
			if _found {
				data.Abbreviations = abbreviationsVal
			}
		}
	}
	return nil
}
func EncodeV0From(data *V0, doc *document.Document, container *cst.Node) error {
	if data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "abbreviations")
		if data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "hinweisen", *data.Abbreviations.ZettelIds); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Abbreviations.Shas != nil {
			if err := cst.SetAny(tableNode, "shas", *data.Abbreviations.Shas); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.PrintIncludeDescription != nil {
		if err := cst.SetAny(container, "print-include-description", *data.PrintIncludeDescription); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTime != nil {
		if err := cst.SetAny(container, "print-time", *data.PrintTime); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTagsAlways != nil {
		if err := cst.SetAny(container, "print-etiketten-always", *data.PrintTagsAlways); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintEmptyShas != nil {
		if err := cst.SetAny(container, "print-empty-shas", *data.PrintEmptyShas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintIncludeTypes != nil {
		if err := cst.SetAny(container, "print-include-typen", *data.PrintIncludeTypes); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintMatchedDormant != nil {
		if err := cst.SetAny(container, "print-matched-archiviert", *data.PrintMatchedDormant); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintShas != nil {
		if err := cst.SetAny(container, "print-shas", *data.PrintShas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintFlush != nil {
		if err := cst.SetAny(container, "print-flush", *data.PrintFlush); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintUnchanged != nil {
		if err := cst.SetAny(container, "print-unchanged", *data.PrintUnchanged); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintColors != nil {
		if err := cst.SetAny(container, "print-colors", *data.PrintColors); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintInventoryLists != nil {
		if err := cst.SetAny(container, "print-bestandsaufnahme", *data.PrintInventoryLists); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type abbreviationsV0Document struct {
	data     abbreviationsV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeabbreviationsV0(input []byte) (*abbreviationsV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &abbreviationsV0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "hinweisen":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.ZettelIds = &v
				d.consumed["hinweisen"] = true
			}
		case "shas":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.Shas = &v
				d.consumed["shas"] = true
			}
		}
	}
	return d, nil
}
func (d *abbreviationsV0Document) Data() *abbreviationsV0 {
	return &d.data
}
func (d *abbreviationsV0Document) Encode() ([]byte, error) {
	if d.data.ZettelIds != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "hinweisen", *d.data.ZettelIds); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Shas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "shas", *d.data.Shas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *abbreviationsV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *abbreviationsV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *abbreviationsV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *abbreviationsV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *abbreviationsV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeabbreviationsV0Into(data *abbreviationsV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "hinweisen":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.ZettelIds = &v
				consumed[keyPrefix+"hinweisen"] = true
			}
		case "shas":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.Shas = &v
				consumed[keyPrefix+"shas"] = true
			}
		}
	}
	return nil
}
func EncodeabbreviationsV0From(data *abbreviationsV0, doc *document.Document, container *cst.Node) error {
	if data.ZettelIds != nil {
		if err := cst.SetAny(container, "hinweisen", *data.ZettelIds); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Shas != nil {
		if err := cst.SetAny(container, "shas", *data.Shas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
