// Code generated by tommy; DO NOT EDIT.

package options_print

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V2Document struct {
	data     V2
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV2(input []byte) (*V2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V2Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "print-blob_digests":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintBlobDigests = &v
				d.consumed["print-blob_digests"] = true
			}
		case "print-colors":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintColors = &v
				d.consumed["print-colors"] = true
			}
		case "print-empty-blob_digests":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintEmptyBlobDigests = &v
				d.consumed["print-empty-blob_digests"] = true
			}
		case "print-flush":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintFlush = &v
				d.consumed["print-flush"] = true
			}
		case "print-include-description":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintIncludeDescription = &v
				d.consumed["print-include-description"] = true
			}
		case "print-include-types":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintIncludeTypes = &v
				d.consumed["print-include-types"] = true
			}
		case "print-inventory_lists":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintInventoryLists = &v
				d.consumed["print-inventory_lists"] = true
			}
		case "print-matched-dormant":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintMatchedDormant = &v
				d.consumed["print-matched-dormant"] = true
			}
		case "print-tags-always":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintTagsAlways = &v
				d.consumed["print-tags-always"] = true
			}
		case "print-time":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintTime = &v
				d.consumed["print-time"] = true
			}
		case "print-unchanged":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.PrintUnchanged = &v
				d.consumed["print-unchanged"] = true
			}
		}
	}
	{
		var _ftAbbreviations *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "abbreviations" {
				_ftAbbreviations = _ch
				break
			}
		}
		if _ftAbbreviations != nil {
			d.consumed["abbreviations"] = true
			abbreviationsVal := &abbreviationsV2{}
			for _, _kv := range _ftAbbreviations.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "zettel_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						d.consumed["abbreviations.zettel_ids"] = true
					}
				case "merkle_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.MarklIds = &v
						d.consumed["abbreviations.merkle_ids"] = true
					}
				}
			}
			d.data.Abbreviations = abbreviationsVal
		} else {
			abbreviationsVal := &abbreviationsV2{}
			_found := false
			for _, _kv := range d.cstDoc.Root().Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "zettel_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						_found = true
						d.consumed["zettel_ids"] = true
					}
				case "merkle_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.MarklIds = &v
						_found = true
						d.consumed["merkle_ids"] = true
					}
				}
			}
			if _found {
				d.data.Abbreviations = abbreviationsVal
			}
		}
	}
	return d, nil
}
func (d *V2Document) Data() *V2 {
	return &d.data
}
func (d *V2Document) Encode() ([]byte, error) {
	if d.data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "abbreviations")
		if d.data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "zettel_ids", *d.data.Abbreviations.ZettelIds); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Abbreviations.MarklIds != nil {
			if err := cst.SetAny(tableNode, "merkle_ids", *d.data.Abbreviations.MarklIds); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.PrintBlobDigests != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-blob_digests", *d.data.PrintBlobDigests); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintColors != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-colors", *d.data.PrintColors); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintEmptyBlobDigests != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-empty-blob_digests", *d.data.PrintEmptyBlobDigests); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintFlush != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-flush", *d.data.PrintFlush); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintIncludeDescription != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-description", *d.data.PrintIncludeDescription); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintIncludeTypes != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-types", *d.data.PrintIncludeTypes); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintInventoryLists != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-inventory_lists", *d.data.PrintInventoryLists); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintMatchedDormant != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-matched-dormant", *d.data.PrintMatchedDormant); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTagsAlways != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-tags-always", *d.data.PrintTagsAlways); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTime != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-time", *d.data.PrintTime); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintUnchanged != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-unchanged", *d.data.PrintUnchanged); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *V2Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *V2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *V2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *V2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *V2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeV2Into(data *V2, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "print-blob_digests":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintBlobDigests = &v
				consumed[keyPrefix+"print-blob_digests"] = true
			}
		case "print-colors":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintColors = &v
				consumed[keyPrefix+"print-colors"] = true
			}
		case "print-empty-blob_digests":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintEmptyBlobDigests = &v
				consumed[keyPrefix+"print-empty-blob_digests"] = true
			}
		case "print-flush":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintFlush = &v
				consumed[keyPrefix+"print-flush"] = true
			}
		case "print-include-description":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintIncludeDescription = &v
				consumed[keyPrefix+"print-include-description"] = true
			}
		case "print-include-types":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintIncludeTypes = &v
				consumed[keyPrefix+"print-include-types"] = true
			}
		case "print-inventory_lists":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintInventoryLists = &v
				consumed[keyPrefix+"print-inventory_lists"] = true
			}
		case "print-matched-dormant":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintMatchedDormant = &v
				consumed[keyPrefix+"print-matched-dormant"] = true
			}
		case "print-tags-always":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintTagsAlways = &v
				consumed[keyPrefix+"print-tags-always"] = true
			}
		case "print-time":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintTime = &v
				consumed[keyPrefix+"print-time"] = true
			}
		case "print-unchanged":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.PrintUnchanged = &v
				consumed[keyPrefix+"print-unchanged"] = true
			}
		}
	}
	{
		var _ftAbbreviations *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"abbreviations" {
				_ftAbbreviations = _ch
				break
			}
		}
		if _ftAbbreviations != nil {
			consumed[keyPrefix+"abbreviations"] = true
			abbreviationsVal := &abbreviationsV2{}
			for _, _kv := range _ftAbbreviations.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "zettel_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						consumed[keyPrefix+"abbreviations.zettel_ids"] = true
					}
				case "merkle_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.MarklIds = &v
						consumed[keyPrefix+"abbreviations.merkle_ids"] = true
					}
				}
			}
			data.Abbreviations = abbreviationsVal
		} else {
			abbreviationsVal := &abbreviationsV2{}
			_found := false
			for _, _kv := range container.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "zettel_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.ZettelIds = &v
						_found = true
						consumed["zettel_ids"] = true
					}
				case "merkle_ids":
					if v, ok := cst.ExtractBool(_kv); ok {
						abbreviationsVal.MarklIds = &v
						_found = true
						consumed["merkle_ids"] = true
					}
				}
			}
			if _found {
				data.Abbreviations = abbreviationsVal
			}
		}
	}
	return nil
}
func EncodeV2From(data *V2, doc *document.Document, container *cst.Node) error {
	if data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "abbreviations")
		if data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "zettel_ids", *data.Abbreviations.ZettelIds); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Abbreviations.MarklIds != nil {
			if err := cst.SetAny(tableNode, "merkle_ids", *data.Abbreviations.MarklIds); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.PrintBlobDigests != nil {
		if err := cst.SetAny(container, "print-blob_digests", *data.PrintBlobDigests); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintColors != nil {
		if err := cst.SetAny(container, "print-colors", *data.PrintColors); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintEmptyBlobDigests != nil {
		if err := cst.SetAny(container, "print-empty-blob_digests", *data.PrintEmptyBlobDigests); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintFlush != nil {
		if err := cst.SetAny(container, "print-flush", *data.PrintFlush); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintIncludeDescription != nil {
		if err := cst.SetAny(container, "print-include-description", *data.PrintIncludeDescription); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintIncludeTypes != nil {
		if err := cst.SetAny(container, "print-include-types", *data.PrintIncludeTypes); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintInventoryLists != nil {
		if err := cst.SetAny(container, "print-inventory_lists", *data.PrintInventoryLists); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintMatchedDormant != nil {
		if err := cst.SetAny(container, "print-matched-dormant", *data.PrintMatchedDormant); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTagsAlways != nil {
		if err := cst.SetAny(container, "print-tags-always", *data.PrintTagsAlways); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTime != nil {
		if err := cst.SetAny(container, "print-time", *data.PrintTime); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintUnchanged != nil {
		if err := cst.SetAny(container, "print-unchanged", *data.PrintUnchanged); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type abbreviationsV2Document struct {
	data     abbreviationsV2
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeabbreviationsV2(input []byte) (*abbreviationsV2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &abbreviationsV2Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "zettel_ids":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.ZettelIds = &v
				d.consumed["zettel_ids"] = true
			}
		case "merkle_ids":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.MarklIds = &v
				d.consumed["merkle_ids"] = true
			}
		}
	}
	return d, nil
}
func (d *abbreviationsV2Document) Data() *abbreviationsV2 {
	return &d.data
}
func (d *abbreviationsV2Document) Encode() ([]byte, error) {
	if d.data.ZettelIds != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "zettel_ids", *d.data.ZettelIds); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.MarklIds != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "merkle_ids", *d.data.MarklIds); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *abbreviationsV2Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *abbreviationsV2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *abbreviationsV2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *abbreviationsV2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *abbreviationsV2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeabbreviationsV2Into(data *abbreviationsV2, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "zettel_ids":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.ZettelIds = &v
				consumed[keyPrefix+"zettel_ids"] = true
			}
		case "merkle_ids":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.MarklIds = &v
				consumed[keyPrefix+"merkle_ids"] = true
			}
		}
	}
	return nil
}
func EncodeabbreviationsV2From(data *abbreviationsV2, doc *document.Document, container *cst.Node) error {
	if data.ZettelIds != nil {
		if err := cst.SetAny(container, "zettel_ids", *data.ZettelIds); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.MarklIds != nil {
		if err := cst.SetAny(container, "merkle_ids", *data.MarklIds); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
