// Code generated by dagnabit; DO NOT EDIT.

package plugins

import internal "github.com/amarbel-llc/madder/go/internal/bravo/plugins"

type (
	Factory = internal.Factory
)

var (
	Default                     = internal.Default
	ErrAlreadyRegistered        = internal.ErrAlreadyRegistered
	ErrUnknownLegacyCompression = internal.ErrUnknownLegacyCompression
	ErrUnknownPlugin            = internal.ErrUnknownPlugin
	LegacyCompressionRef        = internal.LegacyCompressionRef
	MustRegister                = internal.MustRegister
	Resolve                     = internal.Resolve
)
