// Code generated by dagnabit; DO NOT EDIT.

package blob_store_env

import internal "github.com/amarbel-llc/madder/go/internal/foxtrot/blob_store_env"

type (
	BlobStoreEnv = internal.BlobStoreEnv
)

var (
	MakeBlobStoreEnv              = internal.MakeBlobStoreEnv
	MakeBlobStoreEnvWithOrder     = internal.MakeBlobStoreEnvWithOrder
	MakeBlobStoreEnvWithoutStores = internal.MakeBlobStoreEnvWithoutStores
)
