// Code generated by dagnabit (0.4.1+2c7eac2); DO NOT EDIT.

package ids

import internal "github.com/amarbel-llc/madder/go/internal/0/ids"

type (
	BuiltinType     = internal.BuiltinType
	Tai             = internal.Tai
	TaiRFC3339Value = internal.TaiRFC3339Value
	TypeStruct      = internal.TypeStruct
)

var (
	GetOrPanic           = internal.GetOrPanic
	MakeTaiRFC3339Value  = internal.MakeTaiRFC3339Value
	MustTypeStruct       = internal.MustTypeStruct
	NowTai               = internal.NowTai
	TaiFromTime          = internal.TaiFromTime
	TaiFromTime1         = internal.TaiFromTime1
	TaiFromTimeWithIndex = internal.TaiFromTimeWithIndex
)

const (
	TypeTomlBlobStoreConfigInventoryArchiveV0       = internal.TypeTomlBlobStoreConfigInventoryArchiveV0
	TypeTomlBlobStoreConfigInventoryArchiveV1       = internal.TypeTomlBlobStoreConfigInventoryArchiveV1
	TypeTomlBlobStoreConfigInventoryArchiveV2       = internal.TypeTomlBlobStoreConfigInventoryArchiveV2
	TypeTomlBlobStoreConfigInventoryArchiveVCurrent = internal.TypeTomlBlobStoreConfigInventoryArchiveVCurrent
	TypeTomlBlobStoreConfigMultiV0                  = internal.TypeTomlBlobStoreConfigMultiV0
	TypeTomlBlobStoreConfigPointerV0                = internal.TypeTomlBlobStoreConfigPointerV0
	TypeTomlBlobStoreConfigPointerV1                = internal.TypeTomlBlobStoreConfigPointerV1
	TypeTomlBlobStoreConfigS3V0                     = internal.TypeTomlBlobStoreConfigS3V0
	TypeTomlBlobStoreConfigSftpExplicitV0           = internal.TypeTomlBlobStoreConfigSftpExplicitV0
	TypeTomlBlobStoreConfigSftpViaSSHConfigV0       = internal.TypeTomlBlobStoreConfigSftpViaSSHConfigV0
	TypeTomlBlobStoreConfigV1                       = internal.TypeTomlBlobStoreConfigV1
	TypeTomlBlobStoreConfigV2                       = internal.TypeTomlBlobStoreConfigV2
	TypeTomlBlobStoreConfigV3                       = internal.TypeTomlBlobStoreConfigV3
	TypeTomlBlobStoreConfigVCurrent                 = internal.TypeTomlBlobStoreConfigVCurrent
	TypeTomlBlobStoreConfigWebdavV0                 = internal.TypeTomlBlobStoreConfigWebdavV0
)
