// Code generated by dagnabit (0.5.0+e463e94); DO NOT EDIT.

package ids

import internal "code.linenisgreat.com/madder/go/internal/0/ids"

type (
	BuiltinType     = internal.BuiltinType
	Tai             = internal.Tai
	TaiRFC3339Value = internal.TaiRFC3339Value
	TypeStruct      = internal.TypeStruct
)

var (
	GetOrPanic           = internal.GetOrPanic
	MakeTaiRFC3339Value  = internal.MakeTaiRFC3339Value
	MustTypeStruct       = internal.MustTypeStruct
	NowTai               = internal.NowTai
	TaiFromTime          = internal.TaiFromTime
	TaiFromTime1         = internal.TaiFromTime1
	TaiFromTimeWithIndex = internal.TaiFromTimeWithIndex
)

const (
	TypeTomlBlobStoreConfigInventoryArchiveV0       = internal.TypeTomlBlobStoreConfigInventoryArchiveV0
	TypeTomlBlobStoreConfigInventoryArchiveV1       = internal.TypeTomlBlobStoreConfigInventoryArchiveV1
	TypeTomlBlobStoreConfigInventoryArchiveV2       = internal.TypeTomlBlobStoreConfigInventoryArchiveV2
	TypeTomlBlobStoreConfigInventoryArchiveV3       = internal.TypeTomlBlobStoreConfigInventoryArchiveV3
	TypeTomlBlobStoreConfigInventoryArchiveVCurrent = internal.TypeTomlBlobStoreConfigInventoryArchiveVCurrent
	TypeTomlBlobStoreConfigMultiV0                  = internal.TypeTomlBlobStoreConfigMultiV0
	TypeTomlBlobStoreConfigMultiV1                  = internal.TypeTomlBlobStoreConfigMultiV1
	TypeTomlBlobStoreConfigPointerV0                = internal.TypeTomlBlobStoreConfigPointerV0
	TypeTomlBlobStoreConfigPointerV1                = internal.TypeTomlBlobStoreConfigPointerV1
	TypeTomlBlobStoreConfigPointerV2                = internal.TypeTomlBlobStoreConfigPointerV2
	TypeTomlBlobStoreConfigS3V0                     = internal.TypeTomlBlobStoreConfigS3V0
	TypeTomlBlobStoreConfigS3V1                     = internal.TypeTomlBlobStoreConfigS3V1
	TypeTomlBlobStoreConfigSftpExplicitV0           = internal.TypeTomlBlobStoreConfigSftpExplicitV0
	TypeTomlBlobStoreConfigSftpExplicitV1           = internal.TypeTomlBlobStoreConfigSftpExplicitV1
	TypeTomlBlobStoreConfigSftpViaSSHConfigV0       = internal.TypeTomlBlobStoreConfigSftpViaSSHConfigV0
	TypeTomlBlobStoreConfigSftpViaSSHConfigV1       = internal.TypeTomlBlobStoreConfigSftpViaSSHConfigV1
	TypeTomlBlobStoreConfigV1                       = internal.TypeTomlBlobStoreConfigV1
	TypeTomlBlobStoreConfigV2                       = internal.TypeTomlBlobStoreConfigV2
	TypeTomlBlobStoreConfigV3                       = internal.TypeTomlBlobStoreConfigV3
	TypeTomlBlobStoreConfigV4                       = internal.TypeTomlBlobStoreConfigV4
	TypeTomlBlobStoreConfigVCurrent                 = internal.TypeTomlBlobStoreConfigVCurrent
	TypeTomlBlobStoreConfigWebdavV0                 = internal.TypeTomlBlobStoreConfigWebdavV0
	TypeTomlBlobStoreConfigWebdavV1                 = internal.TypeTomlBlobStoreConfigWebdavV1
)
