// Code generated by dagnabit (0.5.0+dirty); DO NOT EDIT.

package fd

import internal "code.linenisgreat.com/madder/go/internal/charlie/fd"

type (
	FD         = internal.FD
	KeyerSha   = internal.KeyerSha
	MutableSet = internal.MutableSet
	Set        = internal.Set
	State      = internal.State
	Std        = internal.Std
)

var (
	Base                     = internal.Base
	Dir                      = internal.Dir
	DirBaseOnly              = internal.DirBaseOnly
	DoesDirectoryContainPath = internal.DoesDirectoryContainPath
	Ext                      = internal.Ext
	ExtSansDot               = internal.ExtSansDot
	FileNameSansExt          = internal.FileNameSansExt
	FileNameSansExtRelTo     = internal.FileNameSansExtRelTo
	FsRootDir                = internal.FsRootDir
	MakeFromDirPath          = internal.MakeFromDirPath
	MakeFromFileInfoWithDir  = internal.MakeFromFileInfoWithDir
	MakeFromPath             = internal.MakeFromPath
	MakeFromPathAndDirEntry  = internal.MakeFromPathAndDirEntry
	MakeMutableSet           = internal.MakeMutableSet
	MakeMutableSetSha        = internal.MakeMutableSetSha
	MakeSet                  = internal.MakeSet
	MakeStd                  = internal.MakeStd
	MakeStdFromWriter        = internal.MakeStdFromWriter
	ZettelId                 = internal.ZettelId
)

const (
	StateFileInfo = internal.StateFileInfo
	StateRead     = internal.StateRead
	StateStored   = internal.StateStored
	StateUnknown  = internal.StateUnknown
)
