// Code generated by dagnabit; DO NOT EDIT.

package env_dir

import internal "github.com/amarbel-llc/madder/go/internal/echo/env_dir"

type (
	Config               = internal.Config
	Env                  = internal.Env
	EnvVarNames          = internal.EnvVarNames
	ErrTempAlreadyExists = internal.ErrTempAlreadyExists
	RelativePath         = internal.RelativePath
	RepoId               = internal.RepoId
	TemporaryFS          = internal.TemporaryFS
)

var (
	DefaultEnvVarNames                       = internal.DefaultEnvVarNames
	MakeDefault                              = internal.MakeDefault
	MakeDefaultAndInitialize                 = internal.MakeDefaultAndInitialize
	MakeDefaultNoInit                        = internal.MakeDefaultNoInit
	MakeErrTempAlreadyExists                 = internal.MakeErrTempAlreadyExists
	MakeFromXDGDotenvPath                    = internal.MakeFromXDGDotenvPath
	MakeWithDefaultHome                      = internal.MakeWithDefaultHome
	MakeWithHomeAndInitialize                = internal.MakeWithHomeAndInitialize
	MakeWithXDG                              = internal.MakeWithXDG
	MakeWithXDGRootOverrideHomeAndInitialize = internal.MakeWithXDGRootOverrideHomeAndInitialize
)

const (
	EnvBin               = internal.EnvBin
	EnvVerifyOnCollision = internal.EnvVerifyOnCollision
	OverrideEnvVarName   = internal.OverrideEnvVarName
)
