// Code generated by dagnabit; DO NOT EDIT.

package blob_io

import internal "github.com/amarbel-llc/madder/go/internal/foxtrot/blob_io"

type (
	Config               = internal.Config
	ErrBlobAlreadyExists = internal.ErrBlobAlreadyExists
	ErrBlobMissing       = internal.ErrBlobMissing
	MoveOptions          = internal.MoveOptions
	TemporaryFS          = internal.TemporaryFS
)

var (
	DefaultConfig                                = internal.DefaultConfig
	ErrCollisionContentMismatch                  = internal.ErrCollisionContentMismatch
	IsErrBlobAlreadyExists                       = internal.IsErrBlobAlreadyExists
	IsErrBlobMissing                             = internal.IsErrBlobMissing
	MakeConfig                                   = internal.MakeConfig
	MakeDirIfNecessary                           = internal.MakeDirIfNecessary
	MakeDirIfNecessaryForStringerWithHeadAndTail = internal.MakeDirIfNecessaryForStringerWithHeadAndTail
	MakeHashBucketPath                           = internal.MakeHashBucketPath
	MakeHashBucketPathFromMerkleId               = internal.MakeHashBucketPathFromMerkleId
	MakeHashBucketPathJoinFunc                   = internal.MakeHashBucketPathJoinFunc
	NewFileReaderOrErrNotExist                   = internal.NewFileReaderOrErrNotExist
	NewMover                                     = internal.NewMover
	NewNopReader                                 = internal.NewNopReader
	NewReader                                    = internal.NewReader
	NewWriter                                    = internal.NewWriter
	PathFromHeadAndTail                          = internal.PathFromHeadAndTail
)
